//! A deterministic emitter. No compiler or formatter is invoked at generation time.
use crate::{Error, ErrorKind, ValidatedSchema, ir::*, rust_identifier, validate::IdentifierCase};
use std::fmt::Write;

impl From<std::fmt::Error> for Error {
    fn from(_: std::fmt::Error) -> Self {
        Self::new(ErrorKind::InputLimit, "output", "MAX_OUTPUT exceeded")
    }
}
#[derive(Default)]
struct Output(String);
impl Write for Output {
    fn write_str(&mut self, text: &str) -> std::fmt::Result {
        if self
            .0
            .len()
            .checked_add(text.len())
            .is_none_or(|n| n > MAX_OUTPUT)
        {
            return Err(std::fmt::Error);
        }
        self.0.push_str(text);
        Ok(())
    }
}
fn name(s: &str) -> Result<String, Error> {
    rust_identifier(s, IdentifierCase::Type)
}
fn field(s: &str) -> Result<String, Error> {
    rust_identifier(s, IdentifierCase::Field)
}
fn le(order: ByteOrder) -> bool {
    order == ByteOrder::Little
}
fn documentation(out: &mut Output, doc: &str, fallback: &str) -> Result<(), Error> {
    writeln!(
        out,
        "#[doc = {:?}]",
        if doc.is_empty() { fallback } else { doc }
    )?;
    Ok(())
}
fn header(out: &mut Output, inputs: &[String]) -> Result<(), Error> {
    if inputs.len() > MAX_TYPES {
        return Err(Error::new(
            ErrorKind::InputLimit,
            "inputs",
            "too many input names",
        ));
    }
    writeln!(
        out,
        "// Generated by fictionet-codegen {}.",
        env!("CARGO_PKG_VERSION")
    )?;
    writeln!(
        out,
        "// You own this file. You may copy and edit it. Regenerate only by choice."
    )?;
    for input in inputs {
        let basename = input.rsplit(['/', '\\']).next().unwrap_or("");
        if basename.len() > MAX_NAME {
            return Err(Error::new(
                ErrorKind::InputLimit,
                "inputs",
                "input file name exceeds MAX_NAME",
            ));
        }
        writeln!(out, "// Input: {basename:?}")?;
    }
    writeln!(out)?;
    Ok(())
}
struct Node<'a> {
    ty: &'a Type,
    child: Option<usize>,
}
fn add<'a>(ty: &'a Type, nodes: &mut Vec<Node<'a>>) -> usize {
    let child = match ty {
        Type::Group { item, .. }
        | Type::Optional {
            item,
            presence: Presence::Flag(_),
        } => Some(add(item, nodes)),
        _ => None,
    };
    let index = nodes.len();
    nodes.push(Node { ty, child });
    index
}
fn missing() -> Error {
    Error::new(
        ErrorKind::InvalidLimit,
        "validated IR",
        "missing normalized limit",
    )
}
fn length(len: &Length) -> Result<(usize, usize), Error> {
    match len {
        Length::Fixed(n) => Ok((0, *n)),
        Length::Variable { prefix, limit } => Ok((prefix.bytes(), limit.ok_or_else(missing)?)),
    }
}
fn literal(number: &Number, p: Primitive) -> String {
    match number {
        Number::Integer(n) if p.is_float() => format!("{:?}{}", *n as f64, p.rust()),
        Number::Integer(n) => format!("{n}{}", p.rust()),
        Number::Float(n) => format!("{n:?}{}", p.rust()),
    }
}
fn scalar_sample(p: Primitive) -> String {
    if p.is_float() {
        format!("(s.number() as i32 % 1000) as {}", p.rust())
    } else if p == Primitive::U64 {
        "s.number()".into()
    } else {
        format!("s.number() as {}", p.rust())
    }
}
fn node(out: &mut Output, i: usize, n: &Node<'_>) -> Result<(), Error> {
    let child = n.child.unwrap_or(0);
    let (ty, read, write, sample) = match n.ty {
        Type::Scalar(p) => (
            p.rust().into(),
            format!("r.scalar::<{}>(le)", p.rust()),
            "w.scalar(*v, le)".into(),
            format!("Ok({})", scalar_sample(*p)),
        ),
        Type::Bytes(len) | Type::String(len) => {
            let (width, size) = length(len)?;
            let text = matches!(n.ty, Type::String(_));
            let method = if text { "text" } else { "bytes" };
            let b = if text { "v.as_bytes()" } else { "v" };
            (
                if text {
                    "String".into()
                } else {
                    "Vec<u8>".into()
                },
                format!("r.{method}({width}, __LIMIT{i}, le)"),
                format!("w.bytes({b}, {width}, __LIMIT{i}, le)"),
                format!("s.{method}({width}, __LIMIT{i})"),
            )
                .tap_limit(out, i, size)?
        }
        Type::Ref(s) => {
            let name = name(s)?;
            (
                format!("Box<{name}>"),
                format!("r.reference::<{name}>(le)"),
                "w.reference(v.as_ref(), le)".into(),
                format!("s.reference::<{name}>()"),
            )
        }
        Type::Group { count, limit, .. } => {
            let width = count.bytes();
            let limit = limit.ok_or_else(missing)?;
            (
                format!("Vec<__Value{child}>"),
                format!("r.group({width}, __LIMIT{i}, le, |r| __read{child}(r, le))"),
                format!("w.group(v, {width}, __LIMIT{i}, le, |w, v| __write{child}(w, v, le))"),
                format!("s.group(__LIMIT{i}, __sample{child})"),
            )
                .tap_limit(out, i, limit)?
        }
        Type::Optional { item, presence } => {
            let (read, write, sample) = match presence {
                Presence::Flag(width) => (
                    format!(
                        "r.optional({}, le, |r| __read{child}(r, le))",
                        width.bytes()
                    ),
                    format!(
                        "w.optional(v, {}, le, |w, v| __write{child}(w, v, le))",
                        width.bytes()
                    ),
                    format!("s.optional(__sample{child})"),
                ),
                Presence::Null(null) => {
                    let Type::Scalar(p) = item.as_ref() else {
                        return Err(Error::new(
                            ErrorKind::InvalidValue,
                            "null",
                            "expected scalar",
                        ));
                    };
                    let null = literal(null, *p);
                    (
                        format!("r.nullable({null}, le)"),
                        format!("w.nullable(v, {null}, le)"),
                        format!("s.nullable(value, {null})"),
                    )
                }
            };
            let optional_type = match presence {
                Presence::Null(_) => match item.as_ref() {
                    Type::Scalar(p) => format!("Option<{}>", p.rust()),
                    _ => return Err(missing()),
                },
                Presence::Flag(_) => format!("Option<__Value{child}>"),
            };
            (optional_type, read, write, sample)
        }
    };
    writeln!(out, "type __Value{i} = {ty};")?;
    writeln!(
        out,
        "fn __read{i}(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value{i}, Error> {{\n    {read}\n}}"
    )?;
    writeln!(
        out,
        "fn __write{i}(w: &mut __wire::Writer, v: &__Value{i}, le: bool) -> Result<(), Error> {{\n    {write}\n}}"
    )?;
    writeln!(
        out,
        "#[cfg(test)]\nfn __sample{i}(s: &mut __wire::Sampler) -> Result<__Value{i}, Error> {{"
    )?;
    if let Type::Optional {
        item,
        presence: Presence::Null(_),
    } = n.ty
        && let Type::Scalar(p) = item.as_ref()
    {
        writeln!(out, "    let value = {};", scalar_sample(*p))?;
    }
    writeln!(out, "    {sample}\n}}\n")?;
    Ok(())
}
trait LimitTuple: Sized {
    fn tap_limit(self, out: &mut Output, i: usize, limit: usize) -> Result<Self, Error>;
}
impl LimitTuple for (String, String, String, String) {
    fn tap_limit(self, out: &mut Output, i: usize, limit: usize) -> Result<Self, Error> {
        writeln!(out, "const __LIMIT{i}: usize = {limit};")?;
        Ok(self)
    }
}

/// Emits one self-contained Rust module using only public Fictionet APIs.
/// Input names appear as escaped basenames in the copy-and-own header.
/// Declaration order is preserved. No files or processes are accessed.
pub fn emit(checked: &ValidatedSchema, inputs: &[String]) -> Result<String, Error> {
    let mut out = Output::default();
    header(&mut out, inputs)?;
    if !checked.schema.doc.is_empty() {
        writeln!(out, "// Schema: {:?}\n", checked.schema.doc)?;
    }
    let limits = checked.limits;
    for (name, value, doc) in [
        (
            "MAX_MESSAGE",
            limits.max_message,
            "Maximum encoded bytes in one value.",
        ),
        (
            "MAX_COLLECTION",
            limits.max_collection,
            "Default limit used for omitted collection lengths.",
        ),
        (
            "MAX_DEPTH",
            limits.max_depth,
            "Maximum nested value operations, including named types and groups.",
        ),
        (
            "MAX_ALLOCATION",
            limits.max_allocation,
            "Maximum requested heap bytes for a decoded value.",
        ),
        (
            "MAX_NODES",
            limits.max_nodes,
            "Maximum visited structural nodes in one value.",
        ),
    ] {
        writeln!(out, "/// {doc}\npub const {name}: usize = {value};")?;
    }
    writeln!(out)?;
    out.write_str(include_str!("runtime.txt"))?;
    let mut nodes = Vec::new();
    let mut field_nodes = Vec::new();
    for t in &checked.schema.types {
        let mut ids = Vec::new();
        if let Definition::Struct(fs) = &t.definition {
            for f in fs {
                ids.push(add(&f.ty, &mut nodes));
            }
        }
        field_nodes.push(ids);
    }
    writeln!(out)?;
    for (i, n) in nodes.iter().enumerate() {
        node(&mut out, i, n)?;
    }
    for (t, ids) in checked.schema.types.iter().zip(&field_nodes) {
        let rust = name(&t.name)?;
        documentation(&mut out, &t.doc, &format!("Wire type {}.", t.name))?;
        match &t.definition {
            Definition::Struct(fs) if fs.is_empty() => {
                writeln!(
                    out,
                    "#[derive(Clone, Debug, PartialEq)]\npub struct {rust} {{}}"
                )?;
            }
            Definition::Struct(fs) => {
                writeln!(out, "#[derive(Clone, Debug, PartialEq)]")?;
                let gap = if rust.len() + 13 > 100 { "\n" } else { " " };
                writeln!(out, "pub struct {rust}{gap}{{")?;
                for (f, id) in fs.iter().zip(ids) {
                    writeln!(
                        out,
                        "    #[doc = {:?}]",
                        if f.doc.is_empty() {
                            f.name.as_str()
                        } else {
                            &f.doc
                        }
                    )?;
                    let field = field(&f.name)?;
                    let line = format!("    pub {field}: __Value{id},");
                    if line.len() <= 100 {
                        writeln!(out, "{line}")?;
                    } else {
                        writeln!(out, "    pub {field}:\n        __Value{id},")?;
                    }
                }
                writeln!(out, "}}")?;
            }
            Definition::Enum { variants, .. } => {
                writeln!(
                    out,
                    "#[derive(Clone, Copy, Debug, PartialEq, Eq)]\npub enum {rust} {{"
                )?;
                for v in variants {
                    writeln!(
                        out,
                        "    #[doc = {:?}]\n    {},",
                        if v.doc.is_empty() {
                            v.name.as_str()
                        } else {
                            &v.doc
                        },
                        name(&v.name)?
                    )?;
                }
                writeln!(out, "}}")?;
            }
            Definition::Set { repr, bits } => {
                let scalar = format!("u{}", repr.bytes() * 8);
                writeln!(
                    out,
                    "#[derive(Clone, Copy, Debug, PartialEq, Eq)]\npub struct {rust}(\n    /// Declared bits only. Unknown bits are refused by the writer.\n    pub {scalar},\n);"
                )?;
                if !bits.is_empty() {
                    writeln!(out, "impl {rust} {{")?;
                }
                for b in bits {
                    writeln!(
                        out,
                        "    #[doc = {:?}]\n    pub const {}: {scalar} = 1 << {};",
                        if b.doc.is_empty() {
                            b.name.as_str()
                        } else {
                            &b.doc
                        },
                        rust_identifier(&b.name, IdentifierCase::Constant)?,
                        b.bit
                    )?;
                }
                if !bits.is_empty() {
                    writeln!(out, "}}")?;
                }
            }
        }
        writeln!(
            out,
            "impl __wire::Codec for {rust} {{\n    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {{"
        )?;
        writeln!(out, "        r.nested(|r| {{")?;
        match &t.definition {
            Definition::Struct(fs) if fs.is_empty() => {
                writeln!(
                    out,
                    "            let _ = (r, le);\n            Ok(Self {{}})"
                )?;
            }
            Definition::Struct(fs) => {
                if fs.is_empty() {
                    writeln!(out, "            let _ = (r, le);")?;
                }
                writeln!(out, "            Ok(Self {{")?;
                for (f, id) in fs.iter().zip(ids) {
                    writeln!(
                        out,
                        "                {}: __read{id}(r, {})?,",
                        field(&f.name)?,
                        f.byte_order
                            .map(le)
                            .map(|b| b.to_string())
                            .unwrap_or("le".into())
                    )?;
                }
                writeln!(out, "            }})")?;
            }
            Definition::Enum { repr, variants } => {
                writeln!(
                    out,
                    "            let v = r.scalar::<{}>(le)?;\n            match v {{",
                    repr.rust()
                )?;
                for v in variants {
                    writeln!(
                        out,
                        "                {} => Ok(Self::{}),",
                        v.value,
                        name(&v.name)?
                    )?;
                }
                writeln!(
                    out,
                    "                _ => Err(Error::Value),\n            }}"
                )?;
            }
            Definition::Set { repr, bits } => {
                let mask = bits.iter().fold(0u64, |mask, b| mask | (1u64 << b.bit));
                writeln!(
                    out,
                    "            let v = r.scalar::<u{}>(le)?;",
                    repr.bytes() * 8
                )?;
                if mask != repr.max() {
                    let condition = if mask == 0 {
                        "v != 0".into()
                    } else {
                        format!("v & !{mask} != 0")
                    };
                    writeln!(
                        out,
                        "            if {condition} {{\n                return Err(Error::Value);\n            }}"
                    )?;
                }
                writeln!(out, "            Ok(Self(v))")?;
            }
        }
        writeln!(
            out,
            "        }})\n    }}\n    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {{\n        w.nested(|w| {{"
        )?;
        match &t.definition {
            Definition::Struct(fs) => {
                if fs.is_empty() {
                    writeln!(out, "            let _ = (w, le);")?;
                }
                for (f, id) in fs.iter().zip(ids) {
                    writeln!(
                        out,
                        "            __write{id}(w, &self.{}, {})?;",
                        field(&f.name)?,
                        f.byte_order
                            .map(le)
                            .map(|b| b.to_string())
                            .unwrap_or("le".into())
                    )?;
                }
                writeln!(out, "            Ok(())")?;
            }
            Definition::Enum { repr, variants } => {
                writeln!(out, "            let v: {} = match self {{", repr.rust())?;
                for v in variants {
                    writeln!(
                        out,
                        "                Self::{} => {},",
                        name(&v.name)?,
                        v.value
                    )?;
                }
                writeln!(out, "            }};\n            w.scalar(v, le)")?;
            }
            Definition::Set { repr, bits } => {
                let mask = bits.iter().fold(0u64, |mask, b| mask | (1u64 << b.bit));
                writeln!(out, "            let v = self.0;")?;
                if mask != repr.max() {
                    let condition = if mask == 0 {
                        "v != 0".into()
                    } else {
                        format!("v & !{mask} != 0")
                    };
                    writeln!(
                        out,
                        "            if {condition} {{\n                return Err(Error::Value);\n            }}"
                    )?;
                }
                writeln!(out, "            w.scalar(v, le)")?;
            }
        }
        writeln!(
            out,
            "        }})\n    }}\n    #[cfg(test)]\n    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {{\n        s.nested(|s| {{"
        )?;
        match &t.definition {
            Definition::Struct(fs) if fs.is_empty() => {
                writeln!(out, "            let _ = s;\n            Ok(Self {{}})")?;
            }
            Definition::Struct(fs) => {
                if fs.is_empty() {
                    writeln!(out, "            let _ = s;")?;
                }
                writeln!(out, "            Ok(Self {{")?;
                for (f, id) in fs.iter().zip(ids) {
                    writeln!(
                        out,
                        "                {}: __sample{id}(s)?,",
                        field(&f.name)?
                    )?;
                }
                writeln!(out, "            }})")?;
            }
            Definition::Enum { variants, .. } if variants.len() == 1 => {
                let variant = variants.first().ok_or_else(missing)?;
                writeln!(
                    out,
                    "            let _ = s;\n            Ok(Self::{})",
                    name(&variant.name)?
                )?;
            }
            Definition::Enum { variants, .. } => {
                writeln!(
                    out,
                    "            Ok(match s.rng.below({}) {{",
                    variants.len()
                )?;
                for (i, v) in variants.iter().enumerate() {
                    let arm = if i + 1 == variants.len() {
                        "_".to_string()
                    } else {
                        i.to_string()
                    };
                    writeln!(out, "                {arm} => Self::{},", name(&v.name)?)?;
                }
                writeln!(out, "            }})")?;
            }
            Definition::Set { repr, bits } => {
                let mask = bits.iter().fold(0u64, |mask, b| mask | (1u64 << b.bit));
                let random = if *repr == Width::U64 {
                    "s.number()".to_string()
                } else {
                    format!("s.number() as u{}", repr.bytes() * 8)
                };
                if mask == 0 {
                    writeln!(out, "            let _ = s;\n            Ok(Self(0))")?;
                } else if mask == repr.max() {
                    writeln!(
                        out,
                        "            let v = {random};\n            Ok(Self(v))"
                    )?;
                } else {
                    writeln!(
                        out,
                        "            let v = {random} & {mask};\n            Ok(Self(v))"
                    )?;
                }
            }
        }
        writeln!(out, "        }})\n    }}\n}}")?;
        writeln!(
            out,
            "impl fictionet::stdlib::codec::Wire for {rust} {{\n    type ParseError = Error;\n    type WriteError = Error;\n\n    /// Reads one exact value. Refuses truncation, trailing bytes, invalid values,\n    /// non-finite floats, invalid UTF-8, and all declared resource limits.\n    fn parse(bytes: &[u8]) -> Result<Self, Error> {{\n        __wire::parse(bytes, {})\n    }}\n\n    /// Appends one value. Refuses invalid values, wrong fixed sizes, reserved\n    /// nulls in Some, non-finite floats, and resource limits. Errors leave out unchanged.\n    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {{\n        __wire::write(self, out, {})\n    }}\n}}\n",
            le(checked.schema.byte_order),
            le(checked.schema.byte_order)
        )?;
    }
    for s in &checked.schema.streams {
        stream(&mut out, s, checked.schema.byte_order)?;
    }
    tests(&mut out, checked)?;
    Ok(out.0)
}
fn stream(out: &mut Output, s: &Stream, body: ByteOrder) -> Result<(), Error> {
    let rust = name(&s.name)?;
    let item = name(&s.item)?;
    let width = s.prefix.bytes();
    let prefix_le = le(s.byte_order);
    let body_le = le(body);
    let magic = format!("b\"{}\"", s.magic.escape_ascii());
    let signature =
        format!("    pub fn write(value: &{item}, out: &mut Vec<u8>) -> Result<(), Error> {{");
    let signature = if signature.len() > 100 {
        format!(
            "    pub fn write(\n        value: &{item},\n        out: &mut Vec<u8>,\n    ) -> Result<(), Error> {{"
        )
    } else {
        signature
    };
    writeln!(
        out,
        "/// Frames of [`{item}`], with fixed magic and a body-length prefix.\n#[derive(Clone, Copy, Debug, Default)]\npub struct {rust};\nimpl {rust} {{\n    const MAGIC: &'static [u8] = {magic};\n\n    /// Appends a complete frame. Refuses invalid bodies and prefix overflow.\n    /// Errors leave the destination unchanged.\n{signature}\n        __wire::write_frame(value, out, Self::MAGIC, {width}, {prefix_le}, {body_le})\n    }}\n}}\nimpl fictionet::stdlib::codec::Decode for {rust} {{\n    type Item = {item};\n    type Error = Error;\n    const NAME: &'static str = {:?};\n\n    fn capacity(&self) -> usize {{\n        MAX_MESSAGE + {}\n    }}\n\n    /// Refuses bad magic, oversized prefixes, and invalid complete bodies.\n    /// Partial frames return Need, including at EOF. Holds no input.\n    fn decode(\n        &mut self,\n        input: &[u8],\n        _eof: bool,\n    ) -> Result<fictionet::stdlib::codec::Step<Self::Item>, Error> {{\n        __wire::frame(input, Self::MAGIC, {width}, {prefix_le}, {body_le})\n    }}\n}}\n",
        s.name,
        s.magic.len() + width
    )?;
    Ok(())
}
fn tests(out: &mut Output, checked: &ValidatedSchema) -> Result<(), Error> {
    writeln!(
        out,
        "#[cfg(test)]\nmod generated_tests {{\n    use super::*;\n    use fictionet::stdlib::codec::{{Wire as _, contract}};\n\n    #[test]\n    fn generated_contracts() -> Result<(), Error> {{\n        for seed in 0..32 {{\n            let mut s = __wire::Sampler::seed(seed);"
    )?;
    for t in &checked.schema.types {
        let n = name(&t.name)?;
        writeln!(
            out,
            "            if let Ok(value) = <{n} as __wire::Codec>::sample(&mut s) {{\n                contract::check_wire_value(&value);\n                if let Ok(bytes) = value.to_bytes() {{\n                    assert_eq!({n}::parse(&bytes)?, value);\n                }}\n            }}"
        )?;
    }
    for stream in &checked.schema.streams {
        let n = name(&stream.item)?;
        let f = name(&stream.name)?;
        writeln!(
            out,
            "            if let Ok(value) = <{n} as __wire::Codec>::sample(&mut s) {{\n                let mut bytes = Vec::new();\n                if {f}::write(&value, &mut bytes).is_ok() {{\n                    contract::check_decode_with_alloc_limit(\n                        || {f},\n                        &bytes,\n                        2 * (MAX_MESSAGE + {}),\n                    );\n                }}\n            }}",
            stream.magic.len() + stream.prefix.bytes()
        )?;
    }
    writeln!(out, "        }}\n        Ok(())\n    }}\n}}")?;
    Ok(())
}

/// Emits a cargo-fuzz target for all generated wire types and framers.
/// `module_path` is the target-relative path to the generated module file.
/// The target needs `fictionet` and `libfuzzer-sys`; the generator does not.
pub fn emit_fuzz(
    checked: &ValidatedSchema,
    module_path: &str,
    inputs: &[String],
) -> Result<String, Error> {
    if module_path.len() > MAX_INPUT {
        return Err(Error::new(
            ErrorKind::InputLimit,
            "module_path",
            "path too long",
        ));
    }
    let mut out = Output::default();
    header(&mut out, inputs)?;
    writeln!(
        out,
        "#![no_main]\n\n#[allow(dead_code)]\n#[path = {module_path:?}]\nmod protocol;\n\nuse fictionet::stdlib::codec::contract;\nuse libfuzzer_sys::fuzz_target;\n\nfuzz_target!(|data: &[u8]| {{"
    )?;
    for t in &checked.schema.types {
        writeln!(
            out,
            "    contract::check_wire::<protocol::{}>(data);",
            name(&t.name)?
        )?;
    }
    for s in &checked.schema.streams {
        writeln!(
            out,
            "    contract::check_decode_with_alloc_limit(\n        || protocol::{},\n        data,\n        2 * (protocol::MAX_MESSAGE + {}),\n    );",
            name(&s.name)?,
            s.magic.len() + s.prefix.bytes()
        )?;
    }
    writeln!(out, "}});")?;
    Ok(out.0)
}
