//! A deterministic emitter. No compiler or formatter is invoked at generation time.
use crate::{Error, ErrorKind, ValidatedSchema, ir::*, rust_identifier, validate::IdentifierCase};
use std::{collections::BTreeSet, fmt::Write};

impl From<std::fmt::Error> for Error {
    fn from(_: std::fmt::Error) -> Self {
        Self::new(ErrorKind::InputLimit, "output", "MAX_OUTPUT exceeded")
    }
}
#[derive(Default)]
struct Output(String);
impl Write for Output {
    fn write_str(&mut self, text: &str) -> std::fmt::Result {
        if self
            .0
            .len()
            .checked_add(text.len())
            .is_none_or(|n| n > MAX_OUTPUT)
        {
            return Err(std::fmt::Error);
        }
        self.0.push_str(text);
        Ok(())
    }
}
// Prefer the first layout that fits. The final choice is the fallback for
// identifiers that cannot fit on a line by themselves.
fn layout(width: usize, choices: &[String]) -> String {
    choices
        .iter()
        .find(|s| s.lines().all(|line| line.len() <= width))
        .or_else(|| choices.last())
        .cloned()
        .unwrap_or_default()
}
fn braced(header: &str) -> String {
    layout(100, &[format!("{header} {{"), format!("{header}\n{{")])
}
fn implementation(trait_name: Option<&str>, rust: &str) -> String {
    let (flat, split) = match trait_name {
        Some(t) => (
            format!("impl {t} for {rust} {{"),
            format!("impl {t}\n    for {rust}\n{{"),
        ),
        None => (format!("impl {rust} {{"), format!("impl\n    {rust}\n{{")),
    };
    layout(100, &[flat.clone(), split, flat])
}
fn assignment(prefix: &str, value: &str, suffix: &str, indent: usize) -> String {
    let flat = format!("{prefix} {value}{suffix}");
    let split = format!("{prefix}\n{}{value}{suffix}", " ".repeat(indent));
    layout(100, &[flat.clone(), split, flat])
}
fn type_layout(prefix: &str, ty: &str, suffix: &str, indent: usize) -> String {
    let flat = format!("{prefix}{ty}{suffix}");
    let Some((outer, inner)) = ty.split_once('<') else {
        return flat;
    };
    let inner = inner.strip_suffix('>').unwrap_or(inner);
    let split = format!(
        "{prefix}{outer}<\n{}\n{}>{suffix}",
        type_layout(&" ".repeat(indent + 4), inner, ",", indent + 4),
        " ".repeat(indent)
    );
    layout(100, &[flat.clone(), split, flat])
}
fn public_field(field: &str, ty: &str) -> String {
    let prefix = format!("    pub {field}:");
    layout(
        100,
        &[
            format!("{prefix} {ty},"),
            format!("{prefix}\n        {ty},"),
            type_layout(&format!("{prefix} "), ty, ",", 4),
            format!("{prefix}\n{}", type_layout("        ", ty, ",", 8)),
        ],
    )
}
fn import(module: &str, name: &str, alias: &str) -> String {
    if name == alias {
        format!("use {module}::{name};")
    } else {
        format!("use {module}::{name} as {alias};")
    }
}
fn name(s: &str) -> Result<String, Error> {
    rust_identifier(s, IdentifierCase::Type)
}
fn field(s: &str) -> Result<String, Error> {
    rust_identifier(s, IdentifierCase::Field)
}
fn le(order: ByteOrder) -> bool {
    order == ByteOrder::Little
}
fn documentation(out: &mut Output, doc: &str, fallback: &str) -> Result<(), Error> {
    writeln!(
        out,
        "#[doc = {:?}]",
        if doc.is_empty() { fallback } else { doc }
    )?;
    Ok(())
}
fn header(out: &mut Output, inputs: &[String]) -> Result<(), Error> {
    if inputs.len() > MAX_TYPES {
        return Err(Error::new(
            ErrorKind::InputLimit,
            "inputs",
            "too many input names",
        ));
    }
    writeln!(
        out,
        "// Generated by fictionet-codegen {}.",
        env!("CARGO_PKG_VERSION")
    )?;
    writeln!(
        out,
        "// You own this file. You may copy and edit it. Regenerate only by choice."
    )?;
    for input in inputs {
        let basename = input.rsplit(['/', '\\']).next().unwrap_or("");
        if basename.len() > MAX_NAME {
            return Err(Error::new(
                ErrorKind::InputLimit,
                "inputs",
                "input file name exceeds MAX_NAME",
            ));
        }
        writeln!(out, "// Input: {basename:?}")?;
    }
    writeln!(out)?;
    Ok(())
}
struct Node<'a> {
    ty: &'a Type,
    child: Option<usize>,
    rust: String,
    boxed: bool,
    minimum: usize,
}
fn add<'a>(
    ty: &'a Type,
    nodes: &mut Vec<Node<'a>>,
    owner: &str,
    checked: &ValidatedSchema,
    in_vec: bool,
) -> Result<usize, Error> {
    let child = match ty {
        Type::Group { item, .. } => Some(add(item, nodes, owner, checked, true)?),
        Type::Optional {
            item,
            presence: Presence::Flag(_),
        } => Some(add(item, nodes, owner, checked, in_vec)?),
        _ => None,
    };
    let boxed =
        matches!(ty, Type::Ref(target) if !in_vec && checked.recursion.needs_box(owner, target));
    let rust = match ty {
        Type::Scalar(p) => p.rust().into(),
        Type::Bytes(_) => "Vec<u8>".into(),
        Type::String(_) => "String".into(),
        Type::Ref(n) => {
            if boxed {
                format!("Box<{}>", name(n)?)
            } else {
                name(n)?
            }
        }
        Type::Group { .. } => format!("Vec<{}>", nodes[child.ok_or_else(missing)?].rust),
        Type::Optional { item, presence } => {
            let inner = match presence {
                Presence::Flag(_) => nodes[child.ok_or_else(missing)?].rust.clone(),
                Presence::Null(_) => match item.as_ref() {
                    Type::Scalar(p) => p.rust().into(),
                    _ => return Err(missing()),
                },
            };
            format!("Option<{inner}>")
        }
    };
    let minimum = crate::validate::minimum_type(ty, &checked.minimum)
        .ok_or_else(missing)?
        .size;
    let index = nodes.len();
    nodes.push(Node {
        ty,
        child,
        rust,
        boxed,
        minimum,
    });
    Ok(index)
}
fn missing() -> Error {
    Error::new(
        ErrorKind::InvalidLimit,
        "validated IR",
        "missing normalized limit",
    )
}
fn length(len: &Length) -> Result<(usize, usize), Error> {
    match len {
        Length::Fixed(n) => Ok((0, *n)),
        Length::Variable { prefix, limit } => Ok((prefix.bytes(), limit.ok_or_else(missing)?)),
    }
}
fn literal(number: &Number, p: Primitive) -> String {
    let f = match number {
        Number::Integer(n) => *n as f64,
        Number::Float(n) => *n,
    };
    if p == Primitive::F32 {
        return format!("{:?}f32", f as f32);
    }
    match number {
        Number::Integer(_) if p.is_float() => format!("{f:?}f64"),
        Number::Integer(n) => format!("{n}{}", p.rust()),
        Number::Float(n) => format!("{n:?}{}", p.rust()),
    }
}
fn scalar_sample(p: Primitive) -> String {
    if p.is_float() {
        format!("(s.number() as i32 % 1000) as {}", p.rust())
    } else if p == Primitive::U64 {
        "s.number()".into()
    } else {
        format!("s.number() as {}", p.rust())
    }
}
fn node(out: &mut Output, i: usize, n: &Node<'_>, nodes: &[Node<'_>]) -> Result<(), Error> {
    let child = n.child.unwrap_or(0);
    let (ty, read, write, sample) = match n.ty {
        Type::Scalar(p) => (
            p.rust().into(),
            format!("r.scalar::<{}>(le)", p.rust()),
            "w.scalar(*v, le)".into(),
            format!("Ok({})", scalar_sample(*p)),
        ),
        Type::Bytes(len) | Type::String(len) => {
            let (width, size) = length(len)?;
            let text = matches!(n.ty, Type::String(_));
            let method = if text { "text" } else { "bytes" };
            let b = if text { "v.as_bytes()" } else { "v" };
            writeln!(out, "const __LIMIT{i}: usize = {size};")?;
            (
                if text {
                    "String".into()
                } else {
                    "Vec<u8>".into()
                },
                format!("r.{method}({width}, __LIMIT{i}, le)"),
                format!("w.bytes({b}, {width}, __LIMIT{i}, le)"),
                format!("s.{method}({width}, __LIMIT{i})"),
            )
        }
        Type::Ref(s) => {
            let name = name(s)?;
            if n.boxed {
                (
                    format!("Box<{name}>"),
                    "r.reference(le)".into(),
                    "w.reference(v.as_ref(), le)".into(),
                    "s.reference()".into(),
                )
            } else {
                (
                    name,
                    format!("<__Value{i} as __wire::Codec>::read(r, le)"),
                    "__wire::Codec::encode(v, w, le)".into(),
                    format!("<__Value{i} as __wire::Codec>::sample(s)"),
                )
            }
        }
        Type::Group { count, limit, .. } => {
            let width = count.bytes();
            let limit = limit.ok_or_else(missing)?;
            let minimum = nodes[child].minimum;
            writeln!(out, "const __LIMIT{i}: usize = {limit};")?;
            (
                format!("Vec<__Value{child}>"),
                format!("r.group({width}, __LIMIT{i}, {minimum}, le, |r| __read{child}(r, le))"),
                format!("w.group(v, {width}, __LIMIT{i}, le, |w, v| __write{child}(w, v, le))"),
                format!("s.group(__LIMIT{i}, __sample{child})"),
            )
        }
        Type::Optional { item, presence } => {
            let (read, write, sample) = match presence {
                Presence::Flag(width) => (
                    format!(
                        "r.optional({}, le, |r| __read{child}(r, le))",
                        width.bytes()
                    ),
                    format!(
                        "w.optional(v, {}, le, |w, v| __write{child}(w, v, le))",
                        width.bytes()
                    ),
                    format!("s.optional(__sample{child})"),
                ),
                Presence::Null(null) => {
                    let Type::Scalar(p) = item.as_ref() else {
                        return Err(Error::new(
                            ErrorKind::InvalidValue,
                            "null",
                            "expected scalar",
                        ));
                    };
                    let null = literal(null, *p);
                    (
                        format!("r.nullable({null}, le)"),
                        format!("w.nullable(v, {null}, le)"),
                        format!("s.nullable(value, {null})"),
                    )
                }
            };
            let optional_type = match presence {
                Presence::Null(_) => match item.as_ref() {
                    Type::Scalar(p) => format!("Option<{}>", p.rust()),
                    _ => return Err(missing()),
                },
                Presence::Flag(_) => format!("Option<__Value{child}>"),
            };
            (optional_type, read, write, sample)
        }
    };
    writeln!(
        out,
        "{}",
        assignment(&format!("type __Value{i} ="), &ty, ";", 4)
    )?;
    writeln!(
        out,
        "fn __read{i}(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value{i}, Error> {{\n    {read}\n}}"
    )?;
    writeln!(
        out,
        "fn __write{i}(w: &mut __wire::Writer, v: &__Value{i}, le: bool) -> Result<(), Error> {{\n    {write}\n}}"
    )?;
    writeln!(
        out,
        "#[cfg(test)]\nfn __sample{i}(s: &mut __wire::Sampler) -> Result<__Value{i}, Error> {{"
    )?;
    if let Type::Optional {
        item,
        presence: Presence::Null(_),
    } = n.ty
        && let Type::Scalar(p) = item.as_ref()
    {
        writeln!(out, "    let value = {};", scalar_sample(*p))?;
    }
    writeln!(out, "    {sample}\n}}\n")?;
    Ok(())
}
/// Emits one self-contained Rust module using only public Fictionet APIs.
/// Input names appear as escaped basenames in the copy-and-own header.
/// Declaration order is preserved. No files or processes are accessed.
pub fn emit(checked: &ValidatedSchema, inputs: &[String]) -> Result<String, Error> {
    let mut out = Output::default();
    header(&mut out, inputs)?;
    if !checked.schema.doc.is_empty() {
        writeln!(out, "// Schema: {:?}\n", checked.schema.doc)?;
    }
    let limits = checked.limits;
    for (name, value, doc) in [
        (
            "MAX_MESSAGE",
            limits.max_message,
            "Maximum encoded bytes in one value.",
        ),
        (
            "MAX_COLLECTION",
            limits.max_collection,
            "Default limit used for omitted collection lengths.",
        ),
        (
            "MAX_DEPTH",
            limits.max_depth,
            "Maximum nested value operations, including named types and groups.",
        ),
        (
            "MAX_ALLOCATION",
            limits.max_allocation,
            "Maximum requested heap bytes for a decoded value.",
        ),
        (
            "MAX_NODES",
            limits.max_nodes,
            "Maximum visited structural nodes in one value.",
        ),
    ] {
        writeln!(out, "/// {doc}\npub const {name}: usize = {value};")?;
    }
    writeln!(out)?;
    out.write_str(include_str!("runtime.txt"))?;
    let mut nodes = Vec::new();
    let mut field_nodes = Vec::new();
    for t in &checked.schema.types {
        let mut ids = Vec::new();
        if let Definition::Struct(fs) = &t.definition {
            for f in fs {
                ids.push(add(&f.ty, &mut nodes, &t.name, checked, false)?);
            }
        }
        field_nodes.push(ids);
    }
    writeln!(out)?;
    for (i, n) in nodes.iter().enumerate() {
        node(&mut out, i, n, &nodes)?;
    }
    for (t, ids) in checked.schema.types.iter().zip(&field_nodes) {
        let rust = name(&t.name)?;
        let mask = match &t.definition {
            Definition::Set { bits, .. } => {
                bits.iter().fold(0u64, |mask, b| mask | (1u64 << b.bit))
            }
            _ => 0,
        };
        documentation(&mut out, &t.doc, &format!("Wire type {}.", t.name))?;
        match &t.definition {
            Definition::Struct(fs) => {
                writeln!(out, "#[derive(Clone, Debug, PartialEq)]")?;
                if fs.is_empty() {
                    writeln!(
                        out,
                        "{}",
                        layout(
                            100,
                            &[
                                format!("pub struct {rust} {{}}"),
                                format!("pub struct {rust}\n{{}}")
                            ]
                        )
                    )?;
                } else {
                    writeln!(out, "{}", braced(&format!("pub struct {rust}")))?;
                    for (f, id) in fs.iter().zip(ids) {
                        writeln!(
                            out,
                            "    #[doc = {:?}]",
                            if f.doc.is_empty() { &f.name } else { &f.doc }
                        )?;
                        let field = field(&f.name)?;
                        writeln!(out, "{}", public_field(&field, &nodes[*id].rust))?;
                    }
                    writeln!(out, "}}")?;
                }
            }
            Definition::Enum { variants, .. } => {
                writeln!(
                    out,
                    "#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n{}",
                    braced(&format!("pub enum {rust}"))
                )?;
                for v in variants {
                    writeln!(
                        out,
                        "    #[doc = {:?}]\n    {},",
                        if v.doc.is_empty() { &v.name } else { &v.doc },
                        name(&v.name)?
                    )?;
                }
                writeln!(out, "}}")?;
            }
            Definition::Set { repr, bits } => {
                let scalar = format!("u{}", repr.bytes() * 8);
                writeln!(
                    out,
                    "#[derive(Clone, Copy, Debug, PartialEq, Eq)]\npub struct {rust}(\n    /// Declared bits only. Unknown bits are refused by the writer.\n    pub {scalar},\n);"
                )?;
                if !bits.is_empty() {
                    writeln!(out, "{}", implementation(None, &rust))?;
                    for b in bits {
                        writeln!(
                            out,
                            "    #[doc = {:?}]",
                            if b.doc.is_empty() { &b.name } else { &b.doc }
                        )?;
                        let bit = rust_identifier(&b.name, IdentifierCase::Constant)?;
                        writeln!(
                            out,
                            "{}",
                            layout(
                                100,
                                &[
                                    format!("    pub const {bit}: {scalar} = 1 << {};", b.bit),
                                    format!(
                                        "    pub const {bit}: {scalar} =\n        1 << {};",
                                        b.bit
                                    ),
                                    format!(
                                        "    pub const {bit}:\n        {scalar} = 1 << {};",
                                        b.bit
                                    ),
                                ]
                            )
                        )?;
                    }
                    writeln!(out, "}}")?;
                }
            }
        }
        writeln!(out, "{}", implementation(Some("__wire::Codec"), &rust))?;
        let order_arg = match &t.definition {
            Definition::Struct(fs) if fs.iter().all(|f| f.byte_order.is_some()) => "_le",
            _ => "le",
        };
        writeln!(
            out,
            "    fn read(r: &mut __wire::Reader<'_>, {order_arg}: bool) -> Result<Self, Error> {{\n        r.nested(|r| {{"
        )?;
        match &t.definition {
            Definition::Struct(fs) => struct_value(&mut out, fs, ids, false)?,
            Definition::Enum { repr, variants } => {
                writeln!(
                    out,
                    "            let v = r.scalar::<{}>(le)?;\n            match v {{",
                    repr.rust()
                )?;
                for v in variants {
                    // The binding keeps long variant paths out of nested calls.
                    writeln!(out, "                {} => {{", v.value)?;
                    writeln!(
                        out,
                        "{}",
                        assignment(
                            "                    let value =",
                            &format!("Self::{}", name(&v.name)?),
                            ";",
                            24
                        )
                    )?;
                    writeln!(out, "                    Ok(value)\n                }}")?;
                }
                writeln!(
                    out,
                    "                _ => Err(Error::Value),\n            }}"
                )?;
            }
            Definition::Set { repr, .. } => {
                writeln!(
                    out,
                    "            let v = r.scalar::<u{}>(le)?;",
                    repr.bytes() * 8
                )?;
                set_check(&mut out, *repr, mask)?;
                writeln!(out, "            Ok(Self(v))")?;
            }
        }
        writeln!(
            out,
            "        }})\n    }}\n    fn encode(&self, w: &mut __wire::Writer, {order_arg}: bool) -> Result<(), Error> {{\n        w.nested(|w| {{"
        )?;
        match &t.definition {
            Definition::Struct(fs) => {
                if fs.is_empty() {
                    writeln!(out, "            let _ = w;")?;
                }
                for (f, id) in fs.iter().zip(ids) {
                    // Keep the call independent of the public field's name length.
                    let f_name = field(&f.name)?;
                    let flat = format!("            let value = &self.{f_name};");
                    writeln!(
                        out,
                        "{}",
                        layout(
                            100,
                            &[
                                flat.clone(),
                                format!("            let value =\n                &self.{f_name};"),
                                format!(
                                    "            let value = &self\n                .{f_name};"
                                ),
                                flat,
                            ]
                        )
                    )?;
                    writeln!(
                        out,
                        "            __write{id}(w, value, {})?;",
                        field_order(f)
                    )?;
                }
                writeln!(out, "            Ok(())")?;
            }
            Definition::Enum { repr, variants } => {
                writeln!(out, "            let v: {} = match self {{", repr.rust())?;
                for v in variants {
                    let variant = name(&v.name)?;
                    let flat = format!("                Self::{variant} => {},", v.value);
                    let split = format!(
                        "                Self::{variant} => {{\n                    {}\n                }}",
                        v.value
                    );
                    writeln!(out, "{}", layout(100, &[flat.clone(), split, flat]))?;
                }
                writeln!(out, "            }};\n            w.scalar(v, le)")?;
            }
            Definition::Set { repr, .. } => {
                writeln!(out, "            let v = self.0;")?;
                set_check(&mut out, *repr, mask)?;
                writeln!(out, "            w.scalar(v, le)")?;
            }
        }
        writeln!(
            out,
            "        }})\n    }}\n    #[cfg(test)]\n    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {{\n        s.nested(|s| {{"
        )?;
        match &t.definition {
            Definition::Struct(fs) => struct_value(&mut out, fs, ids, true)?,
            Definition::Enum { variants, .. } if variants.len() == 1 => {
                writeln!(out, "            let _ = s;")?;
                writeln!(
                    out,
                    "{}",
                    assignment(
                        "            let value =",
                        &format!("Self::{}", name(&variants[0].name)?),
                        ";",
                        16
                    )
                )?;
                writeln!(out, "            Ok(value)")?;
            }
            Definition::Enum { variants, .. } => {
                writeln!(
                    out,
                    "            let choice = s.rng.below({});\n            match choice {{",
                    variants.len()
                )?;
                for (i, v) in variants.iter().enumerate() {
                    let arm = if i + 1 == variants.len() {
                        "_".into()
                    } else {
                        i.to_string()
                    };
                    writeln!(out, "                {arm} => {{")?;
                    writeln!(
                        out,
                        "{}",
                        assignment(
                            "                    let value =",
                            &format!("Self::{}", name(&v.name)?),
                            ";",
                            24
                        )
                    )?;
                    writeln!(out, "                    Ok(value)\n                }}")?;
                }
                writeln!(out, "            }}")?;
            }
            Definition::Set { repr, .. } => {
                let random = if *repr == Width::U64 {
                    "s.number()".into()
                } else {
                    format!("s.number() as u{}", repr.bytes() * 8)
                };
                if mask == 0 {
                    writeln!(out, "            let _ = s;\n            Ok(Self(0))")?;
                } else if mask == repr.max() {
                    writeln!(
                        out,
                        "            let v = {random};\n            Ok(Self(v))"
                    )?;
                } else {
                    writeln!(
                        out,
                        "            let v = {random} & {mask};\n            Ok(Self(v))"
                    )?;
                }
            }
        }
        writeln!(out, "        }})\n    }}\n}}")?;
        writeln!(
            out,
            "{}\n    type ParseError = Error;\n    type WriteError = Error;\n",
            implementation(Some("fictionet::stdlib::codec::Wire"), &rust)
        )?;
        wire_docs(&mut out, t, checked, false)?;
        writeln!(
            out,
            "    fn parse(bytes: &[u8]) -> Result<Self, Error> {{\n        __wire::parse(bytes, {})\n    }}\n",
            le(checked.schema.byte_order)
        )?;
        wire_docs(&mut out, t, checked, true)?;
        writeln!(
            out,
            "    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {{\n        __wire::write(self, out, {})\n    }}\n}}\n",
            le(checked.schema.byte_order)
        )?;
    }
    for s in &checked.schema.streams {
        stream(&mut out, s, checked.schema.byte_order)?;
    }
    tests(&mut out, checked)?;
    Ok(out.0)
}
fn field_order(f: &Field) -> String {
    f.byte_order
        .map(le)
        .map(|b| b.to_string())
        .unwrap_or("le".into())
}
fn struct_value(out: &mut Output, fs: &[Field], ids: &[usize], sample: bool) -> Result<(), Error> {
    if fs.is_empty() {
        writeln!(
            out,
            "            let _ = {};\n            Ok(Self {{}})",
            if sample { "s" } else { "r" }
        )?;
        return Ok(());
    }
    let mut members = Vec::new();
    for (f, id) in fs.iter().zip(ids) {
        let expression = if sample {
            format!("__sample{id}(s)?")
        } else {
            format!("__read{id}(r, {})?", field_order(f))
        };
        writeln!(out, "            let __field{id} = {expression};")?;
        members.push((field(&f.name)?, format!("__field{id}")));
    }
    let flat = format!(
        "            let value = Self {{ {} }};",
        members
            .iter()
            .map(|(f, v)| format!("{f}: {v}"))
            .collect::<Vec<_>>()
            .join(", ")
    );
    let mut split = String::from("            let value = Self {\n");
    for (f, v) in members {
        writeln!(
            split,
            "{}",
            assignment(&format!("                {f}:"), &v, ",", 20)
        )?;
    }
    split.push_str("            };");
    // rustfmt's default struct_lit_width is 18 bytes between the braces.
    writeln!(
        out,
        "{}\n            Ok(value)",
        layout(
            18 + "            let value = Self {  };".len(),
            &[flat, split]
        )
    )?;
    Ok(())
}
fn set_check(out: &mut Output, repr: Width, mask: u64) -> Result<(), Error> {
    if mask != repr.max() {
        let condition = if mask == 0 {
            "v != 0".into()
        } else {
            format!("v & !{mask} != 0")
        };
        writeln!(
            out,
            "            if {condition} {{\n                return Err(Error::Value);\n            }}"
        )?;
    }
    Ok(())
}
fn wire_docs(
    out: &mut Output,
    t: &NamedType,
    checked: &ValidatedSchema,
    write: bool,
) -> Result<(), Error> {
    let mut refusals = BTreeSet::new();
    let mut seen = BTreeSet::new();
    let mut pending = vec![t];
    while let Some(t) = pending.pop() {
        if !seen.insert(&t.name) {
            continue;
        }
        match &t.definition {
            Definition::Enum { .. } if !write => {
                refusals.insert("unknown enum values");
            }
            Definition::Set { repr, bits } if bits.len() < repr.bytes() * 8 => {
                refusals.insert("undeclared set bits");
            }
            Definition::Struct(fs) => {
                for f in fs {
                    let mut ty = &f.ty;
                    loop {
                        match ty {
                            Type::Scalar(p) if p.is_float() => {
                                refusals.insert("non-finite floats");
                            }
                            Type::String(_) if !write => {
                                refusals.insert("invalid UTF-8");
                            }
                            Type::Bytes(Length::Fixed(_)) | Type::String(Length::Fixed(_))
                                if write =>
                            {
                                refusals.insert("wrong fixed data lengths");
                            }
                            Type::Ref(n) => {
                                if let Some(t) = checked.schema.types.iter().find(|t| &t.name == n)
                                {
                                    pending.push(t);
                                }
                            }
                            Type::Optional { item, presence } => {
                                match presence {
                                    Presence::Flag(_) if !write => {
                                        refusals.insert("flags other than 0 or 1");
                                    }
                                    Presence::Null(_) if write => {
                                        refusals.insert("reserved nulls in Some");
                                    }
                                    _ => {}
                                }
                                ty = item;
                                continue;
                            }
                            Type::Group { item, .. } => {
                                ty = item;
                                continue;
                            }
                            _ => {}
                        }
                        break;
                    }
                }
            }
            _ => {}
        }
    }
    writeln!(
        out,
        "    /// {}",
        if write {
            "Appends one value. Errors leave out unchanged."
        } else if checked.minimum.get(&t.name).is_some_and(|m| m.size == 0) {
            "Reads one exact value. Refuses trailing bytes."
        } else {
            "Reads one exact value. Refuses truncation and trailing bytes."
        }
    )?;
    writeln!(
        out,
        "    /// Refuses values above the declared resource limits."
    )?;
    for refusal in refusals {
        writeln!(out, "    /// Refuses {refusal}.")?;
    }
    Ok(())
}
fn stream(out: &mut Output, s: &Stream, body: ByteOrder) -> Result<(), Error> {
    let rust = name(&s.name)?;
    let item = name(&s.item)?;
    let width = s.prefix.bytes();
    let prefix_le = le(s.byte_order);
    let body_le = le(body);
    let magic = format!("b\"{}\"", s.magic.escape_ascii());
    writeln!(
        out,
        "/// Frames of [`{item}`], with fixed magic and a body-length prefix.\n#[derive(Clone, Copy, Debug, Default)]\npub struct {rust};\n{}",
        implementation(None, &rust)
    )?;
    writeln!(
        out,
        "{}\n",
        assignment("    const MAGIC: &'static [u8] =", &magic, ";", 8)
    )?;
    writeln!(
        out,
        "    /// Appends a complete frame. Refuses invalid bodies and prefix overflow.\n    /// Errors leave the destination unchanged."
    )?;
    let signature = layout(
        100,
        &[
            format!("    pub fn write(value: &{item}, out: &mut Vec<u8>) -> Result<(), Error> {{"),
            format!(
                "    pub fn write(\n        value: &{item},\n        out: &mut Vec<u8>,\n    ) -> Result<(), Error> {{"
            ),
        ],
    );
    writeln!(
        out,
        "{signature}\n        __wire::write_frame(value, out, Self::MAGIC, {width}, {prefix_le}, {body_le})\n    }}\n}}\n{}",
        implementation(Some("fictionet::stdlib::codec::Decode"), &rust)
    )?;
    writeln!(out, "{}", assignment("    type Item =", &item, ";", 8))?;
    writeln!(out, "    type Error = Error;")?;
    writeln!(
        out,
        "{}\n",
        assignment(
            "    const NAME: &'static str =",
            &format!("{:?}", s.name),
            ";",
            8
        )
    )?;
    writeln!(
        out,
        "    fn capacity(&self) -> usize {{\n        MAX_MESSAGE + {}\n    }}\n\n    /// Refuses bad magic, oversized prefixes, and invalid complete bodies.\n    /// Partial frames return Need, including at EOF. Holds no input.\n    fn decode(\n        &mut self,\n        input: &[u8],\n        _eof: bool,\n    ) -> Result<fictionet::stdlib::codec::Step<Self::Item>, Error> {{\n        __wire::frame(input, Self::MAGIC, {width}, {prefix_le}, {body_le})\n    }}\n}}\n",
        s.magic.len() + width
    )?;
    Ok(())
}
fn tests(out: &mut Output, checked: &ValidatedSchema) -> Result<(), Error> {
    if checked.schema.types.is_empty() {
        return Ok(());
    }
    writeln!(
        out,
        "#[cfg(test)]\nmod generated_tests {{\n    use super::*;\n\n    #[test]\n    fn generated_contracts() -> Result<(), Error> {{"
    )?;
    for t in &checked.schema.types {
        writeln!(
            out,
            "        {{\n            {}\n            __wire::check::<Value>()?;\n        }}",
            import("super", &name(&t.name)?, "Value")
        )?;
    }
    for s in &checked.schema.streams {
        let n = name(&s.name)?;
        writeln!(
            out,
            "        {{\n            {}\n            __wire::check_stream(|| Frames, Frames::write, {});\n        }}",
            import("super", &n, "Frames"),
            s.magic.len() + s.prefix.bytes()
        )?;
    }
    writeln!(out, "        Ok(())\n    }}\n}}")?;
    Ok(())
}

/// Emits a cargo-fuzz target for all generated wire types and framers.
/// `module_path` is the target-relative path to the generated module file.
/// The target needs `fictionet` and `libfuzzer-sys`; the generator does not.
pub fn emit_fuzz(
    checked: &ValidatedSchema,
    module_path: &str,
    inputs: &[String],
) -> Result<String, Error> {
    if module_path.len() > MAX_INPUT {
        return Err(Error::new(
            ErrorKind::InputLimit,
            "module_path",
            "path too long",
        ));
    }
    let mut out = Output::default();
    header(&mut out, inputs)?;
    writeln!(
        out,
        "#![no_main]\n\n#[allow(dead_code)]\n#[path = {module_path:?}]\nmod protocol;\n\nuse fictionet::stdlib::codec::contract;\nuse libfuzzer_sys::fuzz_target;\n\nfuzz_target!(|data: &[u8]| {{"
    )?;
    for t in &checked.schema.types {
        writeln!(
            out,
            "    {{\n        {}\n        contract::check_wire::<Value>(data);\n    }}",
            import("protocol", &name(&t.name)?, "Value")
        )?;
    }
    for s in &checked.schema.streams {
        writeln!(
            out,
            "    {{\n        {}\n        contract::check_decode_with_alloc_limit(|| Frames, data, 2 * (protocol::MAX_MESSAGE + {}));\n    }}",
            import("protocol", &name(&s.name)?, "Frames"),
            s.magic.len() + s.prefix.bytes()
        )?;
    }
    writeln!(out, "}});")?;
    Ok(out.0)
}
