// Generated by fictionet-codegen 0.1.0 from the ir schema.
// Schema: "blocks.json"
// Regenerate with: fictionet-codegen ir "blocks.json" -o <this file>

#![doc = "Blocks, headers, ranges, constants, and offsets."]

/// Maximum encoded bytes in one value.
pub const MAX_MESSAGE: usize = 1048576;
/// Default limit used for omitted collection lengths.
pub const MAX_COLLECTION: usize = 4096;
/// Maximum nested value operations, including named types and groups.
pub const MAX_DEPTH: usize = 32;
/// Maximum requested heap bytes for a decoded value.
pub const MAX_ALLOCATION: usize = 8388608;
/// Maximum visited structural nodes in one value.
pub const MAX_NODES: usize = 65536;

fictionet::stdlib::codec::generated_runtime!(
    Error,
    __wire,
    MAX_MESSAGE,
    MAX_DEPTH,
    MAX_ALLOCATION,
    MAX_NODES
);

const __MIN0: i64 = -9223372036854775807i64;
const __MAX0: i64 = 9223372036854775806i64;
const __NULL0: i64 = 9223372036854775807i64;
type __Value0 = Option<i64>;
#[inline]
fn __read0(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value0, Error> {
    r.nullable_range(__NULL0, __MIN0, __MAX0, le)
}
#[inline]
fn __write0(w: &mut __wire::Writer, v: &__Value0, le: bool) -> Result<(), Error> {
    w.nullable_range(v, __NULL0, __MIN0, __MAX0, le)
}
#[cfg(test)]
fn __sample0(s: &mut __wire::Sampler) -> Result<__Value0, Error> {
    let value = s.ranged(-9223372036854775807, 9223372036854775806) as i64;
    s.nullable(value, __NULL0)
}

type __Value1 = Price;
#[inline]
fn __read1(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value1, Error> {
    <__Value1 as __wire::Codec>::read(r, le)
}
#[inline]
fn __write1(w: &mut __wire::Writer, v: &__Value1, le: bool) -> Result<(), Error> {
    __wire::Codec::encode(v, w, le)
}
#[cfg(test)]
fn __sample1(s: &mut __wire::Sampler) -> Result<__Value1, Error> {
    <__Value1 as __wire::Codec>::sample(s)
}

const __MIN2: u8 = 1u8;
const __MAX2: u8 = 10u8;
type __Value2 = u8;
#[inline]
fn __read2(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value2, Error> {
    r.ranged(__MIN2, __MAX2, le)
}
#[inline]
fn __write2(w: &mut __wire::Writer, v: &__Value2, le: bool) -> Result<(), Error> {
    w.ranged(*v, __MIN2, __MAX2, le)
}
#[cfg(test)]
fn __sample2(s: &mut __wire::Sampler) -> Result<__Value2, Error> {
    Ok(s.ranged(1, 10) as u8)
}

type __Item3 = Side;
type __Value3 = Option<__Item3>;
#[inline]
fn __read3(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value3, Error> {
    r.nullable_ref(0u8, le, |r| <__Item3 as __wire::Codec>::read(r, le))
}
#[inline]
fn __write3(w: &mut __wire::Writer, v: &__Value3, le: bool) -> Result<(), Error> {
    w.nullable_ref(v, 0u8, le, |w, v| __wire::Codec::encode(v, w, le))
}
#[cfg(test)]
fn __sample3(s: &mut __wire::Sampler) -> Result<__Value3, Error> {
    s.maybe(<__Item3 as __wire::Codec>::sample)
}

const __MIN4: u64 = 0u64;
const __MAX4: u64 = 18446744073709551614u64;
type __Value4 = u64;
#[inline]
fn __read4(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value4, Error> {
    r.ranged(__MIN4, __MAX4, le)
}
#[inline]
fn __write4(w: &mut __wire::Writer, v: &__Value4, le: bool) -> Result<(), Error> {
    w.ranged(*v, __MIN4, __MAX4, le)
}
#[cfg(test)]
fn __sample4(s: &mut __wire::Sampler) -> Result<__Value4, Error> {
    Ok(s.ranged(0, 18446744073709551614) as u64)
}

const __LIMIT5: usize = 2;
type __Value5 = Vec<u8>;
#[inline]
fn __read5(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value5, Error> {
    r.bytes(0, __LIMIT5, le)
}
#[inline]
fn __write5(w: &mut __wire::Writer, v: &__Value5, le: bool) -> Result<(), Error> {
    w.bytes(v, 0, __LIMIT5, le)
}
#[cfg(test)]
fn __sample5(s: &mut __wire::Sampler) -> Result<__Value5, Error> {
    s.bytes(0, __LIMIT5)
}

const __LIMIT6: usize = 8;
type __Entry6 = Entry;
type __Value6 = Vec<__Entry6>;
#[inline]
fn __read6(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value6, Error> {
    let header = r.take(4)?;
    let length = __wire::field(header, 0, 2, le, 65534)?;
    let length = usize::try_from(length).map_err(|_| Error::Limit)?;
    let count = __wire::field(header, 3, 1, le, 255)?;
    let count = usize::try_from(count).map_err(|_| Error::Limit)?;
    if count > __LIMIT6 {
        return Err(Error::Limit);
    }
    if length < 11 {
        return Err(Error::Layout);
    }
    r.entries(count, length, |r| __Entry6::__read_block(r, le, length))
}
#[inline]
fn __write6(w: &mut __wire::Writer, v: &__Value6, le: bool) -> Result<(), Error> {
    let count = u64::try_from(v.len()).map_err(|_| Error::Limit)?;
    let mut header = [0u8; 4];
    __wire::put_field(&mut header, 0, 2, le, 16)?;
    __wire::put_field(&mut header, 3, 1, le, count)?;
    w.put(&header)?;
    w.entries(v, __LIMIT6, |w, v| v.__write_block(w, le))
}
#[cfg(test)]
fn __sample6(s: &mut __wire::Sampler) -> Result<__Value6, Error> {
    s.group(__LIMIT6, <__Entry6 as __wire::Codec>::sample)
}

const __LIMIT7: usize = 32;
type __Value7 = Vec<u8>;
#[inline]
fn __read7(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value7, Error> {
    r.bytes(2, __LIMIT7, le)
}
#[inline]
fn __write7(w: &mut __wire::Writer, v: &__Value7, le: bool) -> Result<(), Error> {
    w.bytes(v, 2, __LIMIT7, le)
}
#[cfg(test)]
fn __sample7(s: &mut __wire::Sampler) -> Result<__Value7, Error> {
    s.bytes(2, __LIMIT7)
}

#[doc = "Wire type Side."]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Side {
    #[doc = "buy"]
    Buy,
    #[doc = "sell"]
    Sell,
}
impl __wire::Codec for Side {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            let v = r.scalar::<u8>(le)?;
            match v {
                49 => {
                    let value = Self::Buy;
                    Ok(value)
                }
                50 => {
                    let value = Self::Sell;
                    Ok(value)
                }
                _ => Err(Error::Value),
            }
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let v: u8 = match self {
                Self::Buy => 49,
                Self::Sell => 50,
            };
            w.scalar(v, le)
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let choice = s.rng.below(2);
            match choice {
                0 => {
                    let value = Self::Buy;
                    Ok(value)
                }
                _ => {
                    let value = Self::Sell;
                    Ok(value)
                }
            }
        })
    }
}
impl fictionet::stdlib::codec::Wire for Side {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    /// Refuses unknown enum values.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, true)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, true)
    }
}

#[doc = "A decimal with a fixed exponent."]
#[derive(Clone, Debug, PartialEq)]
pub struct Price {
    #[doc = "mantissa"]
    pub mantissa: Option<i64>,
}
impl Price {
    #[doc = "exponent"]
    pub const EXPONENT: i8 = -9i8;
}
impl __wire::Codec for Price {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            let __field0 = __read0(r, le)?;
            let value = Self { mantissa: __field0 };
            Ok(value)
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let value = &self.mantissa;
            __write0(w, value, le)?;
            Ok(())
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let __field0 = __sample0(s)?;
            let value = Self { mantissa: __field0 };
            Ok(value)
        })
    }
}
impl fictionet::stdlib::codec::Wire for Price {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    /// Refuses values outside declared ranges.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, true)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    /// Refuses reserved nulls in Some.
    /// Refuses values outside declared ranges.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, true)
    }
}

#[doc = "Wire type Entry."]
#[derive(Clone, Debug, PartialEq)]
pub struct Entry {
    #[doc = "price"]
    pub price: Price,
    #[doc = "level"]
    pub level: u8,
    #[doc = "side"]
    pub side: Option<Side>,
}
impl Entry {
    #[doc = "kind"]
    pub const KIND: Side = Side::Buy;
}
impl __wire::Codec for Entry {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        Self::__read_block(r, le, 16)
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        self.__write_block(w, le)
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let __field0 = __sample1(s)?;
            let __field2 = __sample2(s)?;
            let __field3 = __sample3(s)?;
            let value = Self {
                price: __field0,
                level: __field2,
                side: __field3,
            };
            Ok(value)
        })
    }
}
impl Entry {
    fn __read_block(r: &mut __wire::Reader<'_>, le: bool, length: usize) -> Result<Self, Error> {
        r.nested(|r| {
            let __start = r.block(length, 11)?;
            let __field0 = __read1(r, le)?;
            r.skip_to(__start, 9)?;
            let __field2 = __read2(r, le)?;
            let __field3 = __read3(r, le)?;
            r.skip_to(__start, length)?;
            let value = Self {
                price: __field0,
                level: __field2,
                side: __field3,
            };
            Ok(value)
        })
    }
    fn __write_block(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let __start = w.position();
            let value = &self.price;
            __write1(w, value, le)?;
            w.pad_to(__start, 9)?;
            let value = &self.level;
            __write2(w, value, le)?;
            let value = &self.side;
            __write3(w, value, le)?;
            w.pad_to(__start, 16)?;
            Ok(())
        })
    }
}
impl fictionet::stdlib::codec::Wire for Entry {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    /// Refuses unknown enum values.
    /// Refuses values outside declared ranges.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, true)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    /// Refuses reserved nulls in Some.
    /// Refuses values outside declared ranges.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, true)
    }
}

#[doc = "Wire type Book."]
#[derive(Clone, Debug, PartialEq)]
pub struct Book {
    #[doc = "time"]
    pub time: u64,
    #[doc = "code"]
    pub code: Vec<u8>,
    #[doc = "entries"]
    pub entries: Vec<Entry>,
    #[doc = "note"]
    pub note: Vec<u8>,
}
impl Book {
    #[doc = "source"]
    pub const SOURCE: &[u8] = b"8";
}
impl __wire::Codec for Book {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        Self::__read_block(r, le, 12)
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        self.__write_block(w, le)
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let __field0 = __sample4(s)?;
            let __field2 = __sample5(s)?;
            let __field3 = __sample6(s)?;
            let __field4 = __sample7(s)?;
            let value = Self {
                time: __field0,
                code: __field2,
                entries: __field3,
                note: __field4,
            };
            Ok(value)
        })
    }
}
impl Book {
    fn __read_block(r: &mut __wire::Reader<'_>, le: bool, length: usize) -> Result<Self, Error> {
        r.nested(|r| {
            let __start = r.block(length, 11)?;
            let __field0 = __read4(r, le)?;
            r.skip_to(__start, 9)?;
            let __field2 = __read5(r, le)?;
            r.skip_to(__start, length)?;
            let __field3 = __read6(r, le)?;
            let __field4 = __read7(r, le)?;
            let value = Self {
                time: __field0,
                code: __field2,
                entries: __field3,
                note: __field4,
            };
            Ok(value)
        })
    }
    fn __write_block(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let __start = w.position();
            let value = &self.time;
            __write4(w, value, le)?;
            w.pad_to(__start, 9)?;
            let value = &self.code;
            __write5(w, value, le)?;
            w.pad_to(__start, 12)?;
            let value = &self.entries;
            __write6(w, value, le)?;
            let value = &self.note;
            __write7(w, value, le)?;
            Ok(())
        })
    }
}
impl fictionet::stdlib::codec::Wire for Book {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    /// Refuses entry counts above their limits.
    /// Refuses mismatched header values.
    /// Refuses unknown enum values.
    /// Refuses values outside declared ranges.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, true)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    /// Refuses entry counts above their limits.
    /// Refuses reserved nulls in Some.
    /// Refuses values outside declared ranges.
    /// Refuses wrong fixed data lengths.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, true)
    }
}

#[doc = "Wire type Heartbeat."]
#[derive(Clone, Debug, PartialEq)]
pub struct Heartbeat {}
impl __wire::Codec for Heartbeat {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        Self::__read_block(r, le, 0)
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        self.__write_block(w, le)
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let _ = s;
            Ok(Self {})
        })
    }
}
impl Heartbeat {
    fn __read_block(r: &mut __wire::Reader<'_>, _le: bool, length: usize) -> Result<Self, Error> {
        r.nested(|r| {
            let __start = r.block(length, 0)?;
            r.skip_to(__start, length)?;
            Ok(Self {})
        })
    }
    fn __write_block(&self, w: &mut __wire::Writer, _le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let __start = w.position();
            w.pad_to(__start, 0)?;
            Ok(())
        })
    }
}
impl fictionet::stdlib::codec::Wire for Heartbeat {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, true)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, true)
    }
}

#[doc = "A header followed by a block."]
#[derive(Clone, Debug, PartialEq)]
pub enum Message {
    #[doc = "Book"]
    Book(Book),
    #[doc = "Keeps the session open."]
    Heartbeat(Heartbeat),
}
type __Case5x0 = Book;
type __Case5x1 = Heartbeat;
impl __wire::Codec for Message {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            let header = r.take(8)?;
            let length = __wire::field(header, 0, 2, le, 65534)?;
            let length = usize::try_from(length).map_err(|_| Error::Limit)?;
            let tag = __wire::field(header, 2, 2, le, 65534)?;
            if __wire::field(header, 4, 2, le, 65535)? != 7 {
                return Err(Error::Header);
            }
            if __wire::field(header, 6, 2, le, 65534)? < 2 {
                return Err(Error::Header);
            }
            match tag {
                46 => {
                    let value = __Case5x0::__read_block(r, le, length)?;
                    Ok(Self::Book(value))
                }
                12 => {
                    let value = __Case5x1::__read_block(r, le, length)?;
                    Ok(Self::Heartbeat(value))
                }
                _ => Err(Error::Header),
            }
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let mut header = [0u8; 8];
            match self {
                Self::Book(value) => {
                    __wire::put_field(&mut header, 0, 2, le, 12)?;
                    __wire::put_field(&mut header, 2, 2, le, 46)?;
                    __wire::put_field(&mut header, 4, 2, le, 7)?;
                    __wire::put_field(&mut header, 6, 2, le, 3)?;
                    w.put(&header)?;
                    value.__write_block(w, le)
                }
                Self::Heartbeat(value) => {
                    __wire::put_field(&mut header, 0, 2, le, 0)?;
                    __wire::put_field(&mut header, 2, 2, le, 12)?;
                    __wire::put_field(&mut header, 4, 2, le, 7)?;
                    __wire::put_field(&mut header, 6, 2, le, 3)?;
                    w.put(&header)?;
                    value.__write_block(w, le)
                }
            }
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let choice = s.rng.below(2);
            match choice {
                0 => {
                    let value = <__Case5x0 as __wire::Codec>::sample(s)?;
                    Ok(Self::Book(value))
                }
                _ => {
                    let value = <__Case5x1 as __wire::Codec>::sample(s)?;
                    Ok(Self::Heartbeat(value))
                }
            }
        })
    }
}
impl fictionet::stdlib::codec::Wire for Message {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    /// Refuses block lengths that do not hold the fixed fields.
    /// Refuses entry counts above their limits.
    /// Refuses mismatched header values.
    /// Refuses unknown enum values.
    /// Refuses unknown tags.
    /// Refuses values outside declared ranges.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, true)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    /// Refuses entry counts above their limits.
    /// Refuses reserved nulls in Some.
    /// Refuses values outside declared ranges.
    /// Refuses wrong fixed data lengths.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, true)
    }
}

#[cfg(test)]
mod generated_tests {
    use super::*;

    #[test]
    fn generated_contracts() -> Result<(), Error> {
        {
            use super::Side as Value;
            __wire::check::<Value>()?;
        }
        {
            use super::Price as Value;
            __wire::check::<Value>()?;
        }
        {
            use super::Entry as Value;
            __wire::check::<Value>()?;
        }
        {
            use super::Book as Value;
            __wire::check::<Value>()?;
        }
        {
            use super::Heartbeat as Value;
            __wire::check::<Value>()?;
        }
        {
            use super::Message as Value;
            __wire::check::<Value>()?;
        }
        Ok(())
    }
}
