// Generated by fictionet-codegen 0.1.0 from the ir schema.
// Schema: "float_nulls.json"
// Regenerate with: fictionet-codegen ir "float_nulls.json" -o <this file>

#![doc = "Wire types generated by fictionet-codegen."]

/// Maximum encoded bytes in one value.
pub const MAX_MESSAGE: usize = 1048576;
/// Default limit used for omitted collection lengths.
pub const MAX_COLLECTION: usize = 4096;
/// Maximum nested value operations, including named types and groups.
pub const MAX_DEPTH: usize = 32;
/// Maximum requested heap bytes for a decoded value.
pub const MAX_ALLOCATION: usize = 8388608;
/// Maximum visited structural nodes in one value.
pub const MAX_NODES: usize = 65536;

fictionet::stdlib::codec::generated_runtime!(
    Error,
    __wire,
    MAX_MESSAGE,
    MAX_DEPTH,
    MAX_ALLOCATION,
    MAX_NODES
);

type __Value0 = Option<f32>;
#[inline]
fn __read0(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value0, Error> {
    r.nullable(3.4028235e38f32, le)
}
#[inline]
fn __write0(w: &mut __wire::Writer, v: &__Value0, le: bool) -> Result<(), Error> {
    w.nullable(v, 3.4028235e38f32, le)
}
#[cfg(test)]
fn __sample0(s: &mut __wire::Sampler) -> Result<__Value0, Error> {
    let value = (s.number() as i32 % 1000) as f32;
    s.nullable(value, 3.4028235e38f32)
}

type __Value1 = Option<f64>;
#[inline]
fn __read1(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value1, Error> {
    r.nullable(1.7976931348623157e308f64, le)
}
#[inline]
fn __write1(w: &mut __wire::Writer, v: &__Value1, le: bool) -> Result<(), Error> {
    w.nullable(v, 1.7976931348623157e308f64, le)
}
#[cfg(test)]
fn __sample1(s: &mut __wire::Sampler) -> Result<__Value1, Error> {
    let value = (s.number() as i32 % 1000) as f64;
    s.nullable(value, 1.7976931348623157e308f64)
}

type __Value2 = Option<f32>;
#[inline]
fn __read2(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value2, Error> {
    r.nullable(0.1f32, le)
}
#[inline]
fn __write2(w: &mut __wire::Writer, v: &__Value2, le: bool) -> Result<(), Error> {
    w.nullable(v, 0.1f32, le)
}
#[cfg(test)]
fn __sample2(s: &mut __wire::Sampler) -> Result<__Value2, Error> {
    let value = (s.number() as i32 % 1000) as f32;
    s.nullable(value, 0.1f32)
}

type __Value3 = Option<f32>;
#[inline]
fn __read3(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value3, Error> {
    r.nullable(-0.0f32, le)
}
#[inline]
fn __write3(w: &mut __wire::Writer, v: &__Value3, le: bool) -> Result<(), Error> {
    w.nullable(v, -0.0f32, le)
}
#[cfg(test)]
fn __sample3(s: &mut __wire::Sampler) -> Result<__Value3, Error> {
    let value = (s.number() as i32 % 1000) as f32;
    s.nullable(value, -0.0f32)
}

type __Value4 = u8;
#[inline]
fn __read4(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value4, Error> {
    r.scalar::<u8>(le)
}
#[inline]
fn __write4(w: &mut __wire::Writer, v: &__Value4, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample4(s: &mut __wire::Sampler) -> Result<__Value4, Error> {
    Ok(s.number() as u8)
}

type __Value5 = Option<__Value4>;
#[inline]
fn __read5(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value5, Error> {
    r.optional(8, le, |r| __read4(r, le))
}
#[inline]
fn __write5(w: &mut __wire::Writer, v: &__Value5, le: bool) -> Result<(), Error> {
    w.optional(v, 8, le, |w, v| __write4(w, v, le))
}
#[cfg(test)]
fn __sample5(s: &mut __wire::Sampler) -> Result<__Value5, Error> {
    s.optional(__sample4)
}

#[doc = "Wire type Floats."]
#[derive(Clone, Debug, PartialEq)]
pub struct Floats {
    #[doc = "small"]
    pub small: Option<f32>,
    #[doc = "large"]
    pub large: Option<f64>,
    #[doc = "decimal"]
    pub decimal: Option<f32>,
    #[doc = "negative_zero"]
    pub negative_zero: Option<f32>,
    #[doc = "flag"]
    pub flag: Option<u8>,
}
impl __wire::Codec for Floats {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            let __field0 = __read0(r, le)?;
            let __field1 = __read1(r, le)?;
            let __field2 = __read2(r, le)?;
            let __field3 = __read3(r, le)?;
            let __field4 = __read5(r, le)?;
            let value = Self {
                small: __field0,
                large: __field1,
                decimal: __field2,
                negative_zero: __field3,
                flag: __field4,
            };
            Ok(value)
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let value = &self.small;
            __write0(w, value, le)?;
            let value = &self.large;
            __write1(w, value, le)?;
            let value = &self.decimal;
            __write2(w, value, le)?;
            let value = &self.negative_zero;
            __write3(w, value, le)?;
            let value = &self.flag;
            __write5(w, value, le)?;
            Ok(())
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let __field0 = __sample0(s)?;
            let __field1 = __sample1(s)?;
            let __field2 = __sample2(s)?;
            let __field3 = __sample3(s)?;
            let __field4 = __sample5(s)?;
            let value = Self {
                small: __field0,
                large: __field1,
                decimal: __field2,
                negative_zero: __field3,
                flag: __field4,
            };
            Ok(value)
        })
    }
}
impl fictionet::stdlib::codec::Wire for Floats {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    /// Refuses flags other than 0 or 1.
    /// Refuses non-finite floats.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    /// Refuses non-finite floats.
    /// Refuses reserved nulls in Some.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[cfg(test)]
mod generated_tests {
    use super::*;

    #[test]
    fn generated_contracts() -> Result<(), Error> {
        {
            use super::Floats as Value;
            __wire::check::<Value>()?;
        }
        Ok(())
    }
}
