// Generated by fictionet-codegen 0.1.0.
// You own this file. You may copy and edit it. Regenerate only by choice.
// Input: "groups.json"

/// Maximum encoded bytes in one value.
pub const MAX_MESSAGE: usize = 1048576;
/// Default limit used for omitted collection lengths.
pub const MAX_COLLECTION: usize = 4096;
/// Maximum nested value operations, including named types and groups.
pub const MAX_DEPTH: usize = 32;
/// Maximum requested heap bytes for a decoded value.
pub const MAX_ALLOCATION: usize = 8388608;
/// Maximum visited structural nodes in one value.
pub const MAX_NODES: usize = 65536;

/// Why a wire value was refused.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Error {
    /// Input ended within a value.
    Truncated,
    /// Input contains bytes after the value.
    Trailing,
    /// A byte, item, allocation, or work limit was exceeded.
    Limit,
    /// The value exceeds the nesting limit.
    Depth,
    /// A scalar, flag, enum, set, or null encoding is invalid.
    Value,
    /// Text is not UTF-8.
    Utf8,
    /// A stream header does not match its declared magic.
    Header,
    /// Memory reservation failed.
    Allocation,
}
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{self:?}")
    }
}
impl std::error::Error for Error {}

// This support code belongs to this file. It has no SDK-private dependencies.
#[allow(dead_code)]
mod __wire {
    use super::{Error, MAX_ALLOCATION, MAX_DEPTH, MAX_MESSAGE, MAX_NODES};

    // The IR allows at most 256 magic bytes and an eight-byte prefix.
    const MAX_HEADER: usize = 264;

    pub trait Codec: Sized {
        fn read(r: &mut Reader<'_>, le: bool) -> Result<Self, Error>;
        fn encode(&self, w: &mut Writer, le: bool) -> Result<(), Error>;
        #[cfg(test)]
        fn sample(s: &mut Sampler) -> Result<Self, Error>;
    }
    pub trait Scalar: Copy + PartialEq {
        fn read(r: &mut Reader<'_>, le: bool) -> Result<Self, Error>;
        fn encode(self, w: &mut Writer, le: bool) -> Result<(), Error>;
        fn same(self, other: Self) -> bool;
    }
    macro_rules! scalar {
        ($t:ty, $valid:expr, $same:expr) => {
            impl Scalar for $t {
                fn read(r: &mut Reader<'_>, le: bool) -> Result<Self, Error> {
                    let b = r.take(std::mem::size_of::<Self>())?;
                    let a = b.try_into().map_err(|_| Error::Truncated)?;
                    let v = if le {
                        Self::from_le_bytes(a)
                    } else {
                        Self::from_be_bytes(a)
                    };
                    if !($valid)(v) {
                        return Err(Error::Value);
                    }
                    Ok(v)
                }
                fn encode(self, w: &mut Writer, le: bool) -> Result<(), Error> {
                    if !($valid)(self) {
                        return Err(Error::Value);
                    }
                    w.put(&if le {
                        self.to_le_bytes()
                    } else {
                        self.to_be_bytes()
                    })
                }
                fn same(self, other: Self) -> bool {
                    ($same)(self, other)
                }
            }
        };
    }
    scalar!(u8, |_: u8| true, |a: u8, b: u8| a == b);
    scalar!(u16, |_: u16| true, |a: u16, b: u16| a == b);
    scalar!(u32, |_: u32| true, |a: u32, b: u32| a == b);
    scalar!(u64, |_: u64| true, |a: u64, b: u64| a == b);
    scalar!(i8, |_: i8| true, |a: i8, b: i8| a == b);
    scalar!(i16, |_: i16| true, |a: i16, b: i16| a == b);
    scalar!(i32, |_: i32| true, |a: i32, b: i32| a == b);
    scalar!(i64, |_: i64| true, |a: i64, b: i64| a == b);
    scalar!(f32, f32::is_finite, |a: f32, b: f32| a.to_bits()
        == b.to_bits());
    scalar!(f64, f64::is_finite, |a: f64, b: f64| a.to_bits()
        == b.to_bits());

    #[derive(Default)]
    struct Budget {
        depth: usize,
        nodes: usize,
        allocated: usize,
    }
    impl Budget {
        fn enter(&mut self) -> Result<(), Error> {
            if self.depth >= MAX_DEPTH {
                return Err(Error::Depth);
            }
            if self.nodes >= MAX_NODES {
                return Err(Error::Limit);
            }
            self.depth += 1;
            self.nodes += 1;
            Ok(())
        }
        fn charge(&mut self, bytes: usize) -> Result<(), Error> {
            self.allocated = self.allocated.checked_add(bytes).ok_or(Error::Limit)?;
            if self.allocated > MAX_ALLOCATION {
                return Err(Error::Limit);
            }
            Ok(())
        }
    }
    pub struct Reader<'a> {
        bytes: &'a [u8],
        pos: usize,
        budget: Budget,
    }
    impl<'a> Reader<'a> {
        pub fn new(bytes: &'a [u8]) -> Self {
            Self {
                bytes,
                pos: 0,
                budget: Budget::default(),
            }
        }
        pub fn nested<T>(
            &mut self,
            f: impl FnOnce(&mut Self) -> Result<T, Error>,
        ) -> Result<T, Error> {
            self.budget.enter()?;
            let result = f(self);
            self.budget.depth -= 1;
            result
        }
        pub fn take(&mut self, n: usize) -> Result<&'a [u8], Error> {
            let end = self.pos.checked_add(n).ok_or(Error::Limit)?;
            let bytes = self.bytes.get(self.pos..end).ok_or(Error::Truncated)?;
            self.pos = end;
            Ok(bytes)
        }
        pub fn scalar<T: Scalar>(&mut self, le: bool) -> Result<T, Error> {
            T::read(self, le)
        }
        pub fn count(&mut self, width: usize, le: bool, limit: usize) -> Result<usize, Error> {
            let n = match width {
                1 => u64::from(self.scalar::<u8>(le)?),
                2 => u64::from(self.scalar::<u16>(le)?),
                4 => u64::from(self.scalar::<u32>(le)?),
                8 => self.scalar::<u64>(le)?,
                _ => return Err(Error::Value),
            };
            let n = usize::try_from(n).map_err(|_| Error::Limit)?;
            if n > limit {
                return Err(Error::Limit);
            }
            Ok(n)
        }
        pub fn bytes(&mut self, width: usize, size: usize, le: bool) -> Result<Vec<u8>, Error> {
            let n = if width == 0 {
                size
            } else {
                self.count(width, le, size)?
            };
            let b = self.take(n)?;
            self.budget.charge(n)?;
            let mut v = Vec::new();
            v.try_reserve_exact(n).map_err(|_| Error::Allocation)?;
            v.extend_from_slice(b);
            Ok(v)
        }
        pub fn text(&mut self, width: usize, size: usize, le: bool) -> Result<String, Error> {
            String::from_utf8(self.bytes(width, size, le)?).map_err(|_| Error::Utf8)
        }
        pub fn reference<T: Codec>(&mut self, le: bool) -> Result<Box<T>, Error> {
            self.budget.charge(std::mem::size_of::<T>())?;
            Ok(Box::new(T::read(self, le)?))
        }
        pub fn group<T>(
            &mut self,
            width: usize,
            limit: usize,
            le: bool,
            mut f: impl FnMut(&mut Self) -> Result<T, Error>,
        ) -> Result<Vec<T>, Error> {
            let n = self.count(width, le, limit)?;
            let bytes = n
                .checked_mul(std::mem::size_of::<T>())
                .ok_or(Error::Limit)?;
            self.budget.charge(bytes)?;
            if n > MAX_NODES.saturating_sub(self.budget.nodes) {
                return Err(Error::Limit);
            }
            let mut v = Vec::new();
            v.try_reserve_exact(n).map_err(|_| Error::Allocation)?;
            for _ in 0..n {
                v.push(self.nested(&mut f)?);
            }
            Ok(v)
        }
        pub fn optional<T>(
            &mut self,
            width: usize,
            le: bool,
            f: impl FnOnce(&mut Self) -> Result<T, Error>,
        ) -> Result<Option<T>, Error> {
            match self.count(width, le, 1)? {
                0 => Ok(None),
                _ => self.nested(f).map(Some),
            }
        }
        pub fn nullable<T: Scalar>(&mut self, null: T, le: bool) -> Result<Option<T>, Error> {
            let v = self.scalar::<T>(le)?;
            Ok(if v.same(null) { None } else { Some(v) })
        }
    }
    pub struct Writer {
        bytes: Vec<u8>,
        budget: Budget,
    }
    impl Writer {
        pub fn nested(
            &mut self,
            f: impl FnOnce(&mut Self) -> Result<(), Error>,
        ) -> Result<(), Error> {
            self.budget.enter()?;
            let result = f(self);
            self.budget.depth -= 1;
            result
        }
        pub fn put(&mut self, b: &[u8]) -> Result<(), Error> {
            let end = self.bytes.len().checked_add(b.len()).ok_or(Error::Limit)?;
            if end > MAX_MESSAGE {
                return Err(Error::Limit);
            }
            self.bytes
                .try_reserve(b.len())
                .map_err(|_| Error::Allocation)?;
            self.bytes.extend_from_slice(b);
            Ok(())
        }
        pub fn scalar<T: Scalar>(&mut self, value: T, le: bool) -> Result<(), Error> {
            value.encode(self, le)
        }
        pub fn count(&mut self, n: usize, width: usize, le: bool) -> Result<(), Error> {
            match width {
                1 => self.scalar(u8::try_from(n).map_err(|_| Error::Limit)?, le),
                2 => self.scalar(u16::try_from(n).map_err(|_| Error::Limit)?, le),
                4 => self.scalar(u32::try_from(n).map_err(|_| Error::Limit)?, le),
                8 => self.scalar(u64::try_from(n).map_err(|_| Error::Limit)?, le),
                _ => Err(Error::Value),
            }
        }
        pub fn bytes(
            &mut self,
            b: &[u8],
            width: usize,
            size: usize,
            le: bool,
        ) -> Result<(), Error> {
            if (width == 0 && b.len() != size) || b.len() > size {
                return Err(Error::Limit);
            }
            self.budget.charge(b.len())?;
            if width != 0 {
                self.count(b.len(), width, le)?;
            }
            self.put(b)
        }
        pub fn reference<T: Codec>(&mut self, value: &T, le: bool) -> Result<(), Error> {
            self.budget.charge(std::mem::size_of::<T>())?;
            value.encode(self, le)
        }
        pub fn group<T>(
            &mut self,
            values: &[T],
            width: usize,
            limit: usize,
            le: bool,
            mut f: impl FnMut(&mut Self, &T) -> Result<(), Error>,
        ) -> Result<(), Error> {
            if values.len() > limit || values.len() > MAX_NODES.saturating_sub(self.budget.nodes) {
                return Err(Error::Limit);
            }
            let bytes = values
                .len()
                .checked_mul(std::mem::size_of::<T>())
                .ok_or(Error::Limit)?;
            self.budget.charge(bytes)?;
            self.count(values.len(), width, le)?;
            for v in values {
                self.nested(|w| f(w, v))?;
            }
            Ok(())
        }
        pub fn optional<T>(
            &mut self,
            value: &Option<T>,
            width: usize,
            le: bool,
            f: impl FnOnce(&mut Self, &T) -> Result<(), Error>,
        ) -> Result<(), Error> {
            self.count(usize::from(value.is_some()), width, le)?;
            match value {
                Some(v) => self.nested(|w| f(w, v)),
                None => Ok(()),
            }
        }
        pub fn nullable<T: Scalar>(
            &mut self,
            value: &Option<T>,
            null: T,
            le: bool,
        ) -> Result<(), Error> {
            match value {
                Some(v) if v.same(null) => Err(Error::Value),
                Some(v) => self.scalar(*v, le),
                None => self.scalar(null, le),
            }
        }
    }
    #[cfg(test)]
    pub struct Sampler {
        pub rng: fictionet::stdlib::codec::Lcg,
        budget: Budget,
    }
    #[cfg(test)]
    impl Sampler {
        pub fn number(&mut self) -> u64 {
            (self.rng.next() << 33) | (self.rng.next() << 2) | self.rng.below(4)
        }
        pub fn seed(seed: u64) -> Self {
            Self {
                rng: fictionet::stdlib::codec::Lcg::new(seed),
                budget: Budget::default(),
            }
        }
        pub fn nested<T>(
            &mut self,
            f: impl FnOnce(&mut Self) -> Result<T, Error>,
        ) -> Result<T, Error> {
            self.budget.enter()?;
            let result = f(self);
            self.budget.depth -= 1;
            result
        }
        pub fn bytes(&mut self, width: usize, size: usize) -> Result<Vec<u8>, Error> {
            let n = if width == 0 {
                size
            } else {
                self.rng.index(size.min(8).saturating_add(1))
            };
            self.budget.charge(n)?;
            let mut bytes = Vec::new();
            bytes.try_reserve_exact(n).map_err(|_| Error::Allocation)?;
            bytes.resize(n, 0);
            self.rng.fill(&mut bytes);
            Ok(bytes)
        }
        pub fn text(&mut self, width: usize, size: usize) -> Result<String, Error> {
            let mut bytes = self.bytes(width, size)?;
            for b in &mut bytes {
                *b = b'a' + *b % 26;
            }
            String::from_utf8(bytes).map_err(|_| Error::Utf8)
        }
        pub fn reference<T: Codec>(&mut self) -> Result<Box<T>, Error> {
            self.budget.charge(std::mem::size_of::<T>())?;
            Ok(Box::new(T::sample(self)?))
        }
        pub fn group<T>(
            &mut self,
            limit: usize,
            mut f: impl FnMut(&mut Self) -> Result<T, Error>,
        ) -> Result<Vec<T>, Error> {
            let n = if self.budget.depth < 4 {
                self.rng.index(limit.min(2).saturating_add(1))
            } else {
                0
            };
            self.budget.charge(
                n.checked_mul(std::mem::size_of::<T>())
                    .ok_or(Error::Limit)?,
            )?;
            let mut values = Vec::new();
            values.try_reserve_exact(n).map_err(|_| Error::Allocation)?;
            for _ in 0..n {
                values.push(self.nested(&mut f)?);
            }
            Ok(values)
        }
        pub fn optional<T>(
            &mut self,
            f: impl FnOnce(&mut Self) -> Result<T, Error>,
        ) -> Result<Option<T>, Error> {
            if self.budget.depth < 4 && self.rng.coin() {
                self.nested(f).map(Some)
            } else {
                Ok(None)
            }
        }
        pub fn nullable<T: Scalar>(&mut self, value: T, null: T) -> Result<Option<T>, Error> {
            Ok(if value.same(null) || self.rng.coin() {
                None
            } else {
                Some(value)
            })
        }
    }
    pub fn parse<T: Codec>(bytes: &[u8], le: bool) -> Result<T, Error> {
        if bytes.len() > MAX_MESSAGE {
            return Err(Error::Limit);
        }
        let mut r = Reader::new(bytes);
        let value = T::read(&mut r, le)?;
        if r.pos != bytes.len() {
            return Err(Error::Trailing);
        }
        Ok(value)
    }
    pub fn write<T: Codec>(value: &T, out: &mut Vec<u8>, le: bool) -> Result<(), Error> {
        let mut w = Writer {
            bytes: Vec::new(),
            budget: Budget::default(),
        };
        value.encode(&mut w, le)?;
        out.len().checked_add(w.bytes.len()).ok_or(Error::Limit)?;
        out.try_reserve(w.bytes.len())
            .map_err(|_| Error::Allocation)?;
        out.extend_from_slice(&w.bytes);
        Ok(())
    }
    pub fn frame<T: Codec>(
        input: &[u8],
        magic: &[u8],
        width: usize,
        prefix_le: bool,
        body_le: bool,
    ) -> Result<fictionet::stdlib::codec::Step<T>, Error> {
        use fictionet::stdlib::codec::Step;
        let header = magic.len().checked_add(width).ok_or(Error::Limit)?;
        let Some(prefix) = input.get(..header) else {
            return Ok(Step::Need);
        };
        if prefix.get(..magic.len()) != Some(magic) {
            return Err(Error::Header);
        }
        let mut r = Reader::new(prefix.get(magic.len()..).ok_or(Error::Truncated)?);
        let n = r.count(width, prefix_le, MAX_MESSAGE)?;
        let end = header.checked_add(n).ok_or(Error::Limit)?;
        let Some(body) = input.get(header..end) else {
            return Ok(Step::Need);
        };
        Ok(Step::Item(parse(body, body_le)?, end))
    }
    pub fn write_frame<T: Codec>(
        value: &T,
        out: &mut Vec<u8>,
        magic: &[u8],
        width: usize,
        prefix_le: bool,
        body_le: bool,
    ) -> Result<(), Error> {
        let mut body = Vec::new();
        write(value, &mut body, body_le)?;
        let mut header = Writer {
            bytes: Vec::new(),
            budget: Budget::default(),
        };
        // Header storage is at most 264 bytes, independent of the body limit.
        header
            .bytes
            .try_reserve_exact(MAX_HEADER)
            .map_err(|_| Error::Allocation)?;
        header.bytes.extend_from_slice(magic);
        let n = u64::try_from(body.len()).map_err(|_| Error::Limit)?;
        let bytes = if prefix_le {
            n.to_le_bytes()
        } else {
            n.to_be_bytes()
        };
        if width < 8 && n >= (1u64 << (width * 8)) {
            return Err(Error::Limit);
        }
        let prefix = if prefix_le {
            bytes.get(..width)
        } else {
            bytes.get(8usize.checked_sub(width).ok_or(Error::Limit)?..)
        }
        .ok_or(Error::Limit)?;
        header.bytes.extend_from_slice(prefix);
        let total = header
            .bytes
            .len()
            .checked_add(body.len())
            .ok_or(Error::Limit)?;
        out.len().checked_add(total).ok_or(Error::Limit)?;
        out.try_reserve(total).map_err(|_| Error::Allocation)?;
        out.extend_from_slice(&header.bytes);
        out.extend_from_slice(&body);
        Ok(())
    }
}

type __Value0 = Box<Status>;
fn __read0(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value0, Error> {
    r.reference::<Status>(le)
}
fn __write0(w: &mut __wire::Writer, v: &__Value0, le: bool) -> Result<(), Error> {
    w.reference(v.as_ref(), le)
}
#[cfg(test)]
fn __sample0(s: &mut __wire::Sampler) -> Result<__Value0, Error> {
    s.reference::<Status>()
}

type __Value1 = Box<Flags>;
fn __read1(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value1, Error> {
    r.reference::<Flags>(le)
}
fn __write1(w: &mut __wire::Writer, v: &__Value1, le: bool) -> Result<(), Error> {
    w.reference(v.as_ref(), le)
}
#[cfg(test)]
fn __sample1(s: &mut __wire::Sampler) -> Result<__Value1, Error> {
    s.reference::<Flags>()
}

type __Value2 = i32;
fn __read2(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value2, Error> {
    r.scalar::<i32>(le)
}
fn __write2(w: &mut __wire::Writer, v: &__Value2, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample2(s: &mut __wire::Sampler) -> Result<__Value2, Error> {
    Ok(s.number() as i32)
}

const __LIMIT3: usize = 3;
type __Value3 = Vec<__Value2>;
fn __read3(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value3, Error> {
    r.group(1, __LIMIT3, le, |r| __read2(r, le))
}
fn __write3(w: &mut __wire::Writer, v: &__Value3, le: bool) -> Result<(), Error> {
    w.group(v, 1, __LIMIT3, le, |w, v| __write2(w, v, le))
}
#[cfg(test)]
fn __sample3(s: &mut __wire::Sampler) -> Result<__Value3, Error> {
    s.group(__LIMIT3, __sample2)
}

const __LIMIT4: usize = 3;
type __Value4 = Vec<__Value3>;
fn __read4(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value4, Error> {
    r.group(2, __LIMIT4, le, |r| __read3(r, le))
}
fn __write4(w: &mut __wire::Writer, v: &__Value4, le: bool) -> Result<(), Error> {
    w.group(v, 2, __LIMIT4, le, |w, v| __write3(w, v, le))
}
#[cfg(test)]
fn __sample4(s: &mut __wire::Sampler) -> Result<__Value4, Error> {
    s.group(__LIMIT4, __sample3)
}

type __Value5 = Box<Entry>;
fn __read5(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value5, Error> {
    r.reference::<Entry>(le)
}
fn __write5(w: &mut __wire::Writer, v: &__Value5, le: bool) -> Result<(), Error> {
    w.reference(v.as_ref(), le)
}
#[cfg(test)]
fn __sample5(s: &mut __wire::Sampler) -> Result<__Value5, Error> {
    s.reference::<Entry>()
}

const __LIMIT6: usize = 3;
type __Value6 = Vec<__Value5>;
fn __read6(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value6, Error> {
    r.group(1, __LIMIT6, le, |r| __read5(r, le))
}
fn __write6(w: &mut __wire::Writer, v: &__Value6, le: bool) -> Result<(), Error> {
    w.group(v, 1, __LIMIT6, le, |w, v| __write5(w, v, le))
}
#[cfg(test)]
fn __sample6(s: &mut __wire::Sampler) -> Result<__Value6, Error> {
    s.group(__LIMIT6, __sample5)
}

const __LIMIT7: usize = 12;
type __Value7 = String;
fn __read7(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value7, Error> {
    r.text(2, __LIMIT7, le)
}
fn __write7(w: &mut __wire::Writer, v: &__Value7, le: bool) -> Result<(), Error> {
    w.bytes(v.as_bytes(), 2, __LIMIT7, le)
}
#[cfg(test)]
fn __sample7(s: &mut __wire::Sampler) -> Result<__Value7, Error> {
    s.text(2, __LIMIT7)
}

type __Value8 = Option<__Value7>;
fn __read8(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value8, Error> {
    r.optional(2, le, |r| __read7(r, le))
}
fn __write8(w: &mut __wire::Writer, v: &__Value8, le: bool) -> Result<(), Error> {
    w.optional(v, 2, le, |w, v| __write7(w, v, le))
}
#[cfg(test)]
fn __sample8(s: &mut __wire::Sampler) -> Result<__Value8, Error> {
    s.optional(__sample7)
}

type __Value9 = u8;
fn __read9(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value9, Error> {
    r.scalar::<u8>(le)
}
fn __write9(w: &mut __wire::Writer, v: &__Value9, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample9(s: &mut __wire::Sampler) -> Result<__Value9, Error> {
    Ok(s.number() as u8)
}

#[doc = "Wire type Status."]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Status {
    #[doc = "off"]
    Off,
    #[doc = "on"]
    On,
}
impl __wire::Codec for Status {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            let v = r.scalar::<i16>(le)?;
            match v {
                -1 => Ok(Self::Off),
                32767 => Ok(Self::On),
                _ => Err(Error::Value),
            }
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let v: i16 = match self {
                Self::Off => -1,
                Self::On => 32767,
            };
            w.scalar(v, le)
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            Ok(match s.rng.below(2) {
                0 => Self::Off,
                _ => Self::On,
            })
        })
    }
}
impl fictionet::stdlib::codec::Wire for Status {
    type ParseError = Error;
    type WriteError = Error;

    /// Reads one exact value. Refuses truncation, trailing bytes, invalid values,
    /// non-finite floats, invalid UTF-8, and all declared resource limits.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Appends one value. Refuses invalid values, wrong fixed sizes, reserved
    /// nulls in Some, non-finite floats, and resource limits. Errors leave out unchanged.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[doc = "Wire type Flags."]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Flags(
    /// Declared bits only. Unknown bits are refused by the writer.
    pub u64,
);
impl Flags {
    #[doc = "ready"]
    pub const READY: u64 = 1 << 0;
    #[doc = "last"]
    pub const LAST: u64 = 1 << 63;
}
impl __wire::Codec for Flags {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            let v = r.scalar::<u64>(le)?;
            if v & !9223372036854775809 != 0 {
                return Err(Error::Value);
            }
            Ok(Self(v))
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let v = self.0;
            if v & !9223372036854775809 != 0 {
                return Err(Error::Value);
            }
            w.scalar(v, le)
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let v = s.number() & 9223372036854775809;
            Ok(Self(v))
        })
    }
}
impl fictionet::stdlib::codec::Wire for Flags {
    type ParseError = Error;
    type WriteError = Error;

    /// Reads one exact value. Refuses truncation, trailing bytes, invalid values,
    /// non-finite floats, invalid UTF-8, and all declared resource limits.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Appends one value. Refuses invalid values, wrong fixed sizes, reserved
    /// nulls in Some, non-finite floats, and resource limits. Errors leave out unchanged.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[doc = "Wire type Entry."]
#[derive(Clone, Debug, PartialEq)]
pub struct Entry {
    #[doc = "status"]
    pub status: __Value0,
    #[doc = "flags"]
    pub flags: __Value1,
    #[doc = "values"]
    pub values: __Value4,
}
impl __wire::Codec for Entry {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            Ok(Self {
                status: __read0(r, le)?,
                flags: __read1(r, le)?,
                values: __read4(r, true)?,
            })
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            __write0(w, &self.status, le)?;
            __write1(w, &self.flags, le)?;
            __write4(w, &self.values, true)?;
            Ok(())
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            Ok(Self {
                status: __sample0(s)?,
                flags: __sample1(s)?,
                values: __sample4(s)?,
            })
        })
    }
}
impl fictionet::stdlib::codec::Wire for Entry {
    type ParseError = Error;
    type WriteError = Error;

    /// Reads one exact value. Refuses truncation, trailing bytes, invalid values,
    /// non-finite floats, invalid UTF-8, and all declared resource limits.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Appends one value. Refuses invalid values, wrong fixed sizes, reserved
    /// nulls in Some, non-finite floats, and resource limits. Errors leave out unchanged.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[doc = "Wire type Batch."]
#[derive(Clone, Debug, PartialEq)]
pub struct Batch {
    #[doc = "entries"]
    pub entries: __Value6,
    #[doc = "label"]
    pub label: __Value8,
}
impl __wire::Codec for Batch {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            Ok(Self {
                entries: __read6(r, le)?,
                label: __read8(r, le)?,
            })
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            __write6(w, &self.entries, le)?;
            __write8(w, &self.label, le)?;
            Ok(())
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            Ok(Self {
                entries: __sample6(s)?,
                label: __sample8(s)?,
            })
        })
    }
}
impl fictionet::stdlib::codec::Wire for Batch {
    type ParseError = Error;
    type WriteError = Error;

    /// Reads one exact value. Refuses truncation, trailing bytes, invalid values,
    /// non-finite floats, invalid UTF-8, and all declared resource limits.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Appends one value. Refuses invalid values, wrong fixed sizes, reserved
    /// nulls in Some, non-finite floats, and resource limits. Errors leave out unchanged.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[doc = "A type whose source name matches the imported trait."]
#[derive(Clone, Debug, PartialEq)]
pub struct Wire {
    #[doc = "gen"]
    pub gen_: __Value9,
}
impl __wire::Codec for Wire {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            Ok(Self {
                gen_: __read9(r, le)?,
            })
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            __write9(w, &self.gen_, le)?;
            Ok(())
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            Ok(Self {
                gen_: __sample9(s)?,
            })
        })
    }
}
impl fictionet::stdlib::codec::Wire for Wire {
    type ParseError = Error;
    type WriteError = Error;

    /// Reads one exact value. Refuses truncation, trailing bytes, invalid values,
    /// non-finite floats, invalid UTF-8, and all declared resource limits.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Appends one value. Refuses invalid values, wrong fixed sizes, reserved
    /// nulls in Some, non-finite floats, and resource limits. Errors leave out unchanged.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[cfg(test)]
mod generated_tests {
    use super::*;
    use fictionet::stdlib::codec::{Wire as _, contract};

    #[test]
    fn generated_contracts() -> Result<(), Error> {
        for seed in 0..32 {
            let mut s = __wire::Sampler::seed(seed);
            if let Ok(value) = <Status as __wire::Codec>::sample(&mut s) {
                contract::check_wire_value(&value);
                if let Ok(bytes) = value.to_bytes() {
                    assert_eq!(Status::parse(&bytes)?, value);
                }
            }
            if let Ok(value) = <Flags as __wire::Codec>::sample(&mut s) {
                contract::check_wire_value(&value);
                if let Ok(bytes) = value.to_bytes() {
                    assert_eq!(Flags::parse(&bytes)?, value);
                }
            }
            if let Ok(value) = <Entry as __wire::Codec>::sample(&mut s) {
                contract::check_wire_value(&value);
                if let Ok(bytes) = value.to_bytes() {
                    assert_eq!(Entry::parse(&bytes)?, value);
                }
            }
            if let Ok(value) = <Batch as __wire::Codec>::sample(&mut s) {
                contract::check_wire_value(&value);
                if let Ok(bytes) = value.to_bytes() {
                    assert_eq!(Batch::parse(&bytes)?, value);
                }
            }
            if let Ok(value) = <Wire as __wire::Codec>::sample(&mut s) {
                contract::check_wire_value(&value);
                if let Ok(bytes) = value.to_bytes() {
                    assert_eq!(Wire::parse(&bytes)?, value);
                }
            }
        }
        Ok(())
    }
}
