// Generated by fictionet-codegen 0.1.0 from the ir schema.
// Schema: "groups.json"
// Regenerate with: fictionet-codegen ir "groups.json" -o <this file>

#![doc = "Wire types generated by fictionet-codegen."]

/// Maximum encoded bytes in one value.
pub const MAX_MESSAGE: usize = 1048576;
/// Default limit used for omitted collection lengths.
pub const MAX_COLLECTION: usize = 4096;
/// Maximum nested value operations, including named types and groups.
pub const MAX_DEPTH: usize = 32;
/// Maximum requested heap bytes for a decoded value.
pub const MAX_ALLOCATION: usize = 8388608;
/// Maximum visited structural nodes in one value.
pub const MAX_NODES: usize = 65536;

fictionet::stdlib::codec::generated_runtime!(
    Error,
    __wire,
    MAX_MESSAGE,
    MAX_DEPTH,
    MAX_ALLOCATION,
    MAX_NODES
);

type __Value0 = Status;
#[inline]
fn __read0(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value0, Error> {
    <__Value0 as __wire::Codec>::read(r, le)
}
#[inline]
fn __write0(w: &mut __wire::Writer, v: &__Value0, le: bool) -> Result<(), Error> {
    __wire::Codec::encode(v, w, le)
}
#[cfg(test)]
fn __sample0(s: &mut __wire::Sampler) -> Result<__Value0, Error> {
    <__Value0 as __wire::Codec>::sample(s)
}

type __Value1 = Flags;
#[inline]
fn __read1(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value1, Error> {
    <__Value1 as __wire::Codec>::read(r, le)
}
#[inline]
fn __write1(w: &mut __wire::Writer, v: &__Value1, le: bool) -> Result<(), Error> {
    __wire::Codec::encode(v, w, le)
}
#[cfg(test)]
fn __sample1(s: &mut __wire::Sampler) -> Result<__Value1, Error> {
    <__Value1 as __wire::Codec>::sample(s)
}

type __Value2 = i32;
#[inline]
fn __read2(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value2, Error> {
    r.scalar::<i32>(le)
}
#[inline]
fn __write2(w: &mut __wire::Writer, v: &__Value2, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample2(s: &mut __wire::Sampler) -> Result<__Value2, Error> {
    Ok(s.number() as i32)
}

const __LIMIT3: usize = 3;
type __Value3 = Vec<__Value2>;
#[inline]
fn __read3(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value3, Error> {
    r.group(1, __LIMIT3, 4, le, |r| __read2(r, le))
}
#[inline]
fn __write3(w: &mut __wire::Writer, v: &__Value3, le: bool) -> Result<(), Error> {
    w.group(v, 1, __LIMIT3, le, |w, v| __write2(w, v, le))
}
#[cfg(test)]
fn __sample3(s: &mut __wire::Sampler) -> Result<__Value3, Error> {
    s.group(__LIMIT3, __sample2)
}

const __LIMIT4: usize = 3;
type __Value4 = Vec<__Value3>;
#[inline]
fn __read4(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value4, Error> {
    r.group(2, __LIMIT4, 1, le, |r| __read3(r, le))
}
#[inline]
fn __write4(w: &mut __wire::Writer, v: &__Value4, le: bool) -> Result<(), Error> {
    w.group(v, 2, __LIMIT4, le, |w, v| __write3(w, v, le))
}
#[cfg(test)]
fn __sample4(s: &mut __wire::Sampler) -> Result<__Value4, Error> {
    s.group(__LIMIT4, __sample3)
}

type __Value5 = Entry;
#[inline]
fn __read5(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value5, Error> {
    <__Value5 as __wire::Codec>::read(r, le)
}
#[inline]
fn __write5(w: &mut __wire::Writer, v: &__Value5, le: bool) -> Result<(), Error> {
    __wire::Codec::encode(v, w, le)
}
#[cfg(test)]
fn __sample5(s: &mut __wire::Sampler) -> Result<__Value5, Error> {
    <__Value5 as __wire::Codec>::sample(s)
}

const __LIMIT6: usize = 3;
type __Value6 = Vec<__Value5>;
#[inline]
fn __read6(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value6, Error> {
    r.group(1, __LIMIT6, 12, le, |r| __read5(r, le))
}
#[inline]
fn __write6(w: &mut __wire::Writer, v: &__Value6, le: bool) -> Result<(), Error> {
    w.group(v, 1, __LIMIT6, le, |w, v| __write5(w, v, le))
}
#[cfg(test)]
fn __sample6(s: &mut __wire::Sampler) -> Result<__Value6, Error> {
    s.group(__LIMIT6, __sample5)
}

const __LIMIT7: usize = 12;
type __Value7 = String;
#[inline]
fn __read7(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value7, Error> {
    r.text(2, __LIMIT7, le)
}
#[inline]
fn __write7(w: &mut __wire::Writer, v: &__Value7, le: bool) -> Result<(), Error> {
    w.bytes(v.as_bytes(), 2, __LIMIT7, le)
}
#[cfg(test)]
fn __sample7(s: &mut __wire::Sampler) -> Result<__Value7, Error> {
    s.text(2, __LIMIT7)
}

type __Value8 = Option<__Value7>;
#[inline]
fn __read8(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value8, Error> {
    r.optional(2, le, |r| __read7(r, le))
}
#[inline]
fn __write8(w: &mut __wire::Writer, v: &__Value8, le: bool) -> Result<(), Error> {
    w.optional(v, 2, le, |w, v| __write7(w, v, le))
}
#[cfg(test)]
fn __sample8(s: &mut __wire::Sampler) -> Result<__Value8, Error> {
    s.optional(__sample7)
}

type __Value9 = u8;
#[inline]
fn __read9(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value9, Error> {
    r.scalar::<u8>(le)
}
#[inline]
fn __write9(w: &mut __wire::Writer, v: &__Value9, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample9(s: &mut __wire::Sampler) -> Result<__Value9, Error> {
    Ok(s.number() as u8)
}

const __LIMIT10: usize = 255;
type __Value10 = String;
#[inline]
fn __read10(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value10, Error> {
    r.text(1, __LIMIT10, le)
}
#[inline]
fn __write10(w: &mut __wire::Writer, v: &__Value10, le: bool) -> Result<(), Error> {
    w.bytes(v.as_bytes(), 1, __LIMIT10, le)
}
#[cfg(test)]
fn __sample10(s: &mut __wire::Sampler) -> Result<__Value10, Error> {
    s.text(1, __LIMIT10)
}

const __LIMIT11: usize = 1048576;
type __Value11 = Vec<__Value10>;
#[inline]
fn __read11(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value11, Error> {
    r.group(4, __LIMIT11, 1, le, |r| __read10(r, le))
}
#[inline]
fn __write11(w: &mut __wire::Writer, v: &__Value11, le: bool) -> Result<(), Error> {
    w.group(v, 4, __LIMIT11, le, |w, v| __write10(w, v, le))
}
#[cfg(test)]
fn __sample11(s: &mut __wire::Sampler) -> Result<__Value11, Error> {
    s.group(__LIMIT11, __sample10)
}

#[doc = "Wire type Status."]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Status {
    #[doc = "off"]
    Off,
    #[doc = "on"]
    On,
}
impl __wire::Codec for Status {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            let v = r.scalar::<i16>(le)?;
            match v {
                -1 => {
                    let value = Self::Off;
                    Ok(value)
                }
                32767 => {
                    let value = Self::On;
                    Ok(value)
                }
                _ => Err(Error::Value),
            }
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let v: i16 = match self {
                Self::Off => -1,
                Self::On => 32767,
            };
            w.scalar(v, le)
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let choice = s.rng.below(2);
            match choice {
                0 => {
                    let value = Self::Off;
                    Ok(value)
                }
                _ => {
                    let value = Self::On;
                    Ok(value)
                }
            }
        })
    }
}
impl fictionet::stdlib::codec::Wire for Status {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    /// Refuses unknown enum values.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[doc = "Wire type Flags."]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Flags(
    /// Declared bits only. Unknown bits are refused by the writer.
    pub u64,
);
impl Flags {
    #[doc = "ready"]
    pub const READY: u64 = 1 << 0;
    #[doc = "last"]
    pub const LAST: u64 = 1 << 63;
}
impl __wire::Codec for Flags {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            let v = r.scalar::<u64>(le)?;
            if v & !9223372036854775809 != 0 {
                return Err(Error::Value);
            }
            Ok(Self(v))
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let v = self.0;
            if v & !9223372036854775809 != 0 {
                return Err(Error::Value);
            }
            w.scalar(v, le)
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let v = s.number() & 9223372036854775809;
            Ok(Self(v))
        })
    }
}
impl fictionet::stdlib::codec::Wire for Flags {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    /// Refuses undeclared set bits.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    /// Refuses undeclared set bits.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[doc = "Wire type Entry."]
#[derive(Clone, Debug, PartialEq)]
pub struct Entry {
    #[doc = "status"]
    pub status: Status,
    #[doc = "flags"]
    pub flags: Flags,
    #[doc = "values"]
    pub values: Vec<Vec<i32>>,
}
impl __wire::Codec for Entry {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            let __field0 = __read0(r, le)?;
            let __field1 = __read1(r, le)?;
            let __field2 = __read4(r, true)?;
            let value = Self {
                status: __field0,
                flags: __field1,
                values: __field2,
            };
            Ok(value)
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let value = &self.status;
            __write0(w, value, le)?;
            let value = &self.flags;
            __write1(w, value, le)?;
            let value = &self.values;
            __write4(w, value, true)?;
            Ok(())
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let __field0 = __sample0(s)?;
            let __field1 = __sample1(s)?;
            let __field2 = __sample4(s)?;
            let value = Self {
                status: __field0,
                flags: __field1,
                values: __field2,
            };
            Ok(value)
        })
    }
}
impl fictionet::stdlib::codec::Wire for Entry {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    /// Refuses undeclared set bits.
    /// Refuses unknown enum values.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    /// Refuses undeclared set bits.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[doc = "Wire type Batch."]
#[derive(Clone, Debug, PartialEq)]
pub struct Batch {
    #[doc = "entries"]
    pub entries: Vec<Entry>,
    #[doc = "label"]
    pub label: Option<String>,
}
impl __wire::Codec for Batch {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            let __field0 = __read6(r, le)?;
            let __field1 = __read8(r, le)?;
            let value = Self {
                entries: __field0,
                label: __field1,
            };
            Ok(value)
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let value = &self.entries;
            __write6(w, value, le)?;
            let value = &self.label;
            __write8(w, value, le)?;
            Ok(())
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let __field0 = __sample6(s)?;
            let __field1 = __sample8(s)?;
            let value = Self {
                entries: __field0,
                label: __field1,
            };
            Ok(value)
        })
    }
}
impl fictionet::stdlib::codec::Wire for Batch {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    /// Refuses flags other than 0 or 1.
    /// Refuses invalid UTF-8.
    /// Refuses undeclared set bits.
    /// Refuses unknown enum values.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    /// Refuses undeclared set bits.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[doc = "A type whose source name matches the imported trait."]
#[derive(Clone, Debug, PartialEq)]
pub struct Wire {
    #[doc = "gen"]
    pub gen_: u8,
}
impl __wire::Codec for Wire {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            let __field0 = __read9(r, le)?;
            let value = Self { gen_: __field0 };
            Ok(value)
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let value = &self.gen_;
            __write9(w, value, le)?;
            Ok(())
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let __field0 = __sample9(s)?;
            let value = Self { gen_: __field0 };
            Ok(value)
        })
    }
}
impl fictionet::stdlib::codec::Wire for Wire {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[doc = "Wire type TextBatch."]
#[derive(Clone, Debug, PartialEq)]
pub struct TextBatch {
    #[doc = "texts"]
    pub texts: Vec<String>,
}
impl __wire::Codec for TextBatch {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            let __field0 = __read11(r, le)?;
            let value = Self { texts: __field0 };
            Ok(value)
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let value = &self.texts;
            __write11(w, value, le)?;
            Ok(())
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let __field0 = __sample11(s)?;
            let value = Self { texts: __field0 };
            Ok(value)
        })
    }
}
impl fictionet::stdlib::codec::Wire for TextBatch {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    /// Refuses invalid UTF-8.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[cfg(test)]
mod generated_tests {
    use super::*;

    #[test]
    fn generated_contracts() -> Result<(), Error> {
        {
            use super::Status as Value;
            __wire::check::<Value>()?;
        }
        {
            use super::Flags as Value;
            __wire::check::<Value>()?;
        }
        {
            use super::Entry as Value;
            __wire::check::<Value>()?;
        }
        {
            use super::Batch as Value;
            __wire::check::<Value>()?;
        }
        {
            use super::Wire as Value;
            __wire::check::<Value>()?;
        }
        {
            use super::TextBatch as Value;
            __wire::check::<Value>()?;
        }
        Ok(())
    }
}
