// Generated by fictionet-codegen 0.1.0 from the ir schema.
// Schema: "one_field.json"
// Regenerate with: fictionet-codegen ir "one_field.json" -o <this file>

#![doc = "Wire types generated by fictionet-codegen."]

/// Maximum encoded bytes in one value.
pub const MAX_MESSAGE: usize = 1048576;
/// Default limit used for omitted collection lengths.
pub const MAX_COLLECTION: usize = 4096;
/// Maximum nested value operations, including named types and groups.
pub const MAX_DEPTH: usize = 32;
/// Maximum requested heap bytes for a decoded value.
pub const MAX_ALLOCATION: usize = 8388608;
/// Maximum visited structural nodes in one value.
pub const MAX_NODES: usize = 65536;

fictionet::stdlib::codec::generated_runtime!(
    Error,
    __wire,
    MAX_MESSAGE,
    MAX_DEPTH,
    MAX_ALLOCATION,
    MAX_NODES
);

type __Value0 = u8;
#[inline]
fn __read0(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value0, Error> {
    r.scalar::<u8>(le)
}
#[inline]
fn __write0(w: &mut __wire::Writer, v: &__Value0, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample0(s: &mut __wire::Sampler) -> Result<__Value0, Error> {
    Ok(s.number() as u8)
}

#[doc = "Wire type Point."]
#[derive(Clone, Debug, PartialEq)]
pub struct Point {
    #[doc = "x"]
    pub x: u8,
}
impl __wire::Codec for Point {
    fn read(r: &mut __wire::Reader<'_>, _le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            let __field0 = __read0(r, false)?;
            let value = Self { x: __field0 };
            Ok(value)
        })
    }
    fn encode(&self, w: &mut __wire::Writer, _le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let value = &self.x;
            __write0(w, value, false)?;
            Ok(())
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let __field0 = __sample0(s)?;
            let value = Self { x: __field0 };
            Ok(value)
        })
    }
}
impl fictionet::stdlib::codec::Wire for Point {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[cfg(test)]
mod generated_tests {
    use super::*;

    #[test]
    fn generated_contracts() -> Result<(), Error> {
        {
            use super::Point as Value;
            __wire::check::<Value>()?;
        }
        Ok(())
    }
}
