// Generated by fictionet-codegen 0.1.0 from the ir schema.
// Schema: "primitives.json"
// Regenerate with: fictionet-codegen ir "primitives.json" -o <this file>

#![doc = "Every scalar width, null sentinels, and data forms."]

/// Maximum encoded bytes in one value.
pub const MAX_MESSAGE: usize = 1048576;
/// Default limit used for omitted collection lengths.
pub const MAX_COLLECTION: usize = 4096;
/// Maximum nested value operations, including named types and groups.
pub const MAX_DEPTH: usize = 32;
/// Maximum requested heap bytes for a decoded value.
pub const MAX_ALLOCATION: usize = 8388608;
/// Maximum visited structural nodes in one value.
pub const MAX_NODES: usize = 65536;

fictionet::stdlib::codec::generated_runtime!(
    Error,
    __wire,
    MAX_MESSAGE,
    MAX_DEPTH,
    MAX_ALLOCATION,
    MAX_NODES
);

type __Value0 = u8;
#[inline]
fn __read0(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value0, Error> {
    r.scalar::<u8>(le)
}
#[inline]
fn __write0(w: &mut __wire::Writer, v: &__Value0, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample0(s: &mut __wire::Sampler) -> Result<__Value0, Error> {
    Ok(s.number() as u8)
}

type __Value1 = u16;
#[inline]
fn __read1(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value1, Error> {
    r.scalar::<u16>(le)
}
#[inline]
fn __write1(w: &mut __wire::Writer, v: &__Value1, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample1(s: &mut __wire::Sampler) -> Result<__Value1, Error> {
    Ok(s.number() as u16)
}

type __Value2 = u32;
#[inline]
fn __read2(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value2, Error> {
    r.scalar::<u32>(le)
}
#[inline]
fn __write2(w: &mut __wire::Writer, v: &__Value2, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample2(s: &mut __wire::Sampler) -> Result<__Value2, Error> {
    Ok(s.number() as u32)
}

type __Value3 = u64;
#[inline]
fn __read3(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value3, Error> {
    r.scalar::<u64>(le)
}
#[inline]
fn __write3(w: &mut __wire::Writer, v: &__Value3, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample3(s: &mut __wire::Sampler) -> Result<__Value3, Error> {
    Ok(s.number())
}

type __Value4 = i8;
#[inline]
fn __read4(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value4, Error> {
    r.scalar::<i8>(le)
}
#[inline]
fn __write4(w: &mut __wire::Writer, v: &__Value4, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample4(s: &mut __wire::Sampler) -> Result<__Value4, Error> {
    Ok(s.number() as i8)
}

type __Value5 = i16;
#[inline]
fn __read5(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value5, Error> {
    r.scalar::<i16>(le)
}
#[inline]
fn __write5(w: &mut __wire::Writer, v: &__Value5, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample5(s: &mut __wire::Sampler) -> Result<__Value5, Error> {
    Ok(s.number() as i16)
}

type __Value6 = i32;
#[inline]
fn __read6(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value6, Error> {
    r.scalar::<i32>(le)
}
#[inline]
fn __write6(w: &mut __wire::Writer, v: &__Value6, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample6(s: &mut __wire::Sampler) -> Result<__Value6, Error> {
    Ok(s.number() as i32)
}

type __Value7 = i64;
#[inline]
fn __read7(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value7, Error> {
    r.scalar::<i64>(le)
}
#[inline]
fn __write7(w: &mut __wire::Writer, v: &__Value7, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample7(s: &mut __wire::Sampler) -> Result<__Value7, Error> {
    Ok(s.number() as i64)
}

type __Value8 = f32;
#[inline]
fn __read8(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value8, Error> {
    r.scalar::<f32>(le)
}
#[inline]
fn __write8(w: &mut __wire::Writer, v: &__Value8, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample8(s: &mut __wire::Sampler) -> Result<__Value8, Error> {
    Ok((s.number() as i32 % 1000) as f32)
}

type __Value9 = f64;
#[inline]
fn __read9(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value9, Error> {
    r.scalar::<f64>(le)
}
#[inline]
fn __write9(w: &mut __wire::Writer, v: &__Value9, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample9(s: &mut __wire::Sampler) -> Result<__Value9, Error> {
    Ok((s.number() as i32 % 1000) as f64)
}

type __Value10 = Option<u8>;
#[inline]
fn __read10(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value10, Error> {
    r.nullable(255u8, le)
}
#[inline]
fn __write10(w: &mut __wire::Writer, v: &__Value10, le: bool) -> Result<(), Error> {
    w.nullable(v, 255u8, le)
}
#[cfg(test)]
fn __sample10(s: &mut __wire::Sampler) -> Result<__Value10, Error> {
    let value = s.number() as u8;
    s.nullable(value, 255u8)
}

type __Value11 = Option<u16>;
#[inline]
fn __read11(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value11, Error> {
    r.nullable(65535u16, le)
}
#[inline]
fn __write11(w: &mut __wire::Writer, v: &__Value11, le: bool) -> Result<(), Error> {
    w.nullable(v, 65535u16, le)
}
#[cfg(test)]
fn __sample11(s: &mut __wire::Sampler) -> Result<__Value11, Error> {
    let value = s.number() as u16;
    s.nullable(value, 65535u16)
}

type __Value12 = Option<u32>;
#[inline]
fn __read12(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value12, Error> {
    r.nullable(4294967295u32, le)
}
#[inline]
fn __write12(w: &mut __wire::Writer, v: &__Value12, le: bool) -> Result<(), Error> {
    w.nullable(v, 4294967295u32, le)
}
#[cfg(test)]
fn __sample12(s: &mut __wire::Sampler) -> Result<__Value12, Error> {
    let value = s.number() as u32;
    s.nullable(value, 4294967295u32)
}

type __Value13 = Option<u64>;
#[inline]
fn __read13(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value13, Error> {
    r.nullable(18446744073709551615u64, le)
}
#[inline]
fn __write13(w: &mut __wire::Writer, v: &__Value13, le: bool) -> Result<(), Error> {
    w.nullable(v, 18446744073709551615u64, le)
}
#[cfg(test)]
fn __sample13(s: &mut __wire::Sampler) -> Result<__Value13, Error> {
    let value = s.number();
    s.nullable(value, 18446744073709551615u64)
}

type __Value14 = Option<i8>;
#[inline]
fn __read14(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value14, Error> {
    r.nullable(-128i8, le)
}
#[inline]
fn __write14(w: &mut __wire::Writer, v: &__Value14, le: bool) -> Result<(), Error> {
    w.nullable(v, -128i8, le)
}
#[cfg(test)]
fn __sample14(s: &mut __wire::Sampler) -> Result<__Value14, Error> {
    let value = s.number() as i8;
    s.nullable(value, -128i8)
}

type __Value15 = Option<i16>;
#[inline]
fn __read15(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value15, Error> {
    r.nullable(-32768i16, le)
}
#[inline]
fn __write15(w: &mut __wire::Writer, v: &__Value15, le: bool) -> Result<(), Error> {
    w.nullable(v, -32768i16, le)
}
#[cfg(test)]
fn __sample15(s: &mut __wire::Sampler) -> Result<__Value15, Error> {
    let value = s.number() as i16;
    s.nullable(value, -32768i16)
}

type __Value16 = Option<i32>;
#[inline]
fn __read16(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value16, Error> {
    r.nullable(-2147483648i32, le)
}
#[inline]
fn __write16(w: &mut __wire::Writer, v: &__Value16, le: bool) -> Result<(), Error> {
    w.nullable(v, -2147483648i32, le)
}
#[cfg(test)]
fn __sample16(s: &mut __wire::Sampler) -> Result<__Value16, Error> {
    let value = s.number() as i32;
    s.nullable(value, -2147483648i32)
}

type __Value17 = Option<i64>;
#[inline]
fn __read17(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value17, Error> {
    r.nullable(-9223372036854775808i64, le)
}
#[inline]
fn __write17(w: &mut __wire::Writer, v: &__Value17, le: bool) -> Result<(), Error> {
    w.nullable(v, -9223372036854775808i64, le)
}
#[cfg(test)]
fn __sample17(s: &mut __wire::Sampler) -> Result<__Value17, Error> {
    let value = s.number() as i64;
    s.nullable(value, -9223372036854775808i64)
}

type __Value18 = Option<f32>;
#[inline]
fn __read18(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value18, Error> {
    r.nullable(-999.0f32, le)
}
#[inline]
fn __write18(w: &mut __wire::Writer, v: &__Value18, le: bool) -> Result<(), Error> {
    w.nullable(v, -999.0f32, le)
}
#[cfg(test)]
fn __sample18(s: &mut __wire::Sampler) -> Result<__Value18, Error> {
    let value = (s.number() as i32 % 1000) as f32;
    s.nullable(value, -999.0f32)
}

type __Value19 = Option<f64>;
#[inline]
fn __read19(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value19, Error> {
    r.nullable(-999.0f64, le)
}
#[inline]
fn __write19(w: &mut __wire::Writer, v: &__Value19, le: bool) -> Result<(), Error> {
    w.nullable(v, -999.0f64, le)
}
#[cfg(test)]
fn __sample19(s: &mut __wire::Sampler) -> Result<__Value19, Error> {
    let value = (s.number() as i32 % 1000) as f64;
    s.nullable(value, -999.0f64)
}

const __LIMIT20: usize = 4;
type __Value20 = Vec<u8>;
#[inline]
fn __read20(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value20, Error> {
    r.bytes(0, __LIMIT20, le)
}
#[inline]
fn __write20(w: &mut __wire::Writer, v: &__Value20, le: bool) -> Result<(), Error> {
    w.bytes(v, 0, __LIMIT20, le)
}
#[cfg(test)]
fn __sample20(s: &mut __wire::Sampler) -> Result<__Value20, Error> {
    s.bytes(0, __LIMIT20)
}

const __LIMIT21: usize = 3;
type __Value21 = String;
#[inline]
fn __read21(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value21, Error> {
    r.text(0, __LIMIT21, le)
}
#[inline]
fn __write21(w: &mut __wire::Writer, v: &__Value21, le: bool) -> Result<(), Error> {
    w.bytes(v.as_bytes(), 0, __LIMIT21, le)
}
#[cfg(test)]
fn __sample21(s: &mut __wire::Sampler) -> Result<__Value21, Error> {
    s.text(0, __LIMIT21)
}

const __LIMIT22: usize = 32;
type __Value22 = Vec<u8>;
#[inline]
fn __read22(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value22, Error> {
    r.bytes(2, __LIMIT22, le)
}
#[inline]
fn __write22(w: &mut __wire::Writer, v: &__Value22, le: bool) -> Result<(), Error> {
    w.bytes(v, 2, __LIMIT22, le)
}
#[cfg(test)]
fn __sample22(s: &mut __wire::Sampler) -> Result<__Value22, Error> {
    s.bytes(2, __LIMIT22)
}

const __LIMIT23: usize = 24;
type __Value23 = String;
#[inline]
fn __read23(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value23, Error> {
    r.text(1, __LIMIT23, le)
}
#[inline]
fn __write23(w: &mut __wire::Writer, v: &__Value23, le: bool) -> Result<(), Error> {
    w.bytes(v.as_bytes(), 1, __LIMIT23, le)
}
#[cfg(test)]
fn __sample23(s: &mut __wire::Sampler) -> Result<__Value23, Error> {
    s.text(1, __LIMIT23)
}

type __Value24 = Option<__Value2>;
#[inline]
fn __read24(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value24, Error> {
    r.optional(1, le, |r| __read2(r, le))
}
#[inline]
fn __write24(w: &mut __wire::Writer, v: &__Value24, le: bool) -> Result<(), Error> {
    w.optional(v, 1, le, |w, v| __write2(w, v, le))
}
#[cfg(test)]
fn __sample24(s: &mut __wire::Sampler) -> Result<__Value24, Error> {
    s.optional(__sample2)
}

#[doc = "Wire type primitive message."]
#[derive(Clone, Debug, PartialEq)]
pub struct PrimitiveMessage {
    #[doc = "value_u8"]
    pub value_u8: u8,
    #[doc = "value_u16"]
    pub value_u16: u16,
    #[doc = "value_u32"]
    pub value_u32: u32,
    #[doc = "value_u64"]
    pub value_u64: u64,
    #[doc = "value_i8"]
    pub value_i8: i8,
    #[doc = "value_i16"]
    pub value_i16: i16,
    #[doc = "value_i32"]
    pub value_i32: i32,
    #[doc = "value_i64"]
    pub value_i64: i64,
    #[doc = "value_f32"]
    pub value_f32: f32,
    #[doc = "value_f64"]
    pub value_f64: f64,
    #[doc = "null_u8"]
    pub null_u8: Option<u8>,
    #[doc = "null_u16"]
    pub null_u16: Option<u16>,
    #[doc = "null_u32"]
    pub null_u32: Option<u32>,
    #[doc = "null_u64"]
    pub null_u64: Option<u64>,
    #[doc = "null_i8"]
    pub null_i8: Option<i8>,
    #[doc = "null_i16"]
    pub null_i16: Option<i16>,
    #[doc = "null_i32"]
    pub null_i32: Option<i32>,
    #[doc = "null_i64"]
    pub null_i64: Option<i64>,
    #[doc = "null_f32"]
    pub null_f32: Option<f32>,
    #[doc = "null_f64"]
    pub null_f64: Option<f64>,
    #[doc = "type"]
    pub type_: Vec<u8>,
    #[doc = "fixed-text"]
    pub fixed_text: String,
    #[doc = "data"]
    pub data: Vec<u8>,
    #[doc = "text"]
    pub text: String,
    #[doc = "maybe"]
    pub maybe: Option<u32>,
}
impl __wire::Codec for PrimitiveMessage {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            let __field0 = __read0(r, le)?;
            let __field1 = __read1(r, le)?;
            let __field2 = __read2(r, false)?;
            let __field3 = __read3(r, le)?;
            let __field4 = __read4(r, le)?;
            let __field5 = __read5(r, le)?;
            let __field6 = __read6(r, le)?;
            let __field7 = __read7(r, le)?;
            let __field8 = __read8(r, le)?;
            let __field9 = __read9(r, le)?;
            let __field10 = __read10(r, le)?;
            let __field11 = __read11(r, le)?;
            let __field12 = __read12(r, le)?;
            let __field13 = __read13(r, le)?;
            let __field14 = __read14(r, le)?;
            let __field15 = __read15(r, le)?;
            let __field16 = __read16(r, le)?;
            let __field17 = __read17(r, le)?;
            let __field18 = __read18(r, le)?;
            let __field19 = __read19(r, le)?;
            let __field20 = __read20(r, le)?;
            let __field21 = __read21(r, le)?;
            let __field22 = __read22(r, le)?;
            let __field23 = __read23(r, le)?;
            let __field24 = __read24(r, le)?;
            let value = Self {
                value_u8: __field0,
                value_u16: __field1,
                value_u32: __field2,
                value_u64: __field3,
                value_i8: __field4,
                value_i16: __field5,
                value_i32: __field6,
                value_i64: __field7,
                value_f32: __field8,
                value_f64: __field9,
                null_u8: __field10,
                null_u16: __field11,
                null_u32: __field12,
                null_u64: __field13,
                null_i8: __field14,
                null_i16: __field15,
                null_i32: __field16,
                null_i64: __field17,
                null_f32: __field18,
                null_f64: __field19,
                type_: __field20,
                fixed_text: __field21,
                data: __field22,
                text: __field23,
                maybe: __field24,
            };
            Ok(value)
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let value = &self.value_u8;
            __write0(w, value, le)?;
            let value = &self.value_u16;
            __write1(w, value, le)?;
            let value = &self.value_u32;
            __write2(w, value, false)?;
            let value = &self.value_u64;
            __write3(w, value, le)?;
            let value = &self.value_i8;
            __write4(w, value, le)?;
            let value = &self.value_i16;
            __write5(w, value, le)?;
            let value = &self.value_i32;
            __write6(w, value, le)?;
            let value = &self.value_i64;
            __write7(w, value, le)?;
            let value = &self.value_f32;
            __write8(w, value, le)?;
            let value = &self.value_f64;
            __write9(w, value, le)?;
            let value = &self.null_u8;
            __write10(w, value, le)?;
            let value = &self.null_u16;
            __write11(w, value, le)?;
            let value = &self.null_u32;
            __write12(w, value, le)?;
            let value = &self.null_u64;
            __write13(w, value, le)?;
            let value = &self.null_i8;
            __write14(w, value, le)?;
            let value = &self.null_i16;
            __write15(w, value, le)?;
            let value = &self.null_i32;
            __write16(w, value, le)?;
            let value = &self.null_i64;
            __write17(w, value, le)?;
            let value = &self.null_f32;
            __write18(w, value, le)?;
            let value = &self.null_f64;
            __write19(w, value, le)?;
            let value = &self.type_;
            __write20(w, value, le)?;
            let value = &self.fixed_text;
            __write21(w, value, le)?;
            let value = &self.data;
            __write22(w, value, le)?;
            let value = &self.text;
            __write23(w, value, le)?;
            let value = &self.maybe;
            __write24(w, value, le)?;
            Ok(())
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let __field0 = __sample0(s)?;
            let __field1 = __sample1(s)?;
            let __field2 = __sample2(s)?;
            let __field3 = __sample3(s)?;
            let __field4 = __sample4(s)?;
            let __field5 = __sample5(s)?;
            let __field6 = __sample6(s)?;
            let __field7 = __sample7(s)?;
            let __field8 = __sample8(s)?;
            let __field9 = __sample9(s)?;
            let __field10 = __sample10(s)?;
            let __field11 = __sample11(s)?;
            let __field12 = __sample12(s)?;
            let __field13 = __sample13(s)?;
            let __field14 = __sample14(s)?;
            let __field15 = __sample15(s)?;
            let __field16 = __sample16(s)?;
            let __field17 = __sample17(s)?;
            let __field18 = __sample18(s)?;
            let __field19 = __sample19(s)?;
            let __field20 = __sample20(s)?;
            let __field21 = __sample21(s)?;
            let __field22 = __sample22(s)?;
            let __field23 = __sample23(s)?;
            let __field24 = __sample24(s)?;
            let value = Self {
                value_u8: __field0,
                value_u16: __field1,
                value_u32: __field2,
                value_u64: __field3,
                value_i8: __field4,
                value_i16: __field5,
                value_i32: __field6,
                value_i64: __field7,
                value_f32: __field8,
                value_f64: __field9,
                null_u8: __field10,
                null_u16: __field11,
                null_u32: __field12,
                null_u64: __field13,
                null_i8: __field14,
                null_i16: __field15,
                null_i32: __field16,
                null_i64: __field17,
                null_f32: __field18,
                null_f64: __field19,
                type_: __field20,
                fixed_text: __field21,
                data: __field22,
                text: __field23,
                maybe: __field24,
            };
            Ok(value)
        })
    }
}
impl fictionet::stdlib::codec::Wire for PrimitiveMessage {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    /// Refuses flags other than 0 or 1.
    /// Refuses invalid UTF-8.
    /// Refuses non-finite floats.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, true)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    /// Refuses non-finite floats.
    /// Refuses reserved nulls in Some.
    /// Refuses wrong fixed data lengths.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, true)
    }
}

#[cfg(test)]
mod generated_tests {
    use super::*;

    #[test]
    fn generated_contracts() -> Result<(), Error> {
        {
            use super::PrimitiveMessage as Value;
            __wire::check::<Value>()?;
        }
        Ok(())
    }
}
