// Generated by fictionet-codegen 0.1.0.
// You own this file. You may copy and edit it. Regenerate only by choice.
// Input: "primitives.json"

// Schema: "Every scalar width, null sentinels, and data forms."

/// Maximum encoded bytes in one value.
pub const MAX_MESSAGE: usize = 1048576;
/// Default limit used for omitted collection lengths.
pub const MAX_COLLECTION: usize = 4096;
/// Maximum nested value operations, including named types and groups.
pub const MAX_DEPTH: usize = 32;
/// Maximum requested heap bytes for a decoded value.
pub const MAX_ALLOCATION: usize = 8388608;
/// Maximum visited structural nodes in one value.
pub const MAX_NODES: usize = 65536;

/// Why a wire value was refused.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Error {
    /// Input ended within a value.
    Truncated,
    /// Input contains bytes after the value.
    Trailing,
    /// A byte, item, allocation, or work limit was exceeded.
    Limit,
    /// The value exceeds the nesting limit.
    Depth,
    /// A scalar, flag, enum, set, or null encoding is invalid.
    Value,
    /// Text is not UTF-8.
    Utf8,
    /// A stream header does not match its declared magic.
    Header,
    /// Memory reservation failed.
    Allocation,
}
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{self:?}")
    }
}
impl std::error::Error for Error {}

// This support code belongs to this file. It has no SDK-private dependencies.
#[allow(dead_code)]
mod __wire {
    use super::{Error, MAX_ALLOCATION, MAX_DEPTH, MAX_MESSAGE, MAX_NODES};

    // The IR allows at most 256 magic bytes and an eight-byte prefix.
    const MAX_HEADER: usize = 264;

    pub trait Codec: Sized {
        fn read(r: &mut Reader<'_>, le: bool) -> Result<Self, Error>;
        fn encode(&self, w: &mut Writer, le: bool) -> Result<(), Error>;
        #[cfg(test)]
        fn sample(s: &mut Sampler) -> Result<Self, Error>;
    }
    pub trait Scalar: Copy + PartialEq {
        fn read(r: &mut Reader<'_>, le: bool) -> Result<Self, Error>;
        fn encode(self, w: &mut Writer, le: bool) -> Result<(), Error>;
        fn same(self, other: Self) -> bool;
    }
    macro_rules! scalar {
        ($t:ty, $valid:expr, $same:expr) => {
            impl Scalar for $t {
                fn read(r: &mut Reader<'_>, le: bool) -> Result<Self, Error> {
                    let b = r.take(std::mem::size_of::<Self>())?;
                    let a = b.try_into().map_err(|_| Error::Truncated)?;
                    let v = if le {
                        Self::from_le_bytes(a)
                    } else {
                        Self::from_be_bytes(a)
                    };
                    if !($valid)(v) {
                        return Err(Error::Value);
                    }
                    Ok(v)
                }
                fn encode(self, w: &mut Writer, le: bool) -> Result<(), Error> {
                    if !($valid)(self) {
                        return Err(Error::Value);
                    }
                    w.put(&if le {
                        self.to_le_bytes()
                    } else {
                        self.to_be_bytes()
                    })
                }
                fn same(self, other: Self) -> bool {
                    ($same)(self, other)
                }
            }
        };
    }
    scalar!(u8, |_: u8| true, |a: u8, b: u8| a == b);
    scalar!(u16, |_: u16| true, |a: u16, b: u16| a == b);
    scalar!(u32, |_: u32| true, |a: u32, b: u32| a == b);
    scalar!(u64, |_: u64| true, |a: u64, b: u64| a == b);
    scalar!(i8, |_: i8| true, |a: i8, b: i8| a == b);
    scalar!(i16, |_: i16| true, |a: i16, b: i16| a == b);
    scalar!(i32, |_: i32| true, |a: i32, b: i32| a == b);
    scalar!(i64, |_: i64| true, |a: i64, b: i64| a == b);
    scalar!(f32, f32::is_finite, |a: f32, b: f32| a.to_bits()
        == b.to_bits());
    scalar!(f64, f64::is_finite, |a: f64, b: f64| a.to_bits()
        == b.to_bits());

    #[derive(Default)]
    struct Budget {
        depth: usize,
        nodes: usize,
        allocated: usize,
    }
    impl Budget {
        fn enter(&mut self) -> Result<(), Error> {
            if self.depth >= MAX_DEPTH {
                return Err(Error::Depth);
            }
            if self.nodes >= MAX_NODES {
                return Err(Error::Limit);
            }
            self.depth += 1;
            self.nodes += 1;
            Ok(())
        }
        fn charge(&mut self, bytes: usize) -> Result<(), Error> {
            self.allocated = self.allocated.checked_add(bytes).ok_or(Error::Limit)?;
            if self.allocated > MAX_ALLOCATION {
                return Err(Error::Limit);
            }
            Ok(())
        }
    }
    pub struct Reader<'a> {
        bytes: &'a [u8],
        pos: usize,
        budget: Budget,
    }
    impl<'a> Reader<'a> {
        pub fn new(bytes: &'a [u8]) -> Self {
            Self {
                bytes,
                pos: 0,
                budget: Budget::default(),
            }
        }
        pub fn nested<T>(
            &mut self,
            f: impl FnOnce(&mut Self) -> Result<T, Error>,
        ) -> Result<T, Error> {
            self.budget.enter()?;
            let result = f(self);
            self.budget.depth -= 1;
            result
        }
        pub fn take(&mut self, n: usize) -> Result<&'a [u8], Error> {
            let end = self.pos.checked_add(n).ok_or(Error::Limit)?;
            let bytes = self.bytes.get(self.pos..end).ok_or(Error::Truncated)?;
            self.pos = end;
            Ok(bytes)
        }
        pub fn scalar<T: Scalar>(&mut self, le: bool) -> Result<T, Error> {
            T::read(self, le)
        }
        pub fn count(&mut self, width: usize, le: bool, limit: usize) -> Result<usize, Error> {
            let n = match width {
                1 => u64::from(self.scalar::<u8>(le)?),
                2 => u64::from(self.scalar::<u16>(le)?),
                4 => u64::from(self.scalar::<u32>(le)?),
                8 => self.scalar::<u64>(le)?,
                _ => return Err(Error::Value),
            };
            let n = usize::try_from(n).map_err(|_| Error::Limit)?;
            if n > limit {
                return Err(Error::Limit);
            }
            Ok(n)
        }
        pub fn bytes(&mut self, width: usize, size: usize, le: bool) -> Result<Vec<u8>, Error> {
            let n = if width == 0 {
                size
            } else {
                self.count(width, le, size)?
            };
            let b = self.take(n)?;
            self.budget.charge(n)?;
            let mut v = Vec::new();
            v.try_reserve_exact(n).map_err(|_| Error::Allocation)?;
            v.extend_from_slice(b);
            Ok(v)
        }
        pub fn text(&mut self, width: usize, size: usize, le: bool) -> Result<String, Error> {
            String::from_utf8(self.bytes(width, size, le)?).map_err(|_| Error::Utf8)
        }
        pub fn reference<T: Codec>(&mut self, le: bool) -> Result<Box<T>, Error> {
            self.budget.charge(std::mem::size_of::<T>())?;
            Ok(Box::new(T::read(self, le)?))
        }
        pub fn group<T>(
            &mut self,
            width: usize,
            limit: usize,
            minimum: usize,
            le: bool,
            mut f: impl FnMut(&mut Self) -> Result<T, Error>,
        ) -> Result<Vec<T>, Error> {
            let n = self.count(width, le, limit)?;
            let remaining = self.bytes.len().saturating_sub(self.pos);
            if minimum != 0 && n > remaining / minimum {
                return Err(Error::Truncated);
            }
            let bytes = n
                .checked_mul(std::mem::size_of::<T>())
                .ok_or(Error::Limit)?;
            self.budget.charge(bytes)?;
            if n > MAX_NODES.saturating_sub(self.budget.nodes) {
                return Err(Error::Limit);
            }
            let mut v = Vec::new();
            v.try_reserve_exact(n).map_err(|_| Error::Allocation)?;
            for _ in 0..n {
                v.push(self.nested(&mut f)?);
            }
            Ok(v)
        }
        pub fn optional<T>(
            &mut self,
            width: usize,
            le: bool,
            f: impl FnOnce(&mut Self) -> Result<T, Error>,
        ) -> Result<Option<T>, Error> {
            let flag = match width {
                1 => u64::from(self.scalar::<u8>(le)?),
                2 => u64::from(self.scalar::<u16>(le)?),
                4 => u64::from(self.scalar::<u32>(le)?),
                8 => self.scalar::<u64>(le)?,
                _ => return Err(Error::Value),
            };
            match flag {
                0 => Ok(None),
                1 => self.nested(f).map(Some),
                _ => Err(Error::Value),
            }
        }
        pub fn nullable<T: Scalar>(&mut self, null: T, le: bool) -> Result<Option<T>, Error> {
            let v = self.scalar::<T>(le)?;
            Ok(if v.same(null) { None } else { Some(v) })
        }
    }
    pub struct Writer {
        bytes: Vec<u8>,
        budget: Budget,
    }
    impl Writer {
        pub fn nested(
            &mut self,
            f: impl FnOnce(&mut Self) -> Result<(), Error>,
        ) -> Result<(), Error> {
            self.budget.enter()?;
            let result = f(self);
            self.budget.depth -= 1;
            result
        }
        pub fn put(&mut self, b: &[u8]) -> Result<(), Error> {
            let end = self.bytes.len().checked_add(b.len()).ok_or(Error::Limit)?;
            if end > MAX_MESSAGE {
                return Err(Error::Limit);
            }
            self.bytes
                .try_reserve(b.len())
                .map_err(|_| Error::Allocation)?;
            self.bytes.extend_from_slice(b);
            Ok(())
        }
        pub fn scalar<T: Scalar>(&mut self, value: T, le: bool) -> Result<(), Error> {
            value.encode(self, le)
        }
        pub fn count(&mut self, n: usize, width: usize, le: bool) -> Result<(), Error> {
            match width {
                1 => self.scalar(u8::try_from(n).map_err(|_| Error::Limit)?, le),
                2 => self.scalar(u16::try_from(n).map_err(|_| Error::Limit)?, le),
                4 => self.scalar(u32::try_from(n).map_err(|_| Error::Limit)?, le),
                8 => self.scalar(u64::try_from(n).map_err(|_| Error::Limit)?, le),
                _ => Err(Error::Value),
            }
        }
        pub fn bytes(
            &mut self,
            b: &[u8],
            width: usize,
            size: usize,
            le: bool,
        ) -> Result<(), Error> {
            if (width == 0 && b.len() != size) || b.len() > size {
                return Err(Error::Limit);
            }
            self.budget.charge(b.len())?;
            if width != 0 {
                self.count(b.len(), width, le)?;
            }
            self.put(b)
        }
        pub fn reference<T: Codec>(&mut self, value: &T, le: bool) -> Result<(), Error> {
            self.budget.charge(std::mem::size_of::<T>())?;
            value.encode(self, le)
        }
        pub fn group<T>(
            &mut self,
            values: &[T],
            width: usize,
            limit: usize,
            le: bool,
            mut f: impl FnMut(&mut Self, &T) -> Result<(), Error>,
        ) -> Result<(), Error> {
            if values.len() > limit || values.len() > MAX_NODES.saturating_sub(self.budget.nodes) {
                return Err(Error::Limit);
            }
            let bytes = values
                .len()
                .checked_mul(std::mem::size_of::<T>())
                .ok_or(Error::Limit)?;
            self.budget.charge(bytes)?;
            self.count(values.len(), width, le)?;
            for v in values {
                self.nested(|w| f(w, v))?;
            }
            Ok(())
        }
        pub fn optional<T>(
            &mut self,
            value: &Option<T>,
            width: usize,
            le: bool,
            f: impl FnOnce(&mut Self, &T) -> Result<(), Error>,
        ) -> Result<(), Error> {
            self.count(usize::from(value.is_some()), width, le)?;
            match value {
                Some(v) => self.nested(|w| f(w, v)),
                None => Ok(()),
            }
        }
        pub fn nullable<T: Scalar>(
            &mut self,
            value: &Option<T>,
            null: T,
            le: bool,
        ) -> Result<(), Error> {
            match value {
                Some(v) if v.same(null) => Err(Error::Value),
                Some(v) => self.scalar(*v, le),
                None => self.scalar(null, le),
            }
        }
    }
    #[cfg(test)]
    pub struct Sampler {
        pub rng: fictionet::stdlib::codec::Lcg,
        budget: Budget,
        minimal: bool,
    }
    #[cfg(test)]
    impl Sampler {
        pub fn number(&mut self) -> u64 {
            (self.rng.next() << 33) | (self.rng.next() << 2) | self.rng.below(4)
        }
        pub fn seed(seed: u64) -> Self {
            Self {
                rng: fictionet::stdlib::codec::Lcg::new(seed),
                budget: Budget::default(),
                minimal: seed == 0,
            }
        }
        pub fn nested<T>(
            &mut self,
            f: impl FnOnce(&mut Self) -> Result<T, Error>,
        ) -> Result<T, Error> {
            self.budget.enter()?;
            let result = f(self);
            self.budget.depth -= 1;
            result
        }
        pub fn bytes(&mut self, width: usize, size: usize) -> Result<Vec<u8>, Error> {
            let n = if width == 0 {
                size
            } else if self.minimal {
                0
            } else {
                self.rng.index(size.min(8).saturating_add(1))
            };
            self.budget.charge(n)?;
            let mut bytes = Vec::new();
            bytes.try_reserve_exact(n).map_err(|_| Error::Allocation)?;
            bytes.resize(n, 0);
            self.rng.fill(&mut bytes);
            Ok(bytes)
        }
        pub fn text(&mut self, width: usize, size: usize) -> Result<String, Error> {
            let mut bytes = self.bytes(width, size)?;
            for b in &mut bytes {
                *b = b'a' + *b % 26;
            }
            String::from_utf8(bytes).map_err(|_| Error::Utf8)
        }
        pub fn reference<T: Codec>(&mut self) -> Result<Box<T>, Error> {
            self.budget.charge(std::mem::size_of::<T>())?;
            Ok(Box::new(T::sample(self)?))
        }
        pub fn group<T>(
            &mut self,
            limit: usize,
            mut f: impl FnMut(&mut Self) -> Result<T, Error>,
        ) -> Result<Vec<T>, Error> {
            let n = if !self.minimal && self.budget.depth < 4 {
                self.rng.index(limit.min(2).saturating_add(1))
            } else {
                0
            };
            self.budget.charge(
                n.checked_mul(std::mem::size_of::<T>())
                    .ok_or(Error::Limit)?,
            )?;
            let mut values = Vec::new();
            values.try_reserve_exact(n).map_err(|_| Error::Allocation)?;
            for _ in 0..n {
                values.push(self.nested(&mut f)?);
            }
            Ok(values)
        }
        pub fn optional<T>(
            &mut self,
            f: impl FnOnce(&mut Self) -> Result<T, Error>,
        ) -> Result<Option<T>, Error> {
            if !self.minimal && self.budget.depth < 4 && self.rng.coin() {
                self.nested(f).map(Some)
            } else {
                Ok(None)
            }
        }
        pub fn nullable<T: Scalar>(&mut self, value: T, null: T) -> Result<Option<T>, Error> {
            Ok(if value.same(null) || self.rng.coin() {
                None
            } else {
                Some(value)
            })
        }
    }
    #[cfg(test)]
    pub fn check<T>() -> Result<(), Error>
    where
        T: Codec
            + fictionet::stdlib::codec::Wire<ParseError = Error, WriteError = Error>
            + std::fmt::Debug
            + PartialEq,
    {
        use fictionet::stdlib::codec::contract;
        let mut successes = 0;
        for seed in 0..32 {
            let mut s = Sampler::seed(seed);
            if let Ok(value) = T::sample(&mut s) {
                contract::check_wire_value(&value);
                if let Ok(bytes) = value.to_bytes() {
                    assert_eq!(T::parse(&bytes)?, value);
                    successes += 1;
                }
            }
        }
        assert!(
            successes > 0,
            "no writable sample for {}",
            std::any::type_name::<T>()
        );
        Ok(())
    }
    #[cfg(test)]
    pub fn check_stream<T, D>(
        make: impl Fn() -> D,
        write: fn(&T, &mut Vec<u8>) -> Result<(), Error>,
        header: usize,
    ) where
        T: Codec + std::fmt::Debug + PartialEq,
        D: fictionet::stdlib::codec::Decode<Item = T, Error = Error>,
    {
        use fictionet::stdlib::codec::contract;
        let mut successes = 0;
        for seed in 0..32 {
            let mut s = Sampler::seed(seed);
            if let Ok(value) = T::sample(&mut s) {
                let mut bytes = Vec::new();
                if write(&value, &mut bytes).is_ok() {
                    contract::check_decode_with_alloc_limit(
                        &make,
                        &bytes,
                        2 * (MAX_MESSAGE + header),
                    );
                    successes += 1;
                }
            }
        }
        assert!(
            successes > 0,
            "no writable frame for {}",
            std::any::type_name::<D>()
        );
    }
    pub fn parse<T: Codec>(bytes: &[u8], le: bool) -> Result<T, Error> {
        if bytes.len() > MAX_MESSAGE {
            return Err(Error::Limit);
        }
        let mut r = Reader::new(bytes);
        let value = T::read(&mut r, le)?;
        if r.pos != bytes.len() {
            return Err(Error::Trailing);
        }
        Ok(value)
    }
    pub fn write<T: Codec>(value: &T, out: &mut Vec<u8>, le: bool) -> Result<(), Error> {
        let mut w = Writer {
            bytes: Vec::new(),
            budget: Budget::default(),
        };
        value.encode(&mut w, le)?;
        out.len().checked_add(w.bytes.len()).ok_or(Error::Limit)?;
        out.try_reserve(w.bytes.len())
            .map_err(|_| Error::Allocation)?;
        out.extend_from_slice(&w.bytes);
        Ok(())
    }
    pub fn frame<T: Codec>(
        input: &[u8],
        magic: &[u8],
        width: usize,
        prefix_le: bool,
        body_le: bool,
    ) -> Result<fictionet::stdlib::codec::Step<T>, Error> {
        use fictionet::stdlib::codec::Step;
        let header = magic.len().checked_add(width).ok_or(Error::Limit)?;
        let Some(prefix) = input.get(..header) else {
            return Ok(Step::Need);
        };
        if prefix.get(..magic.len()) != Some(magic) {
            return Err(Error::Header);
        }
        let mut r = Reader::new(prefix.get(magic.len()..).ok_or(Error::Truncated)?);
        let n = r.count(width, prefix_le, MAX_MESSAGE)?;
        let end = header.checked_add(n).ok_or(Error::Limit)?;
        let Some(body) = input.get(header..end) else {
            return Ok(Step::Need);
        };
        Ok(Step::Item(parse(body, body_le)?, end))
    }
    pub fn write_frame<T: Codec>(
        value: &T,
        out: &mut Vec<u8>,
        magic: &[u8],
        width: usize,
        prefix_le: bool,
        body_le: bool,
    ) -> Result<(), Error> {
        let mut body = Vec::new();
        write(value, &mut body, body_le)?;
        let mut header = Writer {
            bytes: Vec::new(),
            budget: Budget::default(),
        };
        // Header storage is at most 264 bytes, independent of the body limit.
        header
            .bytes
            .try_reserve_exact(MAX_HEADER)
            .map_err(|_| Error::Allocation)?;
        header.bytes.extend_from_slice(magic);
        let n = u64::try_from(body.len()).map_err(|_| Error::Limit)?;
        let bytes = if prefix_le {
            n.to_le_bytes()
        } else {
            n.to_be_bytes()
        };
        if width < 8 && n >= (1u64 << (width * 8)) {
            return Err(Error::Limit);
        }
        let prefix = if prefix_le {
            bytes.get(..width)
        } else {
            bytes.get(8usize.checked_sub(width).ok_or(Error::Limit)?..)
        }
        .ok_or(Error::Limit)?;
        header.bytes.extend_from_slice(prefix);
        let total = header
            .bytes
            .len()
            .checked_add(body.len())
            .ok_or(Error::Limit)?;
        out.len().checked_add(total).ok_or(Error::Limit)?;
        out.try_reserve(total).map_err(|_| Error::Allocation)?;
        out.extend_from_slice(&header.bytes);
        out.extend_from_slice(&body);
        Ok(())
    }
}

type __Value0 = u8;
fn __read0(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value0, Error> {
    r.scalar::<u8>(le)
}
fn __write0(w: &mut __wire::Writer, v: &__Value0, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample0(s: &mut __wire::Sampler) -> Result<__Value0, Error> {
    Ok(s.number() as u8)
}

type __Value1 = u16;
fn __read1(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value1, Error> {
    r.scalar::<u16>(le)
}
fn __write1(w: &mut __wire::Writer, v: &__Value1, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample1(s: &mut __wire::Sampler) -> Result<__Value1, Error> {
    Ok(s.number() as u16)
}

type __Value2 = u32;
fn __read2(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value2, Error> {
    r.scalar::<u32>(le)
}
fn __write2(w: &mut __wire::Writer, v: &__Value2, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample2(s: &mut __wire::Sampler) -> Result<__Value2, Error> {
    Ok(s.number() as u32)
}

type __Value3 = u64;
fn __read3(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value3, Error> {
    r.scalar::<u64>(le)
}
fn __write3(w: &mut __wire::Writer, v: &__Value3, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample3(s: &mut __wire::Sampler) -> Result<__Value3, Error> {
    Ok(s.number())
}

type __Value4 = i8;
fn __read4(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value4, Error> {
    r.scalar::<i8>(le)
}
fn __write4(w: &mut __wire::Writer, v: &__Value4, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample4(s: &mut __wire::Sampler) -> Result<__Value4, Error> {
    Ok(s.number() as i8)
}

type __Value5 = i16;
fn __read5(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value5, Error> {
    r.scalar::<i16>(le)
}
fn __write5(w: &mut __wire::Writer, v: &__Value5, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample5(s: &mut __wire::Sampler) -> Result<__Value5, Error> {
    Ok(s.number() as i16)
}

type __Value6 = i32;
fn __read6(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value6, Error> {
    r.scalar::<i32>(le)
}
fn __write6(w: &mut __wire::Writer, v: &__Value6, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample6(s: &mut __wire::Sampler) -> Result<__Value6, Error> {
    Ok(s.number() as i32)
}

type __Value7 = i64;
fn __read7(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value7, Error> {
    r.scalar::<i64>(le)
}
fn __write7(w: &mut __wire::Writer, v: &__Value7, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample7(s: &mut __wire::Sampler) -> Result<__Value7, Error> {
    Ok(s.number() as i64)
}

type __Value8 = f32;
fn __read8(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value8, Error> {
    r.scalar::<f32>(le)
}
fn __write8(w: &mut __wire::Writer, v: &__Value8, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample8(s: &mut __wire::Sampler) -> Result<__Value8, Error> {
    Ok((s.number() as i32 % 1000) as f32)
}

type __Value9 = f64;
fn __read9(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value9, Error> {
    r.scalar::<f64>(le)
}
fn __write9(w: &mut __wire::Writer, v: &__Value9, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample9(s: &mut __wire::Sampler) -> Result<__Value9, Error> {
    Ok((s.number() as i32 % 1000) as f64)
}

type __Value10 = Option<u8>;
fn __read10(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value10, Error> {
    r.nullable(255u8, le)
}
fn __write10(w: &mut __wire::Writer, v: &__Value10, le: bool) -> Result<(), Error> {
    w.nullable(v, 255u8, le)
}
#[cfg(test)]
fn __sample10(s: &mut __wire::Sampler) -> Result<__Value10, Error> {
    let value = s.number() as u8;
    s.nullable(value, 255u8)
}

type __Value11 = Option<u16>;
fn __read11(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value11, Error> {
    r.nullable(65535u16, le)
}
fn __write11(w: &mut __wire::Writer, v: &__Value11, le: bool) -> Result<(), Error> {
    w.nullable(v, 65535u16, le)
}
#[cfg(test)]
fn __sample11(s: &mut __wire::Sampler) -> Result<__Value11, Error> {
    let value = s.number() as u16;
    s.nullable(value, 65535u16)
}

type __Value12 = Option<u32>;
fn __read12(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value12, Error> {
    r.nullable(4294967295u32, le)
}
fn __write12(w: &mut __wire::Writer, v: &__Value12, le: bool) -> Result<(), Error> {
    w.nullable(v, 4294967295u32, le)
}
#[cfg(test)]
fn __sample12(s: &mut __wire::Sampler) -> Result<__Value12, Error> {
    let value = s.number() as u32;
    s.nullable(value, 4294967295u32)
}

type __Value13 = Option<u64>;
fn __read13(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value13, Error> {
    r.nullable(18446744073709551615u64, le)
}
fn __write13(w: &mut __wire::Writer, v: &__Value13, le: bool) -> Result<(), Error> {
    w.nullable(v, 18446744073709551615u64, le)
}
#[cfg(test)]
fn __sample13(s: &mut __wire::Sampler) -> Result<__Value13, Error> {
    let value = s.number();
    s.nullable(value, 18446744073709551615u64)
}

type __Value14 = Option<i8>;
fn __read14(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value14, Error> {
    r.nullable(-128i8, le)
}
fn __write14(w: &mut __wire::Writer, v: &__Value14, le: bool) -> Result<(), Error> {
    w.nullable(v, -128i8, le)
}
#[cfg(test)]
fn __sample14(s: &mut __wire::Sampler) -> Result<__Value14, Error> {
    let value = s.number() as i8;
    s.nullable(value, -128i8)
}

type __Value15 = Option<i16>;
fn __read15(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value15, Error> {
    r.nullable(-32768i16, le)
}
fn __write15(w: &mut __wire::Writer, v: &__Value15, le: bool) -> Result<(), Error> {
    w.nullable(v, -32768i16, le)
}
#[cfg(test)]
fn __sample15(s: &mut __wire::Sampler) -> Result<__Value15, Error> {
    let value = s.number() as i16;
    s.nullable(value, -32768i16)
}

type __Value16 = Option<i32>;
fn __read16(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value16, Error> {
    r.nullable(-2147483648i32, le)
}
fn __write16(w: &mut __wire::Writer, v: &__Value16, le: bool) -> Result<(), Error> {
    w.nullable(v, -2147483648i32, le)
}
#[cfg(test)]
fn __sample16(s: &mut __wire::Sampler) -> Result<__Value16, Error> {
    let value = s.number() as i32;
    s.nullable(value, -2147483648i32)
}

type __Value17 = Option<i64>;
fn __read17(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value17, Error> {
    r.nullable(-9223372036854775808i64, le)
}
fn __write17(w: &mut __wire::Writer, v: &__Value17, le: bool) -> Result<(), Error> {
    w.nullable(v, -9223372036854775808i64, le)
}
#[cfg(test)]
fn __sample17(s: &mut __wire::Sampler) -> Result<__Value17, Error> {
    let value = s.number() as i64;
    s.nullable(value, -9223372036854775808i64)
}

type __Value18 = Option<f32>;
fn __read18(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value18, Error> {
    r.nullable(-999.0f32, le)
}
fn __write18(w: &mut __wire::Writer, v: &__Value18, le: bool) -> Result<(), Error> {
    w.nullable(v, -999.0f32, le)
}
#[cfg(test)]
fn __sample18(s: &mut __wire::Sampler) -> Result<__Value18, Error> {
    let value = (s.number() as i32 % 1000) as f32;
    s.nullable(value, -999.0f32)
}

type __Value19 = Option<f64>;
fn __read19(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value19, Error> {
    r.nullable(-999.0f64, le)
}
fn __write19(w: &mut __wire::Writer, v: &__Value19, le: bool) -> Result<(), Error> {
    w.nullable(v, -999.0f64, le)
}
#[cfg(test)]
fn __sample19(s: &mut __wire::Sampler) -> Result<__Value19, Error> {
    let value = (s.number() as i32 % 1000) as f64;
    s.nullable(value, -999.0f64)
}

const __LIMIT20: usize = 4;
type __Value20 = Vec<u8>;
fn __read20(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value20, Error> {
    r.bytes(0, __LIMIT20, le)
}
fn __write20(w: &mut __wire::Writer, v: &__Value20, le: bool) -> Result<(), Error> {
    w.bytes(v, 0, __LIMIT20, le)
}
#[cfg(test)]
fn __sample20(s: &mut __wire::Sampler) -> Result<__Value20, Error> {
    s.bytes(0, __LIMIT20)
}

const __LIMIT21: usize = 3;
type __Value21 = String;
fn __read21(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value21, Error> {
    r.text(0, __LIMIT21, le)
}
fn __write21(w: &mut __wire::Writer, v: &__Value21, le: bool) -> Result<(), Error> {
    w.bytes(v.as_bytes(), 0, __LIMIT21, le)
}
#[cfg(test)]
fn __sample21(s: &mut __wire::Sampler) -> Result<__Value21, Error> {
    s.text(0, __LIMIT21)
}

const __LIMIT22: usize = 32;
type __Value22 = Vec<u8>;
fn __read22(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value22, Error> {
    r.bytes(2, __LIMIT22, le)
}
fn __write22(w: &mut __wire::Writer, v: &__Value22, le: bool) -> Result<(), Error> {
    w.bytes(v, 2, __LIMIT22, le)
}
#[cfg(test)]
fn __sample22(s: &mut __wire::Sampler) -> Result<__Value22, Error> {
    s.bytes(2, __LIMIT22)
}

const __LIMIT23: usize = 24;
type __Value23 = String;
fn __read23(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value23, Error> {
    r.text(1, __LIMIT23, le)
}
fn __write23(w: &mut __wire::Writer, v: &__Value23, le: bool) -> Result<(), Error> {
    w.bytes(v.as_bytes(), 1, __LIMIT23, le)
}
#[cfg(test)]
fn __sample23(s: &mut __wire::Sampler) -> Result<__Value23, Error> {
    s.text(1, __LIMIT23)
}

type __Value24 = u32;
fn __read24(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value24, Error> {
    r.scalar::<u32>(le)
}
fn __write24(w: &mut __wire::Writer, v: &__Value24, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample24(s: &mut __wire::Sampler) -> Result<__Value24, Error> {
    Ok(s.number() as u32)
}

type __Value25 = Option<__Value24>;
fn __read25(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value25, Error> {
    r.optional(1, le, |r| __read24(r, le))
}
fn __write25(w: &mut __wire::Writer, v: &__Value25, le: bool) -> Result<(), Error> {
    w.optional(v, 1, le, |w, v| __write24(w, v, le))
}
#[cfg(test)]
fn __sample25(s: &mut __wire::Sampler) -> Result<__Value25, Error> {
    s.optional(__sample24)
}

#[doc = "Wire type primitive message."]
#[derive(Clone, Debug, PartialEq)]
pub struct PrimitiveMessage {
    #[doc = "value_u8"]
    pub value_u8: u8,
    #[doc = "value_u16"]
    pub value_u16: u16,
    #[doc = "value_u32"]
    pub value_u32: u32,
    #[doc = "value_u64"]
    pub value_u64: u64,
    #[doc = "value_i8"]
    pub value_i8: i8,
    #[doc = "value_i16"]
    pub value_i16: i16,
    #[doc = "value_i32"]
    pub value_i32: i32,
    #[doc = "value_i64"]
    pub value_i64: i64,
    #[doc = "value_f32"]
    pub value_f32: f32,
    #[doc = "value_f64"]
    pub value_f64: f64,
    #[doc = "null_u8"]
    pub null_u8: Option<u8>,
    #[doc = "null_u16"]
    pub null_u16: Option<u16>,
    #[doc = "null_u32"]
    pub null_u32: Option<u32>,
    #[doc = "null_u64"]
    pub null_u64: Option<u64>,
    #[doc = "null_i8"]
    pub null_i8: Option<i8>,
    #[doc = "null_i16"]
    pub null_i16: Option<i16>,
    #[doc = "null_i32"]
    pub null_i32: Option<i32>,
    #[doc = "null_i64"]
    pub null_i64: Option<i64>,
    #[doc = "null_f32"]
    pub null_f32: Option<f32>,
    #[doc = "null_f64"]
    pub null_f64: Option<f64>,
    #[doc = "type"]
    pub type_: Vec<u8>,
    #[doc = "fixed-text"]
    pub fixed_text: String,
    #[doc = "data"]
    pub data: Vec<u8>,
    #[doc = "text"]
    pub text: String,
    #[doc = "maybe"]
    pub maybe: Option<u32>,
}
impl __wire::Codec for PrimitiveMessage {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            let __field0 = __read0(r, le)?;
            let __field1 = __read1(r, le)?;
            let __field2 = __read2(r, false)?;
            let __field3 = __read3(r, le)?;
            let __field4 = __read4(r, le)?;
            let __field5 = __read5(r, le)?;
            let __field6 = __read6(r, le)?;
            let __field7 = __read7(r, le)?;
            let __field8 = __read8(r, le)?;
            let __field9 = __read9(r, le)?;
            let __field10 = __read10(r, le)?;
            let __field11 = __read11(r, le)?;
            let __field12 = __read12(r, le)?;
            let __field13 = __read13(r, le)?;
            let __field14 = __read14(r, le)?;
            let __field15 = __read15(r, le)?;
            let __field16 = __read16(r, le)?;
            let __field17 = __read17(r, le)?;
            let __field18 = __read18(r, le)?;
            let __field19 = __read19(r, le)?;
            let __field20 = __read20(r, le)?;
            let __field21 = __read21(r, le)?;
            let __field22 = __read22(r, le)?;
            let __field23 = __read23(r, le)?;
            let __field25 = __read25(r, le)?;
            let value = Self {
                value_u8: __field0,
                value_u16: __field1,
                value_u32: __field2,
                value_u64: __field3,
                value_i8: __field4,
                value_i16: __field5,
                value_i32: __field6,
                value_i64: __field7,
                value_f32: __field8,
                value_f64: __field9,
                null_u8: __field10,
                null_u16: __field11,
                null_u32: __field12,
                null_u64: __field13,
                null_i8: __field14,
                null_i16: __field15,
                null_i32: __field16,
                null_i64: __field17,
                null_f32: __field18,
                null_f64: __field19,
                type_: __field20,
                fixed_text: __field21,
                data: __field22,
                text: __field23,
                maybe: __field25,
            };
            Ok(value)
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let value = &self.value_u8;
            __write0(w, value, le)?;
            let value = &self.value_u16;
            __write1(w, value, le)?;
            let value = &self.value_u32;
            __write2(w, value, false)?;
            let value = &self.value_u64;
            __write3(w, value, le)?;
            let value = &self.value_i8;
            __write4(w, value, le)?;
            let value = &self.value_i16;
            __write5(w, value, le)?;
            let value = &self.value_i32;
            __write6(w, value, le)?;
            let value = &self.value_i64;
            __write7(w, value, le)?;
            let value = &self.value_f32;
            __write8(w, value, le)?;
            let value = &self.value_f64;
            __write9(w, value, le)?;
            let value = &self.null_u8;
            __write10(w, value, le)?;
            let value = &self.null_u16;
            __write11(w, value, le)?;
            let value = &self.null_u32;
            __write12(w, value, le)?;
            let value = &self.null_u64;
            __write13(w, value, le)?;
            let value = &self.null_i8;
            __write14(w, value, le)?;
            let value = &self.null_i16;
            __write15(w, value, le)?;
            let value = &self.null_i32;
            __write16(w, value, le)?;
            let value = &self.null_i64;
            __write17(w, value, le)?;
            let value = &self.null_f32;
            __write18(w, value, le)?;
            let value = &self.null_f64;
            __write19(w, value, le)?;
            let value = &self.type_;
            __write20(w, value, le)?;
            let value = &self.fixed_text;
            __write21(w, value, le)?;
            let value = &self.data;
            __write22(w, value, le)?;
            let value = &self.text;
            __write23(w, value, le)?;
            let value = &self.maybe;
            __write25(w, value, le)?;
            Ok(())
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let __field0 = __sample0(s)?;
            let __field1 = __sample1(s)?;
            let __field2 = __sample2(s)?;
            let __field3 = __sample3(s)?;
            let __field4 = __sample4(s)?;
            let __field5 = __sample5(s)?;
            let __field6 = __sample6(s)?;
            let __field7 = __sample7(s)?;
            let __field8 = __sample8(s)?;
            let __field9 = __sample9(s)?;
            let __field10 = __sample10(s)?;
            let __field11 = __sample11(s)?;
            let __field12 = __sample12(s)?;
            let __field13 = __sample13(s)?;
            let __field14 = __sample14(s)?;
            let __field15 = __sample15(s)?;
            let __field16 = __sample16(s)?;
            let __field17 = __sample17(s)?;
            let __field18 = __sample18(s)?;
            let __field19 = __sample19(s)?;
            let __field20 = __sample20(s)?;
            let __field21 = __sample21(s)?;
            let __field22 = __sample22(s)?;
            let __field23 = __sample23(s)?;
            let __field25 = __sample25(s)?;
            let value = Self {
                value_u8: __field0,
                value_u16: __field1,
                value_u32: __field2,
                value_u64: __field3,
                value_i8: __field4,
                value_i16: __field5,
                value_i32: __field6,
                value_i64: __field7,
                value_f32: __field8,
                value_f64: __field9,
                null_u8: __field10,
                null_u16: __field11,
                null_u32: __field12,
                null_u64: __field13,
                null_i8: __field14,
                null_i16: __field15,
                null_i32: __field16,
                null_i64: __field17,
                null_f32: __field18,
                null_f64: __field19,
                type_: __field20,
                fixed_text: __field21,
                data: __field22,
                text: __field23,
                maybe: __field25,
            };
            Ok(value)
        })
    }
}
impl fictionet::stdlib::codec::Wire for PrimitiveMessage {
    type ParseError = Error;
    type WriteError = Error;

    /// Reads one exact value. Refuses truncation and trailing bytes.
    /// Refuses values above the declared resource limits.
    /// Refuses flags other than 0 or 1.
    /// Refuses invalid UTF-8.
    /// Refuses non-finite floats.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, true)
    }

    /// Appends one value. Errors leave out unchanged.
    /// Refuses values above the declared resource limits.
    /// Refuses non-finite floats.
    /// Refuses reserved nulls in Some.
    /// Refuses wrong fixed data lengths.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, true)
    }
}

#[cfg(test)]
mod generated_tests {
    use super::*;

    #[test]
    fn generated_contracts() -> Result<(), Error> {
        {
            use super::PrimitiveMessage as Value;
            __wire::check::<Value>()?;
        }
        Ok(())
    }
}
