// Generated by fictionet-codegen 0.1.0 from the sbe schema.
// Schema: "sbe_sample.xml"
// Regenerate with: fictionet-codegen sbe "sbe_sample.xml" -o <this file>

#![doc = "SBE schema sample id 9 version 4. Front end sample"]

/// Maximum encoded bytes in one value.
pub const MAX_MESSAGE: usize = 1048576;
/// Default limit used for omitted collection lengths.
pub const MAX_COLLECTION: usize = 4096;
/// Maximum nested value operations, including named types and groups.
pub const MAX_DEPTH: usize = 32;
/// Maximum requested heap bytes for a decoded value.
pub const MAX_ALLOCATION: usize = 8388608;
/// Maximum visited structural nodes in one value.
pub const MAX_NODES: usize = 65536;

fictionet::stdlib::codec::generated_runtime!(
    Error,
    __wire,
    MAX_MESSAGE,
    MAX_DEPTH,
    MAX_ALLOCATION,
    MAX_NODES
);

const __MIN0: i64 = -9223372036854775807i64;
const __MAX0: i64 = 9223372036854775807i64;
type __Value0 = i64;
#[inline]
fn __read0(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value0, Error> {
    r.ranged(__MIN0, __MAX0, le)
}
#[inline]
fn __write0(w: &mut __wire::Writer, v: &__Value0, le: bool) -> Result<(), Error> {
    w.ranged(*v, __MIN0, __MAX0, le)
}
#[cfg(test)]
fn __sample0(s: &mut __wire::Sampler) -> Result<__Value0, Error> {
    Ok(s.ranged(-9223372036854775807, 9223372036854775807) as i64)
}

type __Value1 = Price;
#[inline]
fn __read1(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value1, Error> {
    <__Value1 as __wire::Codec>::read(r, le)
}
#[inline]
fn __write1(w: &mut __wire::Writer, v: &__Value1, le: bool) -> Result<(), Error> {
    __wire::Codec::encode(v, w, le)
}
#[cfg(test)]
fn __sample1(s: &mut __wire::Sampler) -> Result<__Value1, Error> {
    <__Value1 as __wire::Codec>::sample(s)
}

type __Value2 = Side;
#[inline]
fn __read2(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value2, Error> {
    <__Value2 as __wire::Codec>::read(r, le)
}
#[inline]
fn __write2(w: &mut __wire::Writer, v: &__Value2, le: bool) -> Result<(), Error> {
    __wire::Codec::encode(v, w, le)
}
#[cfg(test)]
fn __sample2(s: &mut __wire::Sampler) -> Result<__Value2, Error> {
    <__Value2 as __wire::Codec>::sample(s)
}

type __Value3 = QuoteKind;
#[inline]
fn __read3(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value3, Error> {
    <__Value3 as __wire::Codec>::read(r, le)
}
#[inline]
fn __write3(w: &mut __wire::Writer, v: &__Value3, le: bool) -> Result<(), Error> {
    __wire::Codec::encode(v, w, le)
}
#[cfg(test)]
fn __sample3(s: &mut __wire::Sampler) -> Result<__Value3, Error> {
    <__Value3 as __wire::Codec>::sample(s)
}

const __MIN4: u64 = 0u64;
const __MAX4: u64 = 18446744073709551614u64;
type __Value4 = u64;
#[inline]
fn __read4(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value4, Error> {
    r.ranged(__MIN4, __MAX4, le)
}
#[inline]
fn __write4(w: &mut __wire::Writer, v: &__Value4, le: bool) -> Result<(), Error> {
    w.ranged(*v, __MIN4, __MAX4, le)
}
#[cfg(test)]
fn __sample4(s: &mut __wire::Sampler) -> Result<__Value4, Error> {
    Ok(s.ranged(0, 18446744073709551614) as u64)
}

const __LIMIT5: usize = 6;
type __Value5 = Vec<u8>;
#[inline]
fn __read5(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value5, Error> {
    r.bytes(0, __LIMIT5, le)
}
#[inline]
fn __write5(w: &mut __wire::Writer, v: &__Value5, le: bool) -> Result<(), Error> {
    w.bytes(v, 0, __LIMIT5, le)
}
#[cfg(test)]
fn __sample5(s: &mut __wire::Sampler) -> Result<__Value5, Error> {
    s.bytes(0, __LIMIT5)
}

type __Value6 = Quote;
#[inline]
fn __read6(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value6, Error> {
    <__Value6 as __wire::Codec>::read(r, le)
}
#[inline]
fn __write6(w: &mut __wire::Writer, v: &__Value6, le: bool) -> Result<(), Error> {
    __wire::Codec::encode(v, w, le)
}
#[cfg(test)]
fn __sample6(s: &mut __wire::Sampler) -> Result<__Value6, Error> {
    <__Value6 as __wire::Codec>::sample(s)
}

const __MIN7: i32 = 0i32;
const __MAX7: i32 = 1000000i32;
type __Value7 = i32;
#[inline]
fn __read7(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value7, Error> {
    r.ranged(__MIN7, __MAX7, le)
}
#[inline]
fn __write7(w: &mut __wire::Writer, v: &__Value7, le: bool) -> Result<(), Error> {
    w.ranged(*v, __MIN7, __MAX7, le)
}
#[cfg(test)]
fn __sample7(s: &mut __wire::Sampler) -> Result<__Value7, Error> {
    Ok(s.ranged(0, 1000000) as i32)
}

const __MIN8: u32 = 1u32;
const __MAX8: u32 = 4294967294u32;
const __NULL8: u32 = 0u32;
type __Value8 = Option<u32>;
#[inline]
fn __read8(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value8, Error> {
    r.nullable_range(__NULL8, __MIN8, __MAX8, le)
}
#[inline]
fn __write8(w: &mut __wire::Writer, v: &__Value8, le: bool) -> Result<(), Error> {
    w.nullable_range(v, __NULL8, __MIN8, __MAX8, le)
}
#[cfg(test)]
fn __sample8(s: &mut __wire::Sampler) -> Result<__Value8, Error> {
    let value = s.ranged(1, 4294967294) as u32;
    s.nullable(value, __NULL8)
}

type __Item9 = Status;
type __Value9 = Option<__Item9>;
#[inline]
fn __read9(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value9, Error> {
    r.nullable_ref(255u8, le, |r| <__Item9 as __wire::Codec>::read(r, le))
}
#[inline]
fn __write9(w: &mut __wire::Writer, v: &__Value9, le: bool) -> Result<(), Error> {
    w.nullable_ref(v, 255u8, le, |w, v| __wire::Codec::encode(v, w, le))
}
#[cfg(test)]
fn __sample9(s: &mut __wire::Sampler) -> Result<__Value9, Error> {
    s.maybe(<__Item9 as __wire::Codec>::sample)
}

type __Value10 = Flags;
#[inline]
fn __read10(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value10, Error> {
    <__Value10 as __wire::Codec>::read(r, le)
}
#[inline]
fn __write10(w: &mut __wire::Writer, v: &__Value10, le: bool) -> Result<(), Error> {
    __wire::Codec::encode(v, w, le)
}
#[cfg(test)]
fn __sample10(s: &mut __wire::Sampler) -> Result<__Value10, Error> {
    <__Value10 as __wire::Codec>::sample(s)
}

const __MIN11: u8 = 32u8;
const __MAX11: u8 = 126u8;
type __Value11 = u8;
#[inline]
fn __read11(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value11, Error> {
    r.ranged(__MIN11, __MAX11, le)
}
#[inline]
fn __write11(w: &mut __wire::Writer, v: &__Value11, le: bool) -> Result<(), Error> {
    w.ranged(*v, __MIN11, __MAX11, le)
}
#[cfg(test)]
fn __sample11(s: &mut __wire::Sampler) -> Result<__Value11, Error> {
    Ok(s.ranged(32, 126) as u8)
}

const __MIN12: u16 = 0u16;
const __MAX12: u16 = 65534u16;
const __NULL12: u16 = 65535u16;
type __Value12 = Option<u16>;
#[inline]
fn __read12(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value12, Error> {
    r.nullable_range(__NULL12, __MIN12, __MAX12, le)
}
#[inline]
fn __write12(w: &mut __wire::Writer, v: &__Value12, le: bool) -> Result<(), Error> {
    w.nullable_range(v, __NULL12, __MIN12, __MAX12, le)
}
#[cfg(test)]
fn __sample12(s: &mut __wire::Sampler) -> Result<__Value12, Error> {
    let value = s.ranged(0, 65534) as u16;
    s.nullable(value, __NULL12)
}

const __MIN13: i8 = -127i8;
const __MAX13: i8 = 127i8;
const __NULL13: i8 = -128i8;
type __Value13 = Option<i8>;
#[inline]
fn __read13(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value13, Error> {
    r.nullable_range(__NULL13, __MIN13, __MAX13, le)
}
#[inline]
fn __write13(w: &mut __wire::Writer, v: &__Value13, le: bool) -> Result<(), Error> {
    w.nullable_range(v, __NULL13, __MIN13, __MAX13, le)
}
#[cfg(test)]
fn __sample13(s: &mut __wire::Sampler) -> Result<__Value13, Error> {
    let value = s.ranged(-127, 127) as i8;
    s.nullable(value, __NULL13)
}

const __LIMIT14: usize = 255;
type __Entry14 = OrderFills;
type __Value14 = Vec<__Entry14>;
#[inline]
fn __read14(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value14, Error> {
    let header = r.take(4)?;
    let length = __wire::field(header, 0, 2, le, 65534)?;
    let length = usize::try_from(length).map_err(|_| Error::Limit)?;
    let count = __wire::field(header, 3, 1, le, 255)?;
    let count = usize::try_from(count).map_err(|_| Error::Limit)?;
    if count > __LIMIT14 {
        return Err(Error::Limit);
    }
    if length < 12 {
        return Err(Error::Layout);
    }
    let minimum = length.saturating_add(5);
    r.entries(count, minimum, |r| __Entry14::__read_block(r, le, length))
}
#[inline]
fn __write14(w: &mut __wire::Writer, v: &__Value14, le: bool) -> Result<(), Error> {
    let count = u64::try_from(v.len()).map_err(|_| Error::Limit)?;
    let mut header = [0u8; 4];
    __wire::put_field(&mut header, 0, 2, le, 12)?;
    __wire::put_field(&mut header, 3, 1, le, count)?;
    w.put(&header)?;
    w.entries(v, __LIMIT14, |w, v| v.__write_block(w, le))
}
#[cfg(test)]
fn __sample14(s: &mut __wire::Sampler) -> Result<__Value14, Error> {
    s.group(__LIMIT14, <__Entry14 as __wire::Codec>::sample)
}

const __LIMIT15: usize = 20;
type __Value15 = Vec<u8>;
#[inline]
fn __read15(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value15, Error> {
    r.bytes(1, __LIMIT15, le)
}
#[inline]
fn __write15(w: &mut __wire::Writer, v: &__Value15, le: bool) -> Result<(), Error> {
    w.bytes(v, 1, __LIMIT15, le)
}
#[cfg(test)]
fn __sample15(s: &mut __wire::Sampler) -> Result<__Value15, Error> {
    s.bytes(1, __LIMIT15)
}

const __LIMIT16: usize = 100;
type __Entry16 = OrderFillsLegs;
type __Value16 = Vec<__Entry16>;
#[inline]
fn __read16(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value16, Error> {
    let header = r.take(4)?;
    let length = __wire::field(header, 0, 2, le, 65534)?;
    let length = usize::try_from(length).map_err(|_| Error::Limit)?;
    let count = __wire::field(header, 2, 2, le, 100)?;
    let count = usize::try_from(count).map_err(|_| Error::Limit)?;
    if count > __LIMIT16 {
        return Err(Error::Limit);
    }
    if length < 2 {
        return Err(Error::Layout);
    }
    let minimum = length.saturating_add(1);
    r.entries(count, minimum, |r| __Entry16::__read_block(r, le, length))
}
#[inline]
fn __write16(w: &mut __wire::Writer, v: &__Value16, le: bool) -> Result<(), Error> {
    let count = u64::try_from(v.len()).map_err(|_| Error::Limit)?;
    let mut header = [0u8; 4];
    __wire::put_field(&mut header, 0, 2, le, 2)?;
    __wire::put_field(&mut header, 2, 2, le, count)?;
    w.put(&header)?;
    w.entries(v, __LIMIT16, |w, v| v.__write_block(w, le))
}
#[cfg(test)]
fn __sample16(s: &mut __wire::Sampler) -> Result<__Value16, Error> {
    s.group(__LIMIT16, <__Entry16 as __wire::Codec>::sample)
}

const __MIN17: i16 = -32767i16;
const __MAX17: i16 = 32767i16;
type __Value17 = i16;
#[inline]
fn __read17(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value17, Error> {
    r.ranged(__MIN17, __MAX17, le)
}
#[inline]
fn __write17(w: &mut __wire::Writer, v: &__Value17, le: bool) -> Result<(), Error> {
    w.ranged(*v, __MIN17, __MAX17, le)
}
#[cfg(test)]
fn __sample17(s: &mut __wire::Sampler) -> Result<__Value17, Error> {
    Ok(s.ranged(-32767, 32767) as i16)
}

#[doc = "Wire type Side."]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Side {
    #[doc = "Buy"]
    Buy,
    #[doc = "Sell"]
    Sell,
    /// A value absent from this schema.
    Unknown(u8),
}
impl __wire::Codec for Side {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            let v = r.scalar::<u8>(le)?;
            match v {
                49 => {
                    let value = Self::Buy;
                    Ok(value)
                }
                50 => {
                    let value = Self::Sell;
                    Ok(value)
                }
                raw => Ok(Self::Unknown(raw)),
            }
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let v: u8 = match self {
                Self::Buy => 49,
                Self::Sell => 50,
                Self::Unknown(raw) => *raw,
            };
            w.scalar(v, le)
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let choice = s.rng.below(2);
            match choice {
                0 => {
                    let value = Self::Buy;
                    Ok(value)
                }
                _ => {
                    let value = Self::Sell;
                    Ok(value)
                }
            }
        })
    }
}
impl fictionet::stdlib::codec::Wire for Side {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[doc = "Wire type Status."]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Status {
    #[doc = "Open"]
    Open,
    #[doc = "Closed"]
    Closed,
    /// A value absent from this schema.
    Unknown(u8),
}
impl __wire::Codec for Status {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            let v = r.scalar::<u8>(le)?;
            match v {
                0 => {
                    let value = Self::Open;
                    Ok(value)
                }
                1 => {
                    let value = Self::Closed;
                    Ok(value)
                }
                raw => Ok(Self::Unknown(raw)),
            }
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let v: u8 = match self {
                Self::Open => 0,
                Self::Closed => 1,
                Self::Unknown(raw) => *raw,
            };
            w.scalar(v, le)
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let choice = s.rng.below(2);
            match choice {
                0 => {
                    let value = Self::Open;
                    Ok(value)
                }
                _ => {
                    let value = Self::Closed;
                    Ok(value)
                }
            }
        })
    }
}
impl fictionet::stdlib::codec::Wire for Status {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[doc = "Wire type Flags."]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Flags(
    /// Declared bits only. Unknown bits are refused by the writer.
    pub u16,
);
impl Flags {
    #[doc = "Ack"]
    pub const ACK: u16 = 1 << 0;
    #[doc = "Last in its event"]
    pub const LAST: u16 = 1 << 9;
}
impl __wire::Codec for Flags {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            let v = r.scalar::<u16>(le)?;
            if v & !513 != 0 {
                return Err(Error::Value);
            }
            Ok(Self(v))
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let v = self.0;
            if v & !513 != 0 {
                return Err(Error::Value);
            }
            w.scalar(v, le)
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let v = s.number() as u16 & 513;
            Ok(Self(v))
        })
    }
}
impl fictionet::stdlib::codec::Wire for Flags {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    /// Refuses undeclared set bits.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    /// Refuses undeclared set bits.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[doc = "A decimal price."]
#[derive(Clone, Debug, PartialEq)]
pub struct Price {
    #[doc = "mantissa"]
    pub mantissa: i64,
}
impl Price {
    #[doc = "exponent"]
    pub const EXPONENT: i8 = -2i8;
}
impl __wire::Codec for Price {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            let __field0 = __read0(r, le)?;
            let value = Self { mantissa: __field0 };
            Ok(value)
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let value = &self.mantissa;
            __write0(w, value, le)?;
            Ok(())
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let __field0 = __sample0(s)?;
            let value = Self { mantissa: __field0 };
            Ok(value)
        })
    }
}
impl fictionet::stdlib::codec::Wire for Price {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    /// Refuses values outside declared ranges.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    /// Refuses values outside declared ranges.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[doc = "Wire type Quote."]
#[derive(Clone, Debug, PartialEq)]
pub struct Quote {
    #[doc = "price"]
    pub price: Price,
    #[doc = "side"]
    pub side: Side,
    #[doc = "Kind"]
    pub kind: QuoteKind,
}
impl __wire::Codec for Quote {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            let __start = r.position();
            let __field0 = __read1(r, le)?;
            r.skip_to(__start, 9)?;
            let __field1 = __read2(r, le)?;
            let __field2 = __read3(r, le)?;
            let value = Self {
                price: __field0,
                side: __field1,
                kind: __field2,
            };
            Ok(value)
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let __start = w.position();
            let value = &self.price;
            __write1(w, value, le)?;
            w.pad_to(__start, 9)?;
            let value = &self.side;
            __write2(w, value, le)?;
            let value = &self.kind;
            __write3(w, value, le)?;
            Ok(())
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let __field0 = __sample1(s)?;
            let __field1 = __sample2(s)?;
            let __field2 = __sample3(s)?;
            let value = Self {
                price: __field0,
                side: __field1,
                kind: __field2,
            };
            Ok(value)
        })
    }
}
impl fictionet::stdlib::codec::Wire for Quote {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    /// Refuses values outside declared ranges.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    /// Refuses values outside declared ranges.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[doc = "Wire type Quote_Kind."]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum QuoteKind {
    #[doc = "Firm"]
    Firm,
    #[doc = "Indicative"]
    Indicative,
    /// A value absent from this schema.
    Unknown(u8),
}
impl __wire::Codec for QuoteKind {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            let v = r.scalar::<u8>(le)?;
            match v {
                1 => {
                    let value = Self::Firm;
                    Ok(value)
                }
                2 => {
                    let value = Self::Indicative;
                    Ok(value)
                }
                raw => Ok(Self::Unknown(raw)),
            }
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let v: u8 = match self {
                Self::Firm => 1,
                Self::Indicative => 2,
                Self::Unknown(raw) => *raw,
            };
            w.scalar(v, le)
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let choice = s.rng.below(2);
            match choice {
                0 => {
                    let value = Self::Firm;
                    Ok(value)
                }
                _ => {
                    let value = Self::Indicative;
                    Ok(value)
                }
            }
        })
    }
}
impl fictionet::stdlib::codec::Wire for QuoteKind {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[doc = "An order."]
#[derive(Clone, Debug, PartialEq)]
pub struct Order {
    #[doc = "id"]
    pub id: u64,
    #[doc = "symbol"]
    pub symbol: Vec<u8>,
    #[doc = "quote"]
    pub quote: Quote,
    #[doc = "qty"]
    pub qty: i32,
    #[doc = "open"]
    pub open: Option<u32>,
    #[doc = "status"]
    pub status: Option<Status>,
    #[doc = "flags"]
    pub flags: Flags,
    #[doc = "flag"]
    pub flag: u8,
    #[doc = "maybe"]
    pub maybe: Option<u16>,
    #[doc = "level"]
    pub level: Option<i8>,
    #[doc = "fills"]
    pub fills: Vec<OrderFills>,
    #[doc = "memo"]
    pub memo: Vec<u8>,
}
impl Order {
    #[doc = "code"]
    pub const CODE: u8 = 88u8;
    #[doc = "venue"]
    pub const VENUE: &[u8] = b"XCME";
    #[doc = "sideConst"]
    pub const SIDE_CONST: Side = Side::Sell;
}
impl __wire::Codec for Order {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        Self::__read_block(r, le, 48)
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        self.__write_block(w, le)
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let __field0 = __sample4(s)?;
            let __field1 = __sample5(s)?;
            let __field2 = __sample6(s)?;
            let __field3 = __sample7(s)?;
            let __field4 = __sample8(s)?;
            let __field7 = __sample9(s)?;
            let __field8 = __sample10(s)?;
            let __field10 = __sample11(s)?;
            let __field11 = __sample12(s)?;
            let __field12 = __sample13(s)?;
            let __field13 = __sample14(s)?;
            let __field14 = __sample15(s)?;
            let value = Self {
                id: __field0,
                symbol: __field1,
                quote: __field2,
                qty: __field3,
                open: __field4,
                status: __field7,
                flags: __field8,
                flag: __field10,
                maybe: __field11,
                level: __field12,
                fills: __field13,
                memo: __field14,
            };
            Ok(value)
        })
    }
}
impl Order {
    fn __read_block(r: &mut __wire::Reader<'_>, le: bool, length: usize) -> Result<Self, Error> {
        r.nested(|r| {
            let __start = r.block(length, 42)?;
            let __field0 = __read4(r, le)?;
            let __field1 = __read5(r, le)?;
            r.skip_to(__start, 16)?;
            let __field2 = __read6(r, le)?;
            let __field3 = __read7(r, le)?;
            let __field4 = __read8(r, le)?;
            let __field7 = __read9(r, le)?;
            let __field8 = __read10(r, le)?;
            let __field10 = __read11(r, le)?;
            let __field11 = __read12(r, le)?;
            let __field12 = __read13(r, le)?;
            r.skip_to(__start, length)?;
            let __field13 = __read14(r, le)?;
            let __field14 = __read15(r, le)?;
            let value = Self {
                id: __field0,
                symbol: __field1,
                quote: __field2,
                qty: __field3,
                open: __field4,
                status: __field7,
                flags: __field8,
                flag: __field10,
                maybe: __field11,
                level: __field12,
                fills: __field13,
                memo: __field14,
            };
            Ok(value)
        })
    }
    fn __write_block(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let __start = w.position();
            let value = &self.id;
            __write4(w, value, le)?;
            let value = &self.symbol;
            __write5(w, value, le)?;
            w.pad_to(__start, 16)?;
            let value = &self.quote;
            __write6(w, value, le)?;
            let value = &self.qty;
            __write7(w, value, le)?;
            let value = &self.open;
            __write8(w, value, le)?;
            let value = &self.status;
            __write9(w, value, le)?;
            let value = &self.flags;
            __write10(w, value, le)?;
            let value = &self.flag;
            __write11(w, value, le)?;
            let value = &self.maybe;
            __write12(w, value, le)?;
            let value = &self.level;
            __write13(w, value, le)?;
            w.pad_to(__start, 48)?;
            let value = &self.fills;
            __write14(w, value, le)?;
            let value = &self.memo;
            __write15(w, value, le)?;
            Ok(())
        })
    }
}
impl fictionet::stdlib::codec::Wire for Order {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    /// Refuses entry counts above their limits.
    /// Refuses mismatched header values.
    /// Refuses undeclared set bits.
    /// Refuses values outside declared ranges.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    /// Refuses entry counts above their limits.
    /// Refuses reserved nulls in Some.
    /// Refuses undeclared set bits.
    /// Refuses values outside declared ranges.
    /// Refuses wrong fixed data lengths.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[doc = "Wire type Order_fills."]
#[derive(Clone, Debug, PartialEq)]
pub struct OrderFills {
    #[doc = "price"]
    pub price: Price,
    #[doc = "qty"]
    pub qty: i32,
    #[doc = "legs"]
    pub legs: Vec<OrderFillsLegs>,
    #[doc = "text"]
    pub text: Vec<u8>,
}
impl __wire::Codec for OrderFills {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        Self::__read_block(r, le, 12)
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        self.__write_block(w, le)
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let __field0 = __sample1(s)?;
            let __field1 = __sample7(s)?;
            let __field2 = __sample16(s)?;
            let __field3 = __sample15(s)?;
            let value = Self {
                price: __field0,
                qty: __field1,
                legs: __field2,
                text: __field3,
            };
            Ok(value)
        })
    }
}
impl OrderFills {
    fn __read_block(r: &mut __wire::Reader<'_>, le: bool, length: usize) -> Result<Self, Error> {
        r.nested(|r| {
            let __start = r.block(length, 12)?;
            let __field0 = __read1(r, le)?;
            let __field1 = __read7(r, le)?;
            r.skip_to(__start, length)?;
            let __field2 = __read16(r, le)?;
            let __field3 = __read15(r, le)?;
            let value = Self {
                price: __field0,
                qty: __field1,
                legs: __field2,
                text: __field3,
            };
            Ok(value)
        })
    }
    fn __write_block(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let __start = w.position();
            let value = &self.price;
            __write1(w, value, le)?;
            let value = &self.qty;
            __write7(w, value, le)?;
            w.pad_to(__start, 12)?;
            let value = &self.legs;
            __write16(w, value, le)?;
            let value = &self.text;
            __write15(w, value, le)?;
            Ok(())
        })
    }
}
impl fictionet::stdlib::codec::Wire for OrderFills {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    /// Refuses entry counts above their limits.
    /// Refuses mismatched header values.
    /// Refuses values outside declared ranges.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    /// Refuses entry counts above their limits.
    /// Refuses values outside declared ranges.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[doc = "Wire type Order_fills_legs."]
#[derive(Clone, Debug, PartialEq)]
pub struct OrderFillsLegs {
    #[doc = "ratio"]
    pub ratio: i16,
    #[doc = "note"]
    pub note: Vec<u8>,
}
impl __wire::Codec for OrderFillsLegs {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        Self::__read_block(r, le, 2)
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        self.__write_block(w, le)
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let __field0 = __sample17(s)?;
            let __field1 = __sample15(s)?;
            let value = Self {
                ratio: __field0,
                note: __field1,
            };
            Ok(value)
        })
    }
}
impl OrderFillsLegs {
    fn __read_block(r: &mut __wire::Reader<'_>, le: bool, length: usize) -> Result<Self, Error> {
        r.nested(|r| {
            let __start = r.block(length, 2)?;
            let __field0 = __read17(r, le)?;
            r.skip_to(__start, length)?;
            let __field1 = __read15(r, le)?;
            let value = Self {
                ratio: __field0,
                note: __field1,
            };
            Ok(value)
        })
    }
    fn __write_block(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let __start = w.position();
            let value = &self.ratio;
            __write17(w, value, le)?;
            w.pad_to(__start, 2)?;
            let value = &self.note;
            __write15(w, value, le)?;
            Ok(())
        })
    }
}
impl fictionet::stdlib::codec::Wire for OrderFillsLegs {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    /// Refuses values outside declared ranges.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    /// Refuses values outside declared ranges.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[doc = "Wire type Ping."]
#[derive(Clone, Debug, PartialEq)]
pub struct Ping {}
impl __wire::Codec for Ping {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        Self::__read_block(r, le, 0)
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        self.__write_block(w, le)
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let _ = s;
            Ok(Self {})
        })
    }
}
impl Ping {
    fn __read_block(r: &mut __wire::Reader<'_>, _le: bool, length: usize) -> Result<Self, Error> {
        r.nested(|r| {
            let __start = r.block(length, 0)?;
            r.skip_to(__start, length)?;
            Ok(Self {})
        })
    }
    fn __write_block(&self, w: &mut __wire::Writer, _le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let __start = w.position();
            w.pad_to(__start, 0)?;
            Ok(())
        })
    }
}
impl fictionet::stdlib::codec::Wire for Ping {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[doc = "One message: the `messageHeader` header, then the template's root block."]
#[derive(Clone, Debug, PartialEq)]
pub enum Message {
    #[doc = "An order."]
    Order(Order),
    #[doc = "Ping"]
    Ping(Ping),
}
type __Case10x0 = Order;
type __Case10x1 = Ping;
impl __wire::Codec for Message {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            let header = r.take(8)?;
            let length = __wire::field(header, 0, 2, le, 65534)?;
            let length = usize::try_from(length).map_err(|_| Error::Limit)?;
            let tag = __wire::field(header, 2, 2, le, 65534)?;
            if __wire::field(header, 4, 2, le, 65534)? != 9 {
                return Err(Error::Header);
            }
            if __wire::field(header, 6, 2, le, 65534)? < 4 {
                return Err(Error::Header);
            }
            match tag {
                1 => {
                    let value = __Case10x0::__read_block(r, le, length)?;
                    Ok(Self::Order(value))
                }
                2 => {
                    let value = __Case10x1::__read_block(r, le, length)?;
                    Ok(Self::Ping(value))
                }
                _ => Err(Error::Header),
            }
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let mut header = [0u8; 8];
            match self {
                Self::Order(value) => {
                    __wire::put_field(&mut header, 0, 2, le, 48)?;
                    __wire::put_field(&mut header, 2, 2, le, 1)?;
                    __wire::put_field(&mut header, 4, 2, le, 9)?;
                    __wire::put_field(&mut header, 6, 2, le, 4)?;
                    w.put(&header)?;
                    value.__write_block(w, le)
                }
                Self::Ping(value) => {
                    __wire::put_field(&mut header, 0, 2, le, 0)?;
                    __wire::put_field(&mut header, 2, 2, le, 2)?;
                    __wire::put_field(&mut header, 4, 2, le, 9)?;
                    __wire::put_field(&mut header, 6, 2, le, 4)?;
                    w.put(&header)?;
                    value.__write_block(w, le)
                }
            }
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let choice = s.rng.below(2);
            match choice {
                0 => {
                    let value = <__Case10x0 as __wire::Codec>::sample(s)?;
                    Ok(Self::Order(value))
                }
                _ => {
                    let value = <__Case10x1 as __wire::Codec>::sample(s)?;
                    Ok(Self::Ping(value))
                }
            }
        })
    }
}
impl fictionet::stdlib::codec::Wire for Message {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    /// Refuses block lengths that do not hold the fixed fields.
    /// Refuses entry counts above their limits.
    /// Refuses mismatched header values.
    /// Refuses undeclared set bits.
    /// Refuses unknown tags.
    /// Refuses values outside declared ranges.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    /// Refuses entry counts above their limits.
    /// Refuses reserved nulls in Some.
    /// Refuses undeclared set bits.
    /// Refuses values outside declared ranges.
    /// Refuses wrong fixed data lengths.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[cfg(test)]
mod generated_tests {
    use super::*;

    #[test]
    fn generated_contracts() -> Result<(), Error> {
        {
            use super::Side as Value;
            __wire::check::<Value>()?;
        }
        {
            use super::Status as Value;
            __wire::check::<Value>()?;
        }
        {
            use super::Flags as Value;
            __wire::check::<Value>()?;
        }
        {
            use super::Price as Value;
            __wire::check::<Value>()?;
        }
        {
            use super::Quote as Value;
            __wire::check::<Value>()?;
        }
        {
            use super::QuoteKind as Value;
            __wire::check::<Value>()?;
        }
        {
            use super::Order as Value;
            __wire::check::<Value>()?;
        }
        {
            use super::OrderFills as Value;
            __wire::check::<Value>()?;
        }
        {
            use super::OrderFillsLegs as Value;
            __wire::check::<Value>()?;
        }
        {
            use super::Ping as Value;
            __wire::check::<Value>()?;
        }
        {
            use super::Message as Value;
            __wire::check::<Value>()?;
        }
        Ok(())
    }
}
