// Generated by fictionet-codegen 0.1.0 from the ir schema.
// Schema: "short_names.json"
// Regenerate with: fictionet-codegen ir "short_names.json" -o <this file>

#![doc = "Wire types generated by fictionet-codegen."]

/// Maximum encoded bytes in one value.
pub const MAX_MESSAGE: usize = 1048576;
/// Default limit used for omitted collection lengths.
pub const MAX_COLLECTION: usize = 4096;
/// Maximum nested value operations, including named types and groups.
pub const MAX_DEPTH: usize = 32;
/// Maximum requested heap bytes for a decoded value.
pub const MAX_ALLOCATION: usize = 8388608;
/// Maximum visited structural nodes in one value.
pub const MAX_NODES: usize = 65536;

fictionet::stdlib::codec::generated_runtime!(
    Error,
    __wire,
    MAX_MESSAGE,
    MAX_DEPTH,
    MAX_ALLOCATION,
    MAX_NODES
);

#[doc = "Wire type A."]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum A {
    #[doc = "b"]
    B,
}
impl __wire::Codec for A {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            let v = r.scalar::<u8>(le)?;
            match v {
                1 => {
                    let value = Self::B;
                    Ok(value)
                }
                _ => Err(Error::Value),
            }
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let v: u8 = match self {
                Self::B => 1,
            };
            w.scalar(v, le)
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let _ = s;
            let value = Self::B;
            Ok(value)
        })
    }
}
impl fictionet::stdlib::codec::Wire for A {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    /// Refuses unknown enum values.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

/// Frames of [`A`], with fixed magic and a body-length prefix.
#[derive(Clone, Copy, Debug, Default)]
pub struct S;
impl S {
    const MAGIC: &'static [u8] = b"";

    /// Appends a complete frame. Refuses invalid bodies and prefix overflow.
    /// Errors leave the destination unchanged.
    pub fn write(value: &A, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write_frame(value, out, Self::MAGIC, 1, false, false)
    }
}
impl fictionet::stdlib::codec::Decode for S {
    type Item = A;
    type Error = Error;
    const NAME: &'static str = "S";

    fn capacity(&self) -> usize {
        MAX_MESSAGE + 1
    }

    /// Refuses bad magic, oversized prefixes, and invalid complete bodies.
    /// Partial frames return Need, including at EOF. Holds no input.
    fn decode(
        &mut self,
        input: &[u8],
        _eof: bool,
    ) -> Result<fictionet::stdlib::codec::Step<Self::Item>, Error> {
        __wire::frame(input, Self::MAGIC, 1, false, false)
    }
}

#[cfg(test)]
mod generated_tests {
    use super::*;

    #[test]
    fn generated_contracts() -> Result<(), Error> {
        {
            use super::A as Value;
            __wire::check::<Value>()?;
        }
        {
            use super::S as Frames;
            __wire::check_stream(|| Frames, Frames::write, 1);
        }
        Ok(())
    }
}
