// Generated by fictionet-codegen 0.1.0 from the ir schema.
// Schema: "xdr.json"
// Regenerate with: fictionet-codegen ir "xdr.json" -o <this file>

#![doc = "Wire types generated by fictionet-codegen."]

/// Maximum encoded bytes in one value.
pub const MAX_MESSAGE: usize = 1048576;
/// Default limit used for omitted collection lengths.
pub const MAX_COLLECTION: usize = 4096;
/// Maximum nested value operations, including named types and groups.
pub const MAX_DEPTH: usize = 32;
/// Maximum requested heap bytes for a decoded value.
pub const MAX_ALLOCATION: usize = 8388608;
/// Maximum visited structural nodes in one value.
pub const MAX_NODES: usize = 65536;

fictionet::stdlib::codec::generated_runtime!(
    Error,
    __wire,
    MAX_MESSAGE,
    MAX_DEPTH,
    MAX_ALLOCATION,
    MAX_NODES
);

type __Value0 = u32;
#[inline]
fn __read0(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value0, Error> {
    r.scalar::<u32>(le)
}
#[inline]
fn __write0(w: &mut __wire::Writer, v: &__Value0, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample0(s: &mut __wire::Sampler) -> Result<__Value0, Error> {
    Ok(s.number() as u32)
}

type __Value1 = i32;
#[inline]
fn __read1(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value1, Error> {
    r.scalar::<i32>(le)
}
#[inline]
fn __write1(w: &mut __wire::Writer, v: &__Value1, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample1(s: &mut __wire::Sampler) -> Result<__Value1, Error> {
    Ok(s.number() as i32)
}

type __Value2 = u64;
#[inline]
fn __read2(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value2, Error> {
    r.scalar::<u64>(le)
}
#[inline]
fn __write2(w: &mut __wire::Writer, v: &__Value2, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample2(s: &mut __wire::Sampler) -> Result<__Value2, Error> {
    Ok(s.number())
}

type __Value3 = i64;
#[inline]
fn __read3(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value3, Error> {
    r.scalar::<i64>(le)
}
#[inline]
fn __write3(w: &mut __wire::Writer, v: &__Value3, le: bool) -> Result<(), Error> {
    w.scalar(*v, le)
}
#[cfg(test)]
fn __sample3(s: &mut __wire::Sampler) -> Result<__Value3, Error> {
    Ok(s.number() as i64)
}

type __Value4 = Choice;
#[inline]
fn __read4(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value4, Error> {
    <__Value4 as __wire::Codec>::read(r, le)
}
#[inline]
fn __write4(w: &mut __wire::Writer, v: &__Value4, le: bool) -> Result<(), Error> {
    __wire::Codec::encode(v, w, le)
}
#[cfg(test)]
fn __sample4(s: &mut __wire::Sampler) -> Result<__Value4, Error> {
    <__Value4 as __wire::Codec>::sample(s)
}

const __LIMIT5: usize = 4;
type __Value5 = Vec<u8>;
#[inline]
fn __read5(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value5, Error> {
    r.bytes(0, __LIMIT5, le)
}
#[inline]
fn __write5(w: &mut __wire::Writer, v: &__Value5, le: bool) -> Result<(), Error> {
    w.bytes(v, 0, __LIMIT5, le)
}
#[cfg(test)]
fn __sample5(s: &mut __wire::Sampler) -> Result<__Value5, Error> {
    s.bytes(0, __LIMIT5)
}

const __LIMIT6: usize = 8;
type __Value6 = Vec<__Value0>;
#[inline]
fn __read6(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value6, Error> {
    r.group(4, __LIMIT6, 4, le, |r| __read0(r, le))
}
#[inline]
fn __write6(w: &mut __wire::Writer, v: &__Value6, le: bool) -> Result<(), Error> {
    w.group(v, 4, __LIMIT6, le, |w, v| __write0(w, v, le))
}
#[cfg(test)]
fn __sample6(s: &mut __wire::Sampler) -> Result<__Value6, Error> {
    s.group(__LIMIT6, __sample0)
}

type __Value7 = Option<__Value2>;
#[inline]
fn __read7(r: &mut __wire::Reader<'_>, le: bool) -> Result<__Value7, Error> {
    r.optional(4, le, |r| __read2(r, le))
}
#[inline]
fn __write7(w: &mut __wire::Writer, v: &__Value7, le: bool) -> Result<(), Error> {
    w.optional(v, 4, le, |w, v| __write2(w, v, le))
}
#[cfg(test)]
fn __sample7(s: &mut __wire::Sampler) -> Result<__Value7, Error> {
    s.optional(__sample2)
}

#[doc = "Wire type Choice."]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Choice {
    #[doc = "negative"]
    Negative,
    #[doc = "zero"]
    Zero,
    #[doc = "positive"]
    Positive,
}
impl __wire::Codec for Choice {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            let v = r.scalar::<i32>(le)?;
            match v {
                -1 => {
                    let value = Self::Negative;
                    Ok(value)
                }
                0 => {
                    let value = Self::Zero;
                    Ok(value)
                }
                1 => {
                    let value = Self::Positive;
                    Ok(value)
                }
                _ => Err(Error::Value),
            }
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let v: i32 = match self {
                Self::Negative => -1,
                Self::Zero => 0,
                Self::Positive => 1,
            };
            w.scalar(v, le)
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let choice = s.rng.below(3);
            match choice {
                0 => {
                    let value = Self::Negative;
                    Ok(value)
                }
                1 => {
                    let value = Self::Zero;
                    Ok(value)
                }
                _ => {
                    let value = Self::Positive;
                    Ok(value)
                }
            }
        })
    }
}
impl fictionet::stdlib::codec::Wire for Choice {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    /// Refuses unknown enum values.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[doc = "Wire type Record."]
#[derive(Clone, Debug, PartialEq)]
pub struct Record {
    #[doc = "unsigned"]
    pub unsigned: u32,
    #[doc = "signed"]
    pub signed: i32,
    #[doc = "wide"]
    pub wide: u64,
    #[doc = "negative"]
    pub negative: i64,
    #[doc = "choice"]
    pub choice: Choice,
    #[doc = "opaque"]
    pub opaque: Vec<u8>,
    #[doc = "entries"]
    pub entries: Vec<u32>,
    #[doc = "maybe"]
    pub maybe: Option<u64>,
}
impl __wire::Codec for Record {
    fn read(r: &mut __wire::Reader<'_>, le: bool) -> Result<Self, Error> {
        r.nested(|r| {
            let __field0 = __read0(r, le)?;
            let __field1 = __read1(r, le)?;
            let __field2 = __read2(r, le)?;
            let __field3 = __read3(r, le)?;
            let __field4 = __read4(r, le)?;
            let __field5 = __read5(r, le)?;
            let __field6 = __read6(r, le)?;
            let __field7 = __read7(r, le)?;
            let value = Self {
                unsigned: __field0,
                signed: __field1,
                wide: __field2,
                negative: __field3,
                choice: __field4,
                opaque: __field5,
                entries: __field6,
                maybe: __field7,
            };
            Ok(value)
        })
    }
    fn encode(&self, w: &mut __wire::Writer, le: bool) -> Result<(), Error> {
        w.nested(|w| {
            let value = &self.unsigned;
            __write0(w, value, le)?;
            let value = &self.signed;
            __write1(w, value, le)?;
            let value = &self.wide;
            __write2(w, value, le)?;
            let value = &self.negative;
            __write3(w, value, le)?;
            let value = &self.choice;
            __write4(w, value, le)?;
            let value = &self.opaque;
            __write5(w, value, le)?;
            let value = &self.entries;
            __write6(w, value, le)?;
            let value = &self.maybe;
            __write7(w, value, le)?;
            Ok(())
        })
    }
    #[cfg(test)]
    fn sample(s: &mut __wire::Sampler) -> Result<Self, Error> {
        s.nested(|s| {
            let __field0 = __sample0(s)?;
            let __field1 = __sample1(s)?;
            let __field2 = __sample2(s)?;
            let __field3 = __sample3(s)?;
            let __field4 = __sample4(s)?;
            let __field5 = __sample5(s)?;
            let __field6 = __sample6(s)?;
            let __field7 = __sample7(s)?;
            let value = Self {
                unsigned: __field0,
                signed: __field1,
                wide: __field2,
                negative: __field3,
                choice: __field4,
                opaque: __field5,
                entries: __field6,
                maybe: __field7,
            };
            Ok(value)
        })
    }
}
impl fictionet::stdlib::codec::Wire for Record {
    type ParseError = Error;
    type WriteError = Error;

    /// Follows the [`Wire::parse`](fictionet::stdlib::codec::Wire::parse) contract.
    /// Refuses flags other than 0 or 1.
    /// Refuses unknown enum values.
    fn parse(bytes: &[u8]) -> Result<Self, Error> {
        __wire::parse(bytes, false)
    }

    /// Follows the [`Wire::write`](fictionet::stdlib::codec::Wire::write) contract.
    /// Refuses wrong fixed data lengths.
    fn write(&self, out: &mut Vec<u8>) -> Result<(), Error> {
        __wire::write(self, out, false)
    }
}

#[cfg(test)]
mod generated_tests {
    use super::*;

    #[test]
    fn generated_contracts() -> Result<(), Error> {
        {
            use super::Choice as Value;
            __wire::check::<Value>()?;
        }
        {
            use super::Record as Value;
            __wire::check::<Value>()?;
        }
        Ok(())
    }
}
