//! Protocol files compiled as modules of a separate consumer crate.
//! Unit tests run in the SDK; this fixture only checks public dependencies.
#![cfg(not(test))]
#![allow(dead_code)]

// A macro keeps rustfmt from following the #[path] modules.
macro_rules! protocols {
    () => {
        #[path = "../../src/observe/protocols.rs"]
        pub mod observe_protocols;
        #[path = "../../src/observe/tls.rs"]
        pub mod observe_tls;
        #[path = "../../src/observe/conversation.rs"]
        pub mod observe_conversation;
        #[path = "../../src/stdlib/codec/interceptor.rs"]
        pub mod interceptor;
        #[path = "../../src/stdlib/codec/recorder.rs"]
        pub mod recorder;
        #[path = "../../src/stdlib/codec/faults.rs"]
        pub mod faults;
        #[path = "../../src/stdlib/codec/lcg.rs"]
        pub mod lcg;
        #[path = "../../src/stdlib/amqp.rs"]
        pub mod amqp;
        #[path = "../../src/stdlib/asn1.rs"]
        pub mod asn1;
        #[path = "../../src/stdlib/bacnet.rs"]
        pub mod bacnet;
        #[path = "../../src/stdlib/bgp.rs"]
        pub mod bgp;
        #[path = "../../src/stdlib/cboe_boe.rs"]
        pub mod cboe_boe;
        #[path = "../../src/stdlib/cboe_pitch.rs"]
        pub mod cboe_pitch;
        #[path = "../../src/stdlib/cme_mdp3.rs"]
        pub mod cme_mdp3;
        #[path = "../../src/stdlib/coap.rs"]
        pub mod coap;
        #[path = "../../src/stdlib/cotp.rs"]
        pub mod cotp;
        #[path = "../../src/stdlib/dcerpc.rs"]
        pub mod dcerpc;
        #[path = "../../src/stdlib/dhcp.rs"]
        pub mod dhcp;
        #[path = "../../src/stdlib/dhcpv6.rs"]
        pub mod dhcpv6;
        #[path = "../../src/stdlib/diameter.rs"]
        pub mod diameter;
        #[path = "../../src/stdlib/dnp3.rs"]
        pub mod dnp3;
        #[path = "../../src/stdlib/dtls.rs"]
        pub mod dtls;
        #[path = "../../src/stdlib/enip.rs"]
        pub mod enip;
        #[path = "../../src/stdlib/fast.rs"]
        pub mod fast;
        #[path = "../../src/stdlib/fastcgi.rs"]
        pub mod fastcgi;
        #[path = "../../src/stdlib/fix.rs"]
        pub mod fix;
        #[path = "../../src/stdlib/ftp.rs"]
        pub mod ftp;
        #[path = "../../codegen/tests/golden/recursive.rs"]
        pub mod generated_recursive;
        #[path = "../../src/stdlib/geneve.rs"]
        pub mod geneve;
        #[path = "../../src/stdlib/git_protocol.rs"]
        pub mod git_protocol;
        #[path = "../../src/stdlib/gre.rs"]
        pub mod gre;
        #[path = "../../src/stdlib/grpc.rs"]
        pub mod grpc;
        #[path = "../../src/stdlib/hpack.rs"]
        pub mod hpack;
        #[path = "../../src/stdlib/httpd.rs"]
        pub mod httpd;
        #[path = "../../src/stdlib/huffman.rs"]
        pub mod huffman;
        #[path = "../../src/stdlib/http1.rs"]
        pub mod http1;
        #[path = "../../src/stdlib/http2.rs"]
        pub mod http2;
        #[path = "../../src/stdlib/http3.rs"]
        pub mod http3;
        #[path = "../../src/stdlib/iec104.rs"]
        pub mod iec104;
        #[path = "../../src/stdlib/igmp.rs"]
        pub mod igmp;
        #[path = "../../src/stdlib/ike.rs"]
        pub mod ike;
        #[path = "../../src/stdlib/imap.rs"]
        pub mod imap;
        #[path = "../../src/stdlib/imf.rs"]
        pub mod imf;
        #[path = "../../src/stdlib/ipp.rs"]
        pub mod ipp;
        #[path = "../../src/stdlib/ipsec.rs"]
        pub mod ipsec;
        #[path = "../../src/stdlib/itch.rs"]
        pub mod itch;
        #[path = "../../src/stdlib/journal.rs"]
        pub mod journal;
        #[path = "../../src/stdlib/json.rs"]
        pub mod json;
        #[path = "../../src/stdlib/json_schema.rs"]
        pub mod json_schema;
        #[path = "../../src/stdlib/jsonrpc.rs"]
        pub mod jsonrpc;
        #[path = "../../src/stdlib/kafka.rs"]
        pub mod kafka;
        #[path = "../../src/stdlib/kerberos.rs"]
        pub mod kerberos;
        #[path = "../../src/stdlib/l2tp.rs"]
        pub mod l2tp;
        #[path = "../../src/stdlib/ldap.rs"]
        pub mod ldap;
        #[path = "../../src/stdlib/memcache.rs"]
        pub mod memcache;
        #[path = "../../src/stdlib/mime_multipart.rs"]
        pub mod mime_multipart;
        #[path = "../../src/stdlib/modbus.rs"]
        pub mod modbus;
        #[path = "../../src/stdlib/moldudp64.rs"]
        pub mod moldudp64;
        #[path = "../../src/stdlib/mongodb.rs"]
        pub mod mongodb;
        #[path = "../../src/stdlib/mqtt.rs"]
        pub mod mqtt;
        #[path = "../../src/stdlib/mysql.rs"]
        pub mod mysql;
        #[path = "../../src/stdlib/nbdgm.rs"]
        pub mod nbdgm;
        #[path = "../../src/stdlib/nbns.rs"]
        pub mod nbns;
        #[path = "../../src/stdlib/nbss.rs"]
        pub mod nbss;
        #[path = "../../src/stdlib/net.rs"]
        pub mod net;
        #[path = "../../src/stdlib/nfs.rs"]
        pub mod nfs;
        #[path = "../../src/stdlib/ntlmssp.rs"]
        pub mod ntlmssp;
        #[path = "../../src/stdlib/ntp.rs"]
        pub mod ntp;
        #[path = "../../src/stdlib/ocsp.rs"]
        pub mod ocsp;
        #[path = "../../src/stdlib/onc_rpc.rs"]
        pub mod onc_rpc;
        #[path = "../../src/stdlib/opcua.rs"]
        pub mod opcua;
        #[path = "../../src/stdlib/openvpn.rs"]
        pub mod openvpn;
        #[path = "../../src/stdlib/ospf.rs"]
        pub mod ospf;
        #[path = "../../src/stdlib/ouch.rs"]
        pub mod ouch;
        #[path = "../../src/stdlib/pcp.rs"]
        pub mod pcp;
        #[path = "../../src/stdlib/pim.rs"]
        pub mod pim;
        #[path = "../../src/stdlib/pop3.rs"]
        pub mod pop3;
        #[path = "../../src/stdlib/portmap.rs"]
        pub mod portmap;
        #[path = "../../src/stdlib/postgres.rs"]
        pub mod postgres;
        #[path = "../../src/stdlib/prefix_int.rs"]
        pub mod prefix_int;
        #[path = "../../src/stdlib/protobuf.rs"]
        pub mod protobuf;
        #[path = "../../src/stdlib/proxy_protocol.rs"]
        pub mod proxy_protocol;
        #[path = "../../src/stdlib/qpack.rs"]
        pub mod qpack;
        #[path = "../../src/stdlib/quic.rs"]
        pub mod quic;
        #[path = "../../src/stdlib/radius.rs"]
        pub mod radius;
        #[path = "../../src/stdlib/rdp.rs"]
        pub mod rdp;
        #[path = "../../src/stdlib/resp.rs"]
        pub mod resp;
        #[path = "../../src/stdlib/rfb.rs"]
        pub mod rfb;
        #[path = "../../src/stdlib/rip.rs"]
        pub mod rip;
        #[path = "../../src/stdlib/rtcp.rs"]
        pub mod rtcp;
        #[path = "../../src/stdlib/rtp.rs"]
        pub mod rtp;
        #[path = "../../src/stdlib/rtsp.rs"]
        pub mod rtsp;
        #[path = "../../src/stdlib/sbe.rs"]
        pub mod sbe;
        #[path = "../../src/stdlib/scenario.rs"]
        pub mod scenario;
        #[path = "../../src/stdlib/sdp.rs"]
        pub mod sdp;
        #[path = "../../src/stdlib/serve.rs"]
        pub mod serve;
        #[path = "../../src/stdlib/sftp.rs"]
        pub mod sftp;
        #[path = "../../src/stdlib/sip.rs"]
        pub mod sip;
        #[path = "../../src/stdlib/smb2.rs"]
        pub mod smb2;
        #[path = "../../src/stdlib/smtp.rs"]
        pub mod smtp;
        #[path = "../../src/stdlib/snmp.rs"]
        pub mod snmp;
        #[path = "../../src/stdlib/socks.rs"]
        pub mod socks;
        #[path = "../../src/stdlib/soupbintcp.rs"]
        pub mod soupbintcp;
        #[path = "../../src/stdlib/spnego.rs"]
        pub mod spnego;
        #[path = "../../src/stdlib/ssh.rs"]
        pub mod ssh;
        #[path = "../../src/stdlib/sse.rs"]
        pub mod sse;
        #[path = "../../src/stdlib/stun.rs"]
        pub mod stun;
        #[path = "../../src/stdlib/syslog.rs"]
        pub mod syslog;
        #[path = "../../src/stdlib/tcp_stream.rs"]
        pub mod tcp_stream;
        #[path = "../../src/stdlib/tds.rs"]
        pub mod tds;
        #[path = "../../src/stdlib/telnet.rs"]
        pub mod telnet;
        #[path = "../../src/stdlib/tftp.rs"]
        pub mod tftp;
        #[path = "../../src/stdlib/thrift.rs"]
        pub mod thrift;
        #[path = "../../src/stdlib/tpkt.rs"]
        pub mod tpkt;
        #[path = "../../src/stdlib/urlencoded_form.rs"]
        pub mod urlencoded_form;
        #[path = "../../src/stdlib/vrrp.rs"]
        pub mod vrrp;
        #[path = "../../src/stdlib/vxlan.rs"]
        pub mod vxlan;
        #[path = "../../src/stdlib/wake_on_lan.rs"]
        pub mod wake_on_lan;
        #[path = "../../src/stdlib/web.rs"]
        pub mod web;
        #[path = "../../src/stdlib/websocket.rs"]
        pub mod websocket;
        #[path = "../../src/stdlib/whois.rs"]
        pub mod whois;
        #[path = "../../src/stdlib/wireguard.rs"]
        pub mod wireguard;
        #[path = "../../src/stdlib/x509.rs"]
        pub mod x509;
        #[path = "../../src/stdlib/xml.rs"]
        pub mod xml;
        #[path = "../../src/stdlib/zabbix.rs"]
        pub mod zabbix;
    };
}

protocols!();
