// Generated by fictionet-codegen 0.1.0.
// You own this file. You may copy and edit it. Regenerate only by choice.
// Input: "recursive.json"

#![no_main]

#[allow(dead_code)]
#[path = "../../codegen/tests/golden/recursive.rs"]
mod protocol;

use fictionet::stdlib::test_support::contract;
use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: &[u8]| {
    {
        use protocol::Node as Value;
        contract::check_wire::<Value>(data);
    }
    {
        use protocol::Shared as Value;
        contract::check_wire::<Value>(data);
    }
    {
        use protocol::Nodes as Frames;
        contract::check_decode_with_alloc_limit(|| Frames, data, 2 * (protocol::MAX_MESSAGE + 6));
    }
});
